### ISSUE TITLE
Coloring problem in editors

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#1002]
when a search command produces several items, the first one is in red but the others are in black
both in emacs and vscode

**Comment by Alidra** [comment]
Hi @fblanqui,
Would you provide an example please?

**Comment by fblanqui** [comment]
Actually, everything is in red now. But it should be in black.

**Comment by fblanqui** [comment]
To reproduce:
```
make matita
cd libraries/matita
lambdapi index --lib-root . --rule LPSearch.lp matita*.dk
```
+ command example in editor:
```
search "hyp = (nat → bool)";
```
