### ISSUE TITLE
include atom plugin into editors directory?

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#104]
Include https://github.com/Deducteam/atom-dedukti into Lambdapi directory editors/?

**Comment by ejgallego** [comment]
The main downside of this when we looked at that is that atom expects plugins to live in their own git repos. But I am not sure if this is really a restriction

**Comment by ejgallego** [comment]
So indeed I am closing this a wontfix; atom mode is working fine [but for goal display but that should be easy to fix, likely some format change in labmdapi]

IMO the coupling among labmdapi is quite weak, other than the goal format [which should be better documented] we follow the standard LSP.
