### ISSUE TITLE
Reduction engine behavior

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/lambdapi#105]
I found the following document on the Coq dev repo that highlights a problem in the reduction engine of Coq:
```
https://github.com/coq/coq/blob/master/dev/doc/notes-on-conversion.v
```

I wanted to give it a try with lambdapi. So here is the following code (old syntax)
```
nat : Type.

0 : nat.

S : nat -> nat.

def F0 : nat -> nat -> nat.

def F : nat -> nat -> nat.

def ack : nat -> nat -> nat.

[] F 0 --> S.
[n] F (S n) --> m : nat => F0 n m.

[n1] F0 n1 0 --> F n1 (S 0).
[n1,n3] F0 n1 (S n3) --> F n1 (F0 n1 n3).

[n] ack n --> F n.

def 4 := S (S (S (S 0))).

def OMEGA : nat := ack 4 4.

def f (x : nat) := x.

#ASSERT OMEGA == OMEGA.

(; TOO SLOW ;)
#ASSERT OMEGA == f OMEGA.
(; TOO SLOW ;)
(; #ASSERT f OMEGA == OMEGA. ;)
```

In this example, `OMEGA` is just a term that takes forever to compute. The problem raised by this example is that if `OMEGA` is behind the identity function, then `lambdapi` (and `Dedukti`) computes the normal form `OMEGA` to check the convertibility of the two expressions.

In Coq, they observe the same problem only when `f` is on the right-hand side, but in `lambdapi` this happens in both cases. 

I am not sure that this behavior can be fixed easily. However, I thought it was interesting to be aware of this shortcoming.

**Comment by rlepigre** [comment]
Assert does not check typing (if I'm not mistaken), so this is to be expected.

**Comment by francoisthire** [comment]
Maybe I am mistaken, but I think that what is problematic here is not related to types. We are only interested in the behavior of the rewrite engine and more specifically the strategy used by the engine.

**Comment by Gaspi** [comment]
However a more clever implementation of Ack allows WHNF to be quickly computed by reducing the first argument first until we get a successor.
```
N : Type.
0 : N.
S : N -> N.

def F : N -> N -> N.

def ack : N -> N -> N.
[m]   ack 0     m     --> S m.
[n,m] ack (S n) m     --> ack n (F n m).

[n,m] F n 0     --> S 0.
[n,m] F n (S m) --> ack (S n) m.

def 4 := S (S (S (S 0))).
def OMEGA := ack 4 4.
def f (x:N) := x.
#EVAL[WHNF] OMEGA.
#ASSERT f OMEGA == OMEGA.
```

**Comment by francoisthire** [comment]
No indeed, it is not surprising. However, it might be interesting at some
point to be able to have a better control over the reduction strategy at
some point.

Le jeu. 25 oct. 2018 à 14:47, GuillaumeGen <notifications@github.com> a
écrit :
