### ISSUE TITLE
Unable to use rewrite tactic on lambda abstractions, VSCode Interface stops working properly 

### ISSUE THREAD

**Issue by melanie-taprogge** [Deducteam/lambdapi#1071]
I am trying to use simplification rules like the following with rewrite tactics:

```
symbol Simp10_eq x : Prf(eq [↑ o] (inEq [↑ o] x x) ⊥);
```

It works just fine in cases like the following: 

```
symbol Test1: Prf(eq [↑ o] (inEq [(↑ o)] p p ) ⊥) ≔
begin
    rewrite Simp10_eq;
    reflexivity;
end;
```

But in cases involving lambda terms as in :

```
symbol Test2: Prf(eq [↑ o] (inEq [(↑ o)] ((λ x, x ∨ x ) p) ((λ x, x ∨ x ) p) ) ⊥) ≔
begin
    rewrite Simp10_eq;
    reflexivity;
end;
```

I get the "Assertion failed" error on command line and the VS-Code interface seems stop functioning the moment I finish/ uncomment the `rewrite Simp10_eq;` line and either does not return an error message at all (but still does not carry out the rewriting) or returns a non-sensical error message (for instance I get the error `Unexpected token: "/"` for the beginning of the rewrite tactic line, even if there is no "/" character).

**Comment by fblanqui** [comment]
Hi Melanie. Thank you for your issue. Could you please provide us with a small standalone file so that we can reproduce the error? Best regards, Frédéric.

**Comment by melanie-taprogge** [comment]
I just tried reinstalling Lambdapi and it actually fixed my problem!
