### ISSUE TITLE
Could not declare symbol "-1" anymore

### ISSUE THREAD

**Issue by NotBad4U** [Deducteam/lambdapi#1103]
The stdlib declare the symbol "-1" here https://github.com/Deducteam/lambdapi-stdlib/blob/6559f043ef0c9cc4c5bf2af2e1707e11cd53debb/Nat.lp#L166
Nat.lp#L166
```
symbol -1 : ℕ → ℕ; notation -1 postfix 100;

```

But it sound some current changes on the master branch make Lambdapi reject `-` as qid for a symbol.
```
[/Users/alessiocoltellacci/Projects/Inria/lambdapi-stdlib/Nat.lp:166:7-9 ] Unexpected token: "-1".
```

**Comment by Alidra** [comment]
It seems the problem was introduced by [commit 0902592](https://github.com/Deducteam/lambdapi/commit/09025929094d27ac2d401269d8bbd677e06e2dd2)

**Comment by fblanqui** [comment]
We really need to add in CI the checking of the libraries that are in:
- https://github.com/Deducteam/lambdapi-logics
- https://github.com/Deducteam/lambdapi-stdlib
@Alidra , could you please try to set up this?

**Comment by fblanqui** [comment]
@Alidra: this kind of corresponds to #829 though just for logics and stdlib.
