### ISSUE TITLE
CI: build_vscode_extension failure

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#1118]
build_vscode_extension fails in https://github.com/fblanqui/lambdapi/actions/runs/9570064647/job/26383997168 .
Note also the warnings.

**Comment by Alidra** [comment]
Hi Frédéric,

I just checked. The pipeline fails because your repository is not up to date with Deducteam/Lambdapi.
Synchronizing the repos should fix it.

**Comment by fblanqui** [comment]
Right. Thank you!
