### ISSUE TITLE
rewrite under quantifiers

### ISSUE THREAD

**Issue by bodeveix** [Deducteam/lambdapi#1120]
The rewrite tactic fails to cross quantifiers as shown in the proof of the "bug" theorem of the attached file.

[bug3.txt](https://github.com/user-attachments/files/15919969/bug3.txt)

**Comment by fblanqui** [comment]
Thank you for the issue. This is a known issue indeed. I close it since it is a duplicate of #694 .

**Comment by fblanqui** [comment]
There is a difference with #694 though which is that the LHS is closed and does not contain variables that can be instantiated by terms containing bound variables.
