### ISSUE TITLE
VSCode plugin: allowing custom command line arguments 

### ISSUE THREAD

**Issue by AkihisaYamada** [Deducteam/lambdapi#1163]
Hi, I propose to allow customizing command line arguments in the VSCode plugin. Currently one can customize the lambdapi executable, which is executed with fixed argument "lsp". I propose arguments be also configurable.

This will allow, e.g. on Windows, run lambdapi in WSL, via `{ command: "wsl", args: ["lambdapi", "lsp"] }`.

**Comment by Alidra** [comment]
> Hi, I propose to allow customizing command line arguments in the VSCode plugin. Currently one can customize the lambdapi executable, which is executed with fixed argument "lsp". I propose arguments be also configurable.
> 
> This will allow, e.g. on Windows, run lambdapi in WSL, via `{ command: "wsl", args: ["lambdapi", "lsp"] }`.

**Comment by Alidra** [comment]
Thanks @AkihisaYamada. This should be possible with PR 1164
