### ISSUE TITLE
Is Print.pp_rule correct wrt pattern variable naming?

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#122]
https://github.com/Deducteam/lambdapi/blob/8060eee5a306ff4dd13291876e459c9a23c1e65f/src/print.ml#L70

Why the "variables" of the RHS should be printed with the same names as the corresponding pattern variables of the LHS?

The function Confluence.print_rule is quite different.

https://github.com/Deducteam/lambdapi/blob/8060eee5a306ff4dd13291876e459c9a23c1e65f/src/confluence.ml#L54

**Comment by rlepigre** [comment]
I don't understand your concern, do you have an example of bad behavior?
