### ISSUE TITLE
Documentation missing for the field ctxt of the type rule + naming problem

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#123]
https://github.com/Deducteam/lambdapi/blob/8060eee5a306ff4dd13291876e459c9a23c1e65f/src/terms.ml#L114

Currently, ctxt seems to be used in Confluence only. But there is perhaps a problem in Print.pp_rule (see https://github.com/Deducteam/lambdapi/issues/122). If so, it could be the case that ctxt is useful in Print too.

Moreover, it seems that the names are duplicated between the ctxt field and the string argument of Patt:

https://github.com/Deducteam/lambdapi/blob/8060eee5a306ff4dd13291876e459c9a23c1e65f/src/terms.ml#L29

Moreover, it is not nice to use the same name (ctxt) for two different things: the field ctxt in the type rule and the type Ctxt.t for typing contexts:

https://github.com/Deducteam/lambdapi/blob/8060eee5a306ff4dd13291876e459c9a23c1e65f/src/ctxt.ml#L8

We should rename one.

**Comment by fblanqui** [comment]
I propose to rename to rule field "ctxt" into "vars".

**Comment by rlepigre** [comment]
That's fine with me.
