### ISSUE TITLE
Include code in LaTeX documents

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/lambdapi#125]
Currently, what is the best way to include lambdapi/Dedukti code in a LaTeX document? Is there any plan to provide a nice way to have a colored output? In Agda for example, an option `--latex` is provided (see https://agda.readthedocs.io/en/v2.5.3/tools/generating-latex.html).

**Comment by fblanqui** [comment]
There is no such plan for the moment. Meanwhile, we could add some Latex 
file to include, based on the package listings for instance. Guillaume 
has one we used in the paper. Perhaps someone has one for Dedukti too.

Le 30/11/2018 à 14:50, fthire a écrit :

**Comment by GuillaumeGen** [comment]
Mine is Raphaël's one written for Dedukti 2, adapted for Dedukti 3 syntax (without a specific coloration for pattern variables (like &x)).

**Comment by fblanqui** [comment]
Why not adding it in the directory tools/ ?

Le 30/11/2018 à 16:11, GuillaumeGen a écrit :

**Comment by fblanqui** [comment]
I added tools/lambdapi.tex (to be completed and improved).

**Comment by francoisthire** [comment]
The color grispale is not defined.

**Comment by GuillaumeGen** [comment]
\definecolor{grispale}{RGB}{240,240,240}

**Comment by francoisthire** [comment]
I came up with this which gives less flashy colors. However, I still in favor of using something `minted`.

```latex
\colorlet{dbg}{White!85!Black}
\colorlet{dkw}{Blue!85!Black}
\colorlet{dcmt}{Red!85!Black}
\colorlet{dstr}{Orange!85!Black}
\colorlet{dctx}{Brown!85!Black}
\lstdefinelanguage{Dedukti}
{
  alsoletter={=->:\#\*},
  keywords={symbol,rule,infix,def,thm,:, -->, Type},
  delim=[s][\color{dctx}]{\[}{\]},
  comment=[n]{(;}{;)},
  string=[b]{"},
  stringstyle=\color{dstr},
  commentstyle=\color{dcmt},
  showstringspaces=false,
  numbers=left
}
\lstset{basicstyle={\ttfamily\small\upshape},keywordstyle=\color{dkw}}
\lstset{backgroundcolor=\color{dbg},language={Dedukti}}
```

**Comment by GuillaumeGen** [comment]
I am unable to compile your file, I think you forgot a `\usepackage`. `Black`, `White` and so on with capital letters do not exist with `xcolor`.
Furthermore, my name of color are in French, but they are quite explicit, yours are more cryptic.

**Comment by francoisthire** [comment]
I use the package `xcolor` with dvispnames option:

```latex
\usepackage[dvipsnames]{xcolor}
``` 

You can change the names of colors if you want, that is not the point, especially, you can inline the definitions I used.

**Comment by fblanqui** [comment]
Thanks for doing a PR.

Le 13/02/2019 à 14:46, fthire a écrit :

**Comment by fblanqui** [comment]
Color names should be in French.

Le 13/02/2019 à 14:53, GuillaumeGen a écrit :

**Comment by fblanqui** [comment]
Sorry, I meant in English!!!

Le 13/02/2019 à 15:07, Frédéric Blanqui a écrit :

**Comment by francoisthire** [comment]
This is still not clear what we want, right?
By the way, here is the difference I get between minted/listings:
![dedukti-tex](https://user-images.githubusercontent.com/2529963/52717493-82ab1100-2fa1-11e9-95b1-c66a57a1b741.png)

**Comment by rlepigre** [comment]
@francoisthire: how do you define a new language with Minted?

**Comment by GuillaumeGen** [comment]
I agree with you it is fancier with Minted, but it is explicitly stated in LIPIcs instructions to the authors, that Minted and Pygmentize are not supported: http://drops.dagstuhl.de/styles/lipics-v2019/lipics-v2019-authors/lipics-v2019-authors-guidelines.pdf
So I am quite happy with @rafoo's little definition in Listings.

**Comment by francoisthire** [comment]
I had to fork minted indeed. I am not sure it is the best option though. An alternative would be to maintain this fork.

> I agree with you it is fancier with Minted, but it is explicitly stated in LIPIcs instructions to the authors, that Minted and Pygmentize are not supported: http://drops.dagstuhl.de/styles/lipics-v2019/lipics-v2019-authors/lipics-v2019-authors-guidelines.pdf

This is a false issue thanks to the options "frozencache" and "finalizecache" of `minted`: ftp://ftp.dante.de/tex-archive/macros/latex/contrib/minted/minted.pdf

**Comment by francoisthire** [comment]
Great news! No need to fork anymore. You can give a custom lexer to minted:

```latex
\begin{minted}{dedukti.py:DeduktiLexer -x}
  def foo : Type.
\end{minted}
```

However, this requires to use pygmentize >= 2.2.0 while the packaged version on Ubuntu is 2.1.0.

Hence, we only need to maintain a file `dedukti.py` that I already started to write. I can submit a PR if you want.

**Comment by rlepigre** [comment]
Very cool indeed, please do that! I've been wanting that since I learned that Minded exists.

**Comment by fblanqui** [comment]
Why not providing two Latex setups, one for listings, and one for 
minted? Thanks for doing a PR! :-)

Le 13/02/2019 à 15:11, fthire a écrit :

**Comment by francoisthire** [comment]
See #157 .

**Comment by fblanqui** [comment]
I close this issue as it is mainly solved by the introduction of the files listings.tex and latex_minted/dedukti.py, and we won't provide a LateX output for the moment.
