### ISSUE TITLE
Add a file BRANCHES.md in master

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#126]
with the list of branches and, for each branch, a short description of its purpose.

**Comment by fblanqui** [comment]
Perhaps. Meanwhile, there are currently 2 branches I don't know what they are about: spines and interactive_proof. So, please add BRANCHES.md.

**Comment by rlepigre** [comment]
There is only one branch left. I removed `spines` (I still have a copy on my personal repository https://github.com/rlepigre/lambdapi), and `interactive_proof` is a working branch (that should have been created in my personal repository as well) that will be deleted when @ejgallego fixes the issue with LSP. This branch has a corresponding pull-request: #132. When the PR is accepted, no weird and undocumented branch will remain in the main repository, and it should remain so. Experimental branches should be created in personal repositories, and only merged through pull-requests.
