### ISSUE TITLE
CI broken due to changes in Yojson

### ISSUE THREAD

**Issue by rlepigre** [Deducteam/lambdapi#131]
Everything is in the title. We can either:
 - disable some "warnings as errors"
 - give an upper bound for the version of `yojson` we use
 - update the way we use `yojson` to work with the last version (and require a minimal version).

@ejgallego can you look into this?

**Comment by ejgallego** [comment]
Sure, I propose we update to the new version.

**Comment by rlepigre** [comment]
Great, I'm fine with that!

**Comment by ejgallego** [comment]
The should actually be backwards compatible.

**Comment by rlepigre** [comment]
No, it does not seem te be backward compatible...

```
File "lp-lsp/lsp_base.ml", line 53, characters 29-32:
Error: Unbound type constructor J.t
```

**Comment by ejgallego** [comment]
Let me see...

**Comment by rlepigre** [comment]
I think we need `yojson.1.6.0` now.
