### ISSUE TITLE
The handling of proofs in the LSP server is (temporarily) broken

### ISSUE THREAD

**Issue by rlepigre** [Deducteam/lambdapi#143]
I recently merged #138, which introduces a new API that will be used by @ejgallego to use of finer grain notion of document. The idea is that tactics are now a form of sub-command.

The consequence of me merging this PR is that the LSP mode is unable to handle proofs at the moment. This will hopefully be fixed soon, but I thought it was easier to merge now, since the proof mode was not usable anyway (theorems and proofs handled as a single block, no displaying of the proof context, ...).

**Comment by ejgallego** [comment]
Sadly I am having trouble with Atom, somehow the packages we were relying upon (`atom-languageclient`) have been removed it seems.

So even if I can fix this I may have a hard time testing proofs and goals.

**Comment by rlepigre** [comment]
@ejgallego: note that you can use the emacs mode. I find it works quite well. You just need to run `make install && make install_emacs`, and you need to have `eglot` installed. Let me known if I can help for fixing the server!

**Comment by rlepigre** [comment]
@ejgallego: if I understand correctly, what you meant is actually that Atom is the only editor with full support for proofs, right? Anyway, it would already be great to be able to check proofs incrementally, without the mode failing. We can try to find a solution for displaying goals properly in a second step.

**Comment by ejgallego** [comment]
Fixed by #144
