### ISSUE TITLE
Add a pre-commit hook in github?

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#147]
Hi Rodolphe. With https://github.com/Deducteam/lambdapi/commit/b835172eea912434f799e53d6d145109784113d6, you added some script doing some sanity checks and a Makefile target. This could be done automatically with git.

**Comment by rlepigre** [comment]
I known you can do that locally using `git`, but the file cannot be shared since it is in the `.git` directory. What we could do is add the check to the CI, but for now the script I wrote always returns successfully (with exit code 0), so failure cannot be tested.

**Comment by fblanqui** [comment]
A discussion on file indentation started on https://github.com/Deducteam/lambdapi/pull/159#issuecomment-463662632 .

**Comment by GuillaumeGen** [comment]
In PR #165 , I suggest running `make sanity_check` with continuous integration. I agree with @fblanqui it is required if we want everyone to follow these rules.

**Comment by rlepigre** [comment]
PR #165 has been merged. This is a start, but it only does its job if every commit goes through a PR, and that it is only merged after CI is successful. Can we close this issue?

**Comment by GuillaumeGen** [comment]
Otherwise, you receive a mail saying that build on `master` are broken.

**Comment by GuillaumeGen** [comment]
And who has the right to commit on `master` without doing a PR?

**Comment by rlepigre** [comment]
Only @fblanqui and I can push to `master` directly, I think. But we should try to avoid that.
