### ISSUE TITLE
How to add a shortcut for ≡ in editors/emacs/lambdapi.el?

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#148]
How to map, say ==, to ≡ ? I tried by adding:
`("=="   ?≡) ("\\equiv"  ?≡)`
but it doesn't work.

By the way, shouldn't \to be replaced by \rightarrow, and \To by \Rightarrow?

**Comment by rlepigre** [comment]
Maybe you forgot to run `make install_emacs` again. It worked for me, and I added new aliases for the arrow symbols (we can keep both names, plus `->` and `=>`).
