### ISSUE TITLE
Dependency graph of the project

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#154]
It would be nice to provide a dependency graph of the source files to help newcomers to enter the code.

**Comment by fblanqui** [comment]
After http://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html, a .dot graph can be generated using ocamldoc -dot:

> Generate a dependency graph for the toplevel modules, in a format suitable for displaying and processing by dot. The dot tool is available from http://www.research.att.com/sw/tools/graphviz/. The textual representation of the graph is written to the file ocamldoc.out, or to the file specified with the -o option. Use dot ocamldoc.out to display it.

**Comment by fblanqui** [comment]
It would be very useful to me to have this right now. As expert on dot, is there any chance @gabrielhdt that you can do it this morning?

**Comment by francoisthire** [comment]
Actually, dune can do it too.

**Comment by gabrielhdt** [comment]
> Actually, dune can do it too.

Good news, we need to do it through dune.

**Comment by gabrielhdt** [comment]
https://github.com/mjambon/dune-deps seems to be the way to go.

**Comment by gabrielhdt** [comment]
Apparently, `dune-deps` does not provide dependencies between files. So we have three options
* @francoisthire has a solution with dune,
* someone finds the right setup and command line to make `ocamldoc -dot` work on the dune project (I tries `dune exec -- ocamldoc -dot src/core/*.ml` without success),
* or we implement something using the output of `ocamldep`.

**Comment by fblanqui** [comment]
Any solution is fine. If @francoisthire has a solution already, that's great.

**Comment by rlepigre** [comment]
I am just wondering: how is such a thing useful to you @fblanqui?

**Comment by francoisthire** [comment]
Sorry, I had `dune-deps` in mind indeed.

**Comment by ejgallego** [comment]
Dune already knows module deps so it would be easy to add a patch for it to generate this information, tho in general module dependencies in OCaml can be quite tricky due to virtual libs, etc... There is a dune tool that allows to query all that Dune knows using GraphQL I think.

On the other hand I would maybe take advantage of `odoc` and build an overview page for beginners `dune build @doc` , API doc + a bit of introduction to the modules could be very helpful.

**Comment by amelieled** [comment]
It's not possible with `ocamldoc -dot` ?

**Comment by gabrielhdt** [comment]
At least not trivially (all the setup is drowned in dune, so one has to explicit paths and dependencies and libraries for `ocamldoc`...)

**Comment by ejgallego** [comment]
dune knows how to talk to `odoc` and `odoc` has already the graph at hand; so maybe submitting a feature request to `odoc` would be the easiest here?

**Comment by amelieled** [comment]
Yes it's too difficult to write the ocamldoc command actually. With odoc, however, I couldn't figure out how to generate the dependency graph.
(The documentation generated by odoc is wonderful)

**Comment by fblanqui** [comment]
Duplicated and partly solved in https://github.com/Deducteam/lambdapi/issues/376
