### ISSUE TITLE
replace Latex commands by Unicode caracters in tools/listings.tex

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#162]
Is there a way to replace in tools/listings.tex Latex commands like \A,\all, etc. by their Unicode counterpart ⇒, ∀, etc. ?

**Comment by rlepigre** [comment]
Yes, but it is not always compatible with conference/journal formats. In general, I don't find this really reliable.
```latex
\usepackage[mathletters]{ucs}
\usepackage[utf8x]{inputenc}
```

**Comment by fblanqui** [comment]
I already tried and it doesn't work:

```

! Package inputenc Error: Unicode char �\expandafter\lst@FillFixed@ (U+A96)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
  ...

l.44 ... Set:TYPE     symbol arrow:Set⇒Set⇒Set
```


Le 14/02/2019 à 10:45, Rodolphe Lepigre a écrit :

**Comment by rlepigre** [comment]
Yeah, that won't work with LaTex. Try compiling with `rubber --pdf document.tex`.

**Comment by fblanqui** [comment]
Doesn't work either for me :-(

11:07 ~/lambdapi-git/tools rubber --pdf listings.tex
compiling listings.tex...
listings.tex:44: Package inputenc Error: Unicode char 
�\expandafter\lst@FillFixed@ (U+A96)
listings.tex:44: leading text: ... Set:TYPE     symbol arrow:Set⇒Set⇒Set
listings.tex:44: Package inputenc Error: Keyboard character used is 
undefined
listings.tex:44: leading text: ... Set:TYPE     symbol arrow:Set⇒Set⇒Set
listings.tex:44: Package inputenc Error: Keyboard character used is 
undefined
listings.tex:44: leading text: ... Set:TYPE     symbol arrow:Set⇒Set⇒Set
listings.tex:44: Package inputenc Error: Unicode char �\lst@EC�\lst@EC� 
(U+282F92)
listings.tex:44: leading text: ... Set:TYPE     symbol arrow:Set⇒Set⇒Set
listings.tex:46: Package inputenc Error: Unicode char 
�\expandafter\lst@FillFixed@ (U+A96)
listings.tex:46: leading text: symbol El:Set⇒TYPE
listings.tex:46: Package inputenc Error: Keyboard character used is 
undefined
listings.tex:46: leading text: symbol El:Set⇒TYPE
listings.tex:46: Package inputenc Error: Keyboard character used is 
undefined
listings.tex:46: leading text: symbol El:Set⇒TYPE
listings.tex:47: Package inputenc Error: Unicode char 
�\lst@FillFixed@\lst@EC� (U+207C7)
listings.tex:47: leading text:   rule El (arrow a b) $\ra$ El a ⇒
listings.tex:47: Package inputenc Error: Keyboard character used is 
undefined
listings.tex:47: leading text:   rule El (arrow a b) $\ra$ El a ⇒
listings.tex:50: Package inputenc Error: Unicode char 
�\lst@FillFixed@\lst@EC� (U+207C7)
listings.tex:50: leading text: ...   symbol 0:$\bN$       symbol s:$\bN$⇒$

Le 14/02/2019 à 11:02, Rodolphe Lepigre a écrit :

**Comment by rlepigre** [comment]
What does `file listings.tex` returns?

**Comment by fblanqui** [comment]
It's UFT8 encoded:

listings.tex: LaTeX 2e document, UTF-8 Unicode text

Le 14/02/2019 à 11:10, Rodolphe Lepigre a écrit :

**Comment by rlepigre** [comment]
Email me the file, I'll have a look.

**Comment by rlepigre** [comment]
It works for me. Use exactly:
```latex
\usepackage[mathletters]{ucs}
\usepackage[utf8x]{inputenc} % "utf8x", not "utf8"
```

**Comment by fblanqui** [comment]
Not for me:

compiling listings.tex...
listings.tex:44: Package utf8x Error: MalformedUTF-8sequence.
listings.tex:44: leading text: ... Set:TYPE     symbol arrow:Set⇒Set⇒Set
listings.tex:44: Package utf8x Error: MalformedUTF-8sequence.
listings.tex:44: leading text: ... Set:TYPE     symbol arrow:Set⇒Set⇒Set
listings.tex:44: Package ucs Error: Unknown Unicode character 65533 = 
U+FFFD,
listings.tex:44: leading text: ... Set:TYPE     symbol arrow:Set⇒Set⇒Set
listings.tex:44: Package utf8x Error: Character135appearedalone.
listings.tex:44: leading text: ... Set:TYPE     symbol arrow:Set⇒Set⇒Set
listings.tex:44: Package utf8x Error: Character146appearedalone.
listings.tex:44: leading text: ... Set:TYPE     symbol arrow:Set⇒Set⇒Set
listings.tex:44: Package utf8x Error: MalformedUTF-8sequence.
listings.tex:44: leading text: ... Set:TYPE     symbol arrow:Set⇒Set⇒Set
listings.tex:44: Package utf8x Error: MalformedUTF-8sequence.
listings.tex:44: leading text: ... Set:TYPE     symbol arrow:Set⇒Set⇒Set
listings.tex:46: Package utf8x Error: MalformedUTF-8sequence.
listings.tex:46: leading text: symbol El:Set⇒TYPE
listings.tex:46: Package utf8x Error: MalformedUTF-8sequence.
listings.tex:46: leading text: symbol El:Set⇒TYPE
listings.tex:46: Package utf8x Error: Character135appearedalone.
listings.tex:46: leading text: symbol El:Set⇒TYPE

I get a PDF with [U+FFFD] à la place de ⇒.


Le 14/02/2019 à 11:38, Rodolphe Lepigre a écrit :

**Comment by fblanqui** [comment]
I found a solution with d4300d7.

Le 14/02/2019 à 13:26, Frédéric Blanqui a écrit :

**Comment by fblanqui** [comment]
It now compiles but the \mathbb symbols are not printed in the right font.

**Comment by rlepigre** [comment]
It is hard to say what happens without seeing the actual file, but from what I understand from the error message, you removed the dollars. Unicode support for maths does not provide unicode support in the text. You still need to write `$⇒$` (instead of `$\Rightarrow$`). But of course, you can always set a replacement rule in the listing configuration.

**Comment by rlepigre** [comment]
Hopefully, the `minted` mode will work a lot better.

**Comment by fblanqui** [comment]
There is no need to put ⇒ between $'s. It's just that ℕ is printed as an italic N.
[listings.pdf](https://github.com/Deducteam/lambdapi/files/2865057/listings.pdf)

**Comment by fblanqui** [comment]
Fixed in https://github.com/Deducteam/lambdapi/commit/d4300d79f392ce367db762034cbc36230d6c471a#diff-b69044afe2869ff86ebf4be89e45716c.
