### ISSUE TITLE
Developer chat

### ISSUE THREAD

**Issue by ejgallego** [Deducteam/lambdapi#163]
We discussed this last time but we didn't reach a conclusion. IMHO having a developer chat is very important so we can discuss real time.

Some options are:
- gitter: lacking features but pretty easy to use,good integration with github, open source
- https://mattermost.com/: Interesting but so far it seems you have to self host,
- zulip, slack, discord: Non-free, quite annoying to use for non-registered people [IMHO to avoid]

Opening a gitter room takes 1 minute so that's my preferred choice.

**Comment by fblanqui** [comment]
Good idea!

Le 14/02/2019 à 16:02, Emilio Jesús Gallego Arias a écrit :

**Comment by rafoo** [comment]
Why not IRC? There is already a fairly active `#deducteam` channel on freenode.

**Comment by fblanqui** [comment]
How does IRC work? What should I install to use it?

**Comment by rlepigre** [comment]
Here at MPI we are using https://mattermost.com and it works really great. However, that is a service that must be self-hosted (as remarked by Emilio). However, this does not seem to be complicated, and the lab could probably provide this service. It would certainly be useful for other people in the lab, not only Deducteam...

**Comment by rafoo** [comment]
> How does IRC work? What should I install to use it?

You connect to an IRC server like `irc.freenode.net` using any IRC client (there are plenty of them, for desktop, mobile, and browser), there is no need to create an account as long as your username is not used by someone else. Once connected to the freenode server, just type `/join #deducteam` to join the channel.

**Comment by rafoo** [comment]
> Here at MPI we are using https://mattermost.com and it works really great. However, that is a service that must be self-hosted (as remarked by Emilio). However, this does not seem to be complicated, and the lab could probably provide this service. It would certainly be useful for other people in the lab, not only Deducteam...

A public Mattermost instance is run by the Framasoft organisation.
The instance: https://framateam.org
The presentation of the instance: https://framablog.org/2016/05/10/framateam-liberez-vos-equipes-des-groupes-facebook-et-de-slack/

**Comment by fblanqui** [comment]
Who's using IRC? I didn't #deducteam.

**Comment by fblanqui** [comment]
J'ai créé un channel privé sur https://framateam.org/dedukti/channels/dedukti-dev . Envoyez-moi un mail avec votre login sur framateam.org pour vous donnez accès.

**Comment by fblanqui** [comment]
Lien d'inscription: https://framateam.org/signup_user_complete/?id=sj4c7zoqji8axdxc5y1nf188mc

**Comment by fblanqui** [comment]
Please stay connected if you want this to be useful!!

**Comment by gabrielhdt** [comment]
The previous solution has been abandoned, but I feel that such a solution would be really helpful in those times. The options are (to update what Emilio said)
* gitter, which looks easy to use, open source and quite well integrated
* matrix, open source, distributed architecture
* slack (I don't understand whether it's open or closed source)

**Comment by fblanqui** [comment]
Good idea to resurrect this issue @gabrielhdt . Any solution is fine for me as long as it integrates well with github and if we can copy and paste source code.

**Comment by francoisthire** [comment]
From the last few months, I use `slack` and it works pretty well. We can copy/past code (without syntax coloring but this not really necessary IMHO). We can create several rooms and also having private conversations. But I understand that `open source` projects come first.

**Comment by ejgallego** [comment]
I still like gitter but I'm usually in minority; for the me strong point is that it is very simple and moreover _it allows me to have all projects in a single window_ . Slack / Zulip are very popular but they require N windows for N projects that's annoying for me.

**Comment by gabrielhdt** [comment]
If I did everything correctly, gitter's available <https://gitter.im/dedukti3/community> (lambdapi was not available)

**Comment by ejgallego** [comment]
The way we set up this in coq is creating a Gitter organization in this case `Deducteam` which inherits from the github one; it was long time ago so I dunno if that will still work.

**Comment by gabrielhdt** [comment]
Ok so I likely messed up that part, I've created a `dedukti3` organization, but its not too late

**Comment by gabrielhdt** [comment]
So indeed, we can set up using an organisation, so the actual gitter link is
https://gitter.im/deducteam-dedukti/lambdapi
(and deducteam was already taken as well...)

**Comment by ejgallego** [comment]
If deducteam was taken it means you already have the organization created, right? Maybe Frédéric created it in the past?

**Comment by gabrielhdt** [comment]
It's strange because the Deducteam community can't be accessed and can't be used, see
https://gitter.im/deducteam
whereas
https://gitter.im/deducteam-dedukti
works

**Comment by ejgallego** [comment]
I guess only the person that created the Gitter `deducteam` organization can access it.

**Comment by fblanqui** [comment]
I do not remember to have done that. Perhaps @francoisthire ?

**Comment by francoisthire** [comment]
Apparently I already started a gitter at some point, so this is possible.
I'll check that at the end of the week.

Le mar. 28 avr. 2020 à 18:23, Frédéric Blanqui <notifications@github.com> a
écrit :

**Comment by fblanqui** [comment]
Currently I cannot access gitter.im. Is it only my computer or is it the same for other people? I get the following error message:
```
La page n’est pas redirigée correctement
Une erreur est survenue pendant une connexion à gitter.im.
    La cause de ce problème peut être la désactivation ou le refus des cookies.
```
Cookies are allowed. Any idea?

**Comment by fblanqui** [comment]
Inria set up a mattermost that we could use as well if needed: https://mattermost.inria.fr/

**Comment by fblanqui** [comment]
Gitter works this morning.

Question: are the messages on Gitter & Matrix public or private?

**Comment by gabrielhdt** [comment]
They are delibarately public, although Matrix can be made private, and you can chat user to user on matrix (conversations can even be encrypted)

**Comment by gabrielhdt** [comment]
The Deducteam community reappeared (I don't know why, @francoisthire have you sorted this out?), so perhaps we should settle things down (i.e. delete duplicates &c.)

**Comment by gabrielhdt** [comment]
So yet another room: <https://gitter.im/Deducteam/lambdapi>

**Comment by ejgallego** [comment]
Thanks @gabrielhdt !
