### ISSUE TITLE
Factorize code common to confluence and termination

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#167]
Factorize code used for calling external tools and put it in extra.ml.

**Comment by rlepigre** [comment]
I'm not sure this code should really be extracted. It is only useful for formats of the confluence/termination competition, and it is in no way generic.

**Comment by fblanqui** [comment]
Parts of it can be factorized. Later we may have to call many other 
tools: ZenonModulo, iProverModulo, ArchSat, etc.

**Comment by rlepigre** [comment]
I know, but we cannot share more that a very few numbers of lines, and that is not worth it from my perspective.

**Comment by fblanqui** [comment]
Done in https://github.com/Deducteam/lambdapi/commit/7e6eff80ae8a10dd59e7433931f5805584ddbbfe.
