### ISSUE TITLE
Handling implicit arguments or _ in RHS?

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#169]
In M_LHS mode, we could replace them by a fresh pattern variable like if it were a P_Wild. The problem is with the M_RHS mode. What to do in this case?... It is like if we allow _ in a RHS. This should generate a fresh meta and we would need to check that SR instantiates all these generated metas. For the moment, we could just fail when they are implicit arguments in RHS, and leave this for future work.

**Comment by GuillaumeGen** [comment]
In #222 , I discovered that non-annotated lambdas are allowed on the rhs of a rule declared by `:=` (a definition). Is there any reason justifying such a heterogeneous behaviour between two ways to declare rules?

**Comment by rlepigre** [comment]
Yes, immediate definitions are handled differently since the definition is a closed term. In particular, there is no subject reduction concern here.

**Comment by fblanqui** [comment]
Well, there is some type-checking if a type is given. So,this is like checking SR, but it is much simpler.

**Comment by fblanqui** [comment]
@francoisthire , this issue is fixed now.

**Comment by francoisthire** [comment]
That's great, thank you.
