### ISSUE TITLE
Use Sphinx for documentation ?

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#173]
This issue is not urgent. I open it to keep it in mind.

Many tools use http://www.sphinx-doc.org/ now for their doc, including Coq. See https://coq.inria.fr/distrib/current/refman/ . It seems to be automatically generated from html and http://docutils.sourceforge.net/rst.html files in https://github.com/coq/doc.

Perhaps we should do the same to get a better rendering of the doc.

**Comment by rlepigre** [comment]
Are you talking about the documentation in the code, or the user documentation?

**Comment by fblanqui** [comment]
The user doc.

Le 23/02/2019 à 11:48, Rodolphe Lepigre a écrit :

**Comment by ejgallego** [comment]
For documentation of `.lp` files itself, I think it would be very feasible to use `odoc` ; there is some talk about adding a Coq backend so if that works it would be pretty easy to have a lp backend.

**Comment by fblanqui** [comment]
Fixed in https://github.com/Deducteam/lambdapi/pull/431
