### ISSUE TITLE
Adding a .merlin file ?

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#174]
Does anyone have a .merlin file that could be shared?

**Comment by fblanqui** [comment]
Is it enough to have:
```
S src
S lp-lsp
S tools
B _build
```
?

**Comment by fblanqui** [comment]
See https://github.com/ocaml/merlin/wiki/project-configuration .

**Comment by rlepigre** [comment]
There are probably more build directories to add. I thought that dune could generate this files, is that the case @ejgallego?

**Comment by ejgallego** [comment]
Merlin files should indeed automatically generated by the check target, don't add any as they will be overwritten on build.

**Comment by ejgallego** [comment]
By the way, it is very likely that the next version of Merlin + dune won't store Merlin info in the build tree, achieving greater hygiene.

**Comment by fblanqui** [comment]
Could you please elaborate? What command should I use exactly?

**Comment by ejgallego** [comment]
dune build @check for example

**Comment by ejgallego** [comment]
Or any other build command

**Comment by rlepigre** [comment]
Or `make`, since it calls dune. Merlin files are created automatically.
