### ISSUE TITLE
More detailed comment required for Handle.require

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#176]

**Comment by fblanqui** [comment]
https://github.com/Deducteam/lambdapi/blob/d1ab8c908da79468c48f2a09984b6d8c2560bbf1/src/handle.ml#L23

**Comment by rlepigre** [comment]
The remaining mechanism is documented quite clearly, I don't see how I can give more explanations (see the bottom of `src/compile.ml` and the documentation of `Parser.require` and `Parser.do_require`).
