### ISSUE TITLE
When required modules are compiled ?

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#178]
https://github.com/Deducteam/lambdapi/blob/d1ab8c908da79468c48f2a09984b6d8c2560bbf1/src/handle.ml#L39

**Comment by ejgallego** [comment]
After quite a bit of thinking and taking into account quite a few existing models I am quite convinced on adopting the following solution @rlepigre @fblanqui:

- resolution of requires is very specific to the build system / plafform; for example a web version won't resolve in the same way than LSP and not in the same way than the command line.
- even so, in some cases you may want different resolution rules for different library scopes, and that is also hard to anticipate / manage
- the bug introduced in https://github.com/Deducteam/lambdapi/commit/ea120ef2c1fe696380d91f7823cb00b0b75216a3 is still here and will hinder development we hope to start next month,
- what I propose is to:
  + split parsing state from command state,
  + parameterize vernac evaluation by a `resolver` class, that resolves modules to loadable files.

**Comment by fblanqui** [comment]
For the record, see beginning of discussion on https://github.com/Deducteam/lambdapi/commit/ea120ef2c1fe696380d91f7823cb00b0b75216a3#commitcomment-33017724.

**Comment by rlepigre** [comment]
Let's continue in #213.
