### ISSUE TITLE
Incorrect error location

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#184]
If you take the file nat.lp of https://github.com/Deducteam/lambdapi/issues/183 which fails on an assert
and call LP on the following file natbool.lp:
```
require open nat bool
```
You get the following error message:
```
18:11 ~/lambdapi-git/lib lp natbool.lp 
Entering directory '/home/blanqui/src/deducteam/lambdapi-git'
Entering directory '/home/blanqui/src/deducteam/lambdapi-git'
[natbool.lp, 1:0-16] Assertion failed.
```
The error message is correct but the location is not.

**Comment by fblanqui** [comment]
By the way, why do we have these "Entering directory ..." messages?

**Comment by fblanqui** [comment]
The "Entering" messages seem to be those of dune because when I call the lambdapi executable directly I do not get them.

**Comment by rlepigre** [comment]
Indeed, "entering" messages come from dune.
