### ISSUE TITLE
Improve syntax coloring in Emacs mode

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#186]
When an identifier contains a keyword, then the keyword part is colored. Is it possible to forbid this behavior?

**Comment by rlepigre** [comment]
Do you have an example? I cannot reproduce. It seems that I do check for word boundaries.

**Comment by fblanqui** [comment]
or_intro_left

**Comment by rlepigre** [comment]
Oh right, this is due to the underscores. I don't know how to fix that quickly, but there is certainly a way. I'm definitely not an emacs specialist.

**Comment by gabrielhdt** [comment]
There is `(modify_syntax_entry ?_ "w")` which will consider the underscore as part of the word, but it has some side effects (such as word  moves &c.)
