### ISSUE TITLE
Grammar: allow ∀x y:N,...

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#197]
That is, remove the need for parentheses.

**Comment by rlepigre** [comment]
We already talked about that: it is not really possible.

None of the languages I know (Coq, Agda, ...) allow that anyway. In fact, [PML](https://github.com/rlepigre/pml) does, but this requires another limitation that you did not like: you need one quantifier by type. So if `x` and `y` are of type `N` and `z` is of type `B` you can write `∀x y:N, ∀z:B, ...` but not `∀x y:N z:B, ...`.

**Comment by rlepigre** [comment]
Moreover, in that case, parentheses will be required most of the time around the type...

**Comment by fblanqui** [comment]
Is it possible to combine both without creating ambiguities? For instance by adding:

term = ... | ∀ ident+ (: term)?, term | λ ident+ (: term)?, term

**Comment by rlepigre** [comment]
No, that would be ambiguous in the case where no type annotation is given. We could maybe add a rule like `"∀" ident+ ":" term, term` but I think it would be confusing. Note that we already allow things like `∀ (x y z : A), B`, I think that this is good enough.

**Comment by rlepigre** [comment]
And again, we would need to use a weird priority for typing the domain in that case.
