### ISSUE TITLE
saniy_check on Mac OS

### ISSUE THREAD

**Issue by elhaddadyacine** [Deducteam/lambdapi#198]
Hi,
After cloning the repo in Mac OS, I got some errors when I do `make sanity_check`.
Does `awk` on Linux have a diffirent behaviour as on Mac OS ? or it's an other problem ?
Those are the first 20 lines of the error messages :
```
In src/basics.ml, line 40 more than 78 characters...
In src/rewrite.ml, line 87 more than 78 characters...
In src/rewrite.ml, line 96 more than 78 characters...
In src/rewrite.ml, line 97 more than 78 characters...
In src/scope.ml, line 273 more than 78 characters...
In src/scope.ml, line 275 more than 78 characters...
In src/solve.ml, line 32 more than 78 characters...
In src/sr.ml, line 49 more than 78 characters...
In src/sr.ml, line 50 more than 78 characters...
In src/sr.ml, line 51 more than 78 characters...
In src/basics.ml, line 5 has trailing spaces...
In src/basics.ml, line 8 has trailing spaces...
In src/basics.ml, line 37 has trailing spaces...
In src/basics.ml, line 38 has trailing spaces...
In src/basics.ml, line 41 has trailing spaces...
In src/basics.ml, line 84 has trailing spaces...
In src/basics.ml, line 104 has trailing spaces...
In src/basics.ml, line 113 has trailing spaces...
In src/basics.ml, line 128 has trailing spaces...
In src/basics.ml, line 130 has trailing spaces...
```

**Comment by rlepigre** [comment]
It is probably a problem with your locales: this setup assumes UTF-8 encoding. Can you try to run the following command?
```bash
LANG=en_US.UTF-8 make sanity_check
```

**Comment by elhaddadyacine** [comment]
I got the same output.

**Comment by elhaddadyacine** [comment]
I solved the problem by installing `gawk` with :
```bash
brew install gawk
```
I don't know if it should be added in the doc or not.

**Comment by rlepigre** [comment]
Yes, you can probably add something to the doc saying that we expect GNU version of commands (not the BSD version), so it may be necessary to install these commands on MacOS. I am guessing that `awk` will not be the only problem on MacOS, in particular the library scripts also probably need GNU commands (although we may rely on the common subset of options that both GNU and BSD version support).

**Comment by fblanqui** [comment]
Why not explicitly calling gawk in the script?

**Comment by rlepigre** [comment]
I don't think that we can assume a `gawk` alias exists on all non-BSD systems. And MacOS users need the GNU tools anyway for mostly everything. Moreover, the two implementations of `awk` have different command line options, so we can't assume compatibility.

**Comment by elhaddadyacine** [comment]
I've installed `lambdapi` on a fresh version of `Mac OS` and `gawk` is the only tool to install in order to run sanity checks.
