### ISSUE TITLE
Using `format6` instead of  `string` as pretty printer separator

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#199]
Currently, the `List.pp` and `Array.pp` have the following signatures:
```
'a pp -> string -> 'a (array | list) pp
```
which prevents from using format tags in the separator (the `string`).

If `string` is changed to `('a, 'b, 'c, 'd, 'e, 'f) format6`, format tags can be used in separators.  The format `"%s%a"` would have to be changed to `"%(fmt %)%a"`.

**Comment by rlepigre** [comment]
Do you have a use case in mind where you want more than just a static `string` here?

Anyway, I don't know if what you ask for is even possible. For instance, how do you feed the necessary arguments for printing each separator? Maybe I'm missing something!

**Comment by gabrielhdt** [comment]
I'd like to print matrices, so having a `"@,"` as separator is handy.  It seems we can leave the polymorphic type.  In fact I have tried it in my pull request, at commit f6d18386e0900c94e8496c4bbffdebb65b408d7e; and it seems that it is backward compatible with the string type.

**Comment by gabrielhdt** [comment]
Ah the arguments, indeed.  I only thought about format tags.  I haven't thought about using `"%d"` or stuff of the kind.

**Comment by rlepigre** [comment]
In that case I suggest that you use a custom printing function for your matrices, since the change you propose may lead to very weird type errors in case someone uses a format that expects arguments (that you cannot hope to distribute over every separator without using some GADT wizardry I fear). We could probably find out what instantiation of the arguments of `format6` corresponds to a constant format string, but I feel that the type would be too confusing for beginners.

**Comment by ejgallego** [comment]
Even the standard [`pp_print_list`](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Format.html#VALpp_print_list) has signature:
```ocaml
val pp_print_list : ?pp_sep:(formatter -> unit -> unit) ->
       (formatter -> 'a -> unit) -> formatter -> 'a list -> unit
```
so the request does have some merit IMHO.

**Comment by rlepigre** [comment]
@ejgallego: that was not what was proposed here, since @gabrielhdt considered using the following signature.
```ocaml
type 'a pp = formatter -> 'a -> unit
val pp : 'a pp -> ('a, 'b, 'c, 'd, 'e, 'f) format6 -> 'a list pp
```

@gabrielhdt: note that you can use `Format.pp_print_list` (I did not know existed).

**Comment by gabrielhdt** [comment]
Hmmm me neither, I'll have a look.  Indeed the name clash with `'a` is a mistake.

**Comment by ejgallego** [comment]
> having a `"@,"` as separator is handy

This is precisely the use case the standard signature allows; I do agree that what @gabrielhdt proposed is a bit too far-fetched.

**Comment by rlepigre** [comment]
@ejgallego: That is of course a very good point, and for that use case @gabrielhdt can use `Format.pp_print_list` instead of `Extra.List.pp`.

**Comment by gabrielhdt** [comment]
And I have; and it works; see 1cafda5a85882cd3df582442fd8dc8d9a7f76587.
