### ISSUE TITLE
Parsing of infix symbols

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#214]
[x + succ y] is currently parsed as [((+ x) succ) y]. Is it possible to change this behavior?

**Comment by fblanqui** [comment]
Other example of problem: [x + (succ y) = succ (x + y)] is currently parsed as [((= (x + (succ y)) succ) (x + y)]...

**Comment by rlepigre** [comment]
Sure, see 97a746b.

**Comment by fblanqui** [comment]
Thanks!
