### ISSUE TITLE
Travis log too long ?

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#219]
Travis logs are > 10,000 lines. Can't we reduce them?

**Comment by rlepigre** [comment]
What logs are you talking about? I can only find logs with around 600 lines.

**Comment by fblanqui** [comment]
https://travis-ci.org/Deducteam/lambdapi/jobs/527740093

**Comment by ejgallego** [comment]
Ups, indeed opamverbose is not a good idea.

**Comment by rlepigre** [comment]
Fixed in 75c95d43987e6cb556dc9103f0c14cbb137dd31c
