### ISSUE TITLE
CLI debug flags not effective

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#221]
Try for instance
```
lambdapi tests/OK/nat.lp --debug re
```
and nothing shows up.

**Comment by fblanqui** [comment]
@rlepigre , isn't because one also needs to use the option --verbose 3 to get any output at all?

**Comment by gabrielhdt** [comment]
With `--verbose 3`, we only get the output related to `--verbose 3`

**Comment by rlepigre** [comment]
Well, `--verbose` has nothing to do with debug output. The verbosity level `n` enables all printing done with `Console.out m` with `m` smaller or equal to `n` (if I'm not mistaken). For you example, I guess not much reduction is done at all: this file mainly contains rule definitions.

However, the fact that there is no output for typing is worrying... I'll have a look.

**Comment by rlepigre** [comment]
I forgot resetting the `log_enabled` flag, which meant that the value of the debug flags would not be taken into account when the console state was restored.
