### ISSUE TITLE
Option --beautify does not sanatize names

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/lambdapi#226]
Here an example where the --beautify output cannot be parsed.

```lambdapi
(; CoC encoding ;)
(; The Higher-order product is missing because it is not useful (yet!) ;)


Sort : Type.

star : Sort. (; ⋆ ;)
box  : Sort. (; □ ;)

(; Compute R(s1,s2) since we are in a functional PTS ;)
def rule : Sort -> Sort -> Sort.
[s] rule _ s --> s.
```

The output is 

```lambdapi
symbol const Sort : TYPE

symbol const star : Sort

symbol const box : Sort

symbol rule : Sort ⇒ Sort ⇒ Sort

rule rule _ &s → &s
```

**Comment by rlepigre** [comment]
Yeah, we should probably try to escape keywords.

**Comment by rlepigre** [comment]
Note that ddeea4770795c38751f122bb7433cd6fa6a23308 introduce the following behavior: if an invalid Lambdapi identifier is encountered with `--beautify` on the legacy syntax then the program fails. To translate, first fix up your source file with a couple of search and replace.
