### ISSUE TITLE
Incorrect error location reporting in emacs

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#230]
With
```
symbol R:TYPE
symbol sin:R⇒R
symbol D:(R⇒R)⇒(R⇒R)
rule D(λx,sin F[x]) → λx:R,x
```
I get `[zo.lp, 4:15] Parse error.` But, in emacs, I get the 3rd line marked with !! and the first closing parenthesis underlined.

**Comment by rlepigre** [comment]
I can't reproduce, the error is correctly reported on my machine. Are you sure you have the last version (try `make install && make install_emacs`).

**Comment by fblanqui** [comment]
Yes, I still have this error... :-( I use emacs 26.1 and eglot 1.4.

**Comment by rlepigre** [comment]
Are you sure that the version of `lp-lsp` you are using is recent? Maybe check the date on the file returned by `which lp-lsp`. Sometime it happens that old binaries are in path before most recent ones (e.g., when opam malfunctions). I frankly don't see where your problem could come from if `lambdapi` gives the right position.

**Comment by rlepigre** [comment]
You could also check the log generated by the LSP server to check that the position reported to `eglot` is correct.

**Comment by fblanqui** [comment]
log-lsp.txt:
```
[send]: {
          "jsonrpc": "2.0",
          "method": "textDocument/publishDiagnostics",
          "params": {
            "uri": "file:///home/blanqui/src/deducteam/lambdapi/zo.lp",
            "diagnostics": [
              {
                "range": {
                  "start": { "line": 3, "character": 23 },
                  "end": { "line": 3, "character": 23 }
                },
                "severity": 1,
                "message": "Parse error."
              }
            ]
          }
        }
```
The line number is wrong.
Perhaps a problem like starting at 0 instead of 1?

**Comment by rlepigre** [comment]
Seems normal form what I understand form the protocol documentation (everything seems to start at 0). And the log is similar on my machine, although Emacs reports correct positions.

**Comment by fblanqui** [comment]
What are your versions of emacs and eglot?

**Comment by rlepigre** [comment]
I have `eglot 1.4` (same as you) and `emacs 26.2` (using `spacemacs`), but I doubt the version of Emacs is important here. Do any of the students have the same problem? @francoisthire could you check?

**Comment by gabrielhdt** [comment]
Emacs 26.2, latest eglot, nothing anormal

**Comment by fblanqui** [comment]
I have emacs 26.1. Could someone try with emacs 26.1? I cannot install emacs 26.2 or 26.3 (latest version) on my machine.

**Comment by gabrielhdt** [comment]
emacs 26.1 (I changed my config from the previous post, obviously), eglot 1.4, and I got the `F` of the 4th line underlined.

**Comment by fblanqui** [comment]
What about the "!!" ?

**Comment by fblanqui** [comment]
![Capture d’écran_2019-10-18_19-55-44](https://user-images.githubusercontent.com/10852505/67116785-7d156300-f1e1-11e9-9319-9ba0ebf9f1fb.png)

**Comment by gabrielhdt** [comment]
I don't have any !! (this may depend on emacs config though), only F underlined in red

**Comment by fblanqui** [comment]
@ejgallego , would you have any explanation/solution for this problem?

**Comment by ejgallego** [comment]
I'll have a look once I'm back.

**Comment by ejgallego** [comment]
I cannot reproduce either; my emacs displays the error correctly. Indeed are you sure you are picking the new `lp-lsp`?

Does the error happen with an empty .emacs file?

**Comment by fblanqui** [comment]
Not possible with an empty .emacs file but with:
```
;; ## added by OPAM user-setup for emacs / base ## 56ab50dc8996d2bb95e7856a6eddb17b ## you can edit, but keep this line
(require 'opam-user-setup "~/.emacs.d/opam-user-setup.el")
;; ## end of OPAM user-setup addition for emacs / base ## keep this line

(require 'package)
(package-initialize)

(load "lambdapi")
```

**Comment by ejgallego** [comment]
Umm, that's super bizarre; it works fine for me :/

**Comment by ejgallego** [comment]
I guess you could try to update emacs, for debian / ubuntu there is this Emacs-snapshot repos https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa

**Comment by rlepigre** [comment]
@fblanqui are you sure you don't have an old version of the server installed somewhere in your path? Maybe you should check using the `which` command.

**Comment by fblanqui** [comment]
Yes.

**Comment by rlepigre** [comment]
@fblanqui does this problem still exist?

**Comment by fblanqui** [comment]
No. Thanks! Problem solved in https://github.com/Deducteam/lambdapi/pull/308.
