### ISSUE TITLE
Meaning of `_`

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#233]
I wanted to test variable binding in decision trees with the following example
```
symbol const A : TYPE
symbol const B : TYPE

symbol f : (A ⇒ B) ⇒ B
symbol g : A ⇒ B

symbol const o : A

rule f (λ x, g _) → g o

assert f (λ x, f (λ t, g x)) ≡ g o
```
I supposed the meaning of `_` in the rule is "match any terms which does not have any free variable in it", i.e. it could have been replaced by a `&X[]`, had the syntax allowed that.

However, when invoked with `--verbose 3`, I see
```
(rules) f (λx, g &#1[x]) → g o
```
so the rule is allowing the variable `x` in the term.
Where is the mistake?

**Comment by fblanqui** [comment]
There is no mistake. The meaning of _ is &F[x] in your example. Perhaps, this should be clarified in the documentation.

**Comment by gabrielhdt** [comment]
And how do I write that I don't want any variable in my matched term?

**Comment by gabrielhdt** [comment]
Ah writing `&X` seem to do the trick, fine.  So the mistake was on my side.

**Comment by fblanqui** [comment]
`rule f (λ x, g &Y) → g o`
