### ISSUE TITLE
Separate metavariable arguments by something different from a comma ?

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#234]
With the following file zo.lp:
```
symbol T:TYPE
symbol a : T
symbol f : ((T⇒T)⇒T)⇒T
rule f (λx,&F[x]) → &F[λx,a]
```
I get the error:
```
[zo.lp, 4:23] Parse error.
```

**Comment by rlepigre** [comment]
That is normal, the comma is used to separate the elements of the environment and for abstractions. Here there is no choice but adding parentheses around the abstraction.

**Comment by fblanqui** [comment]
Ah right. But that's not so nice to use the same token for two different things... Shouldn't we use ';' to separate elements in environments?

**Comment by rlepigre** [comment]
Yes we could do that, but is it worth it though? I don't think we have many lambdas in environments anyway. And one problem I foresee is that we might want to introduce a sequencing operator in the future.

**Comment by fblanqui** [comment]
In terms??

**Comment by rlepigre** [comment]
Yeah, in terms. That might be useful at some point, for example to introduce a `print` instruction (might be useful for debugging): `print("hello, world!"); 42`

**Comment by fblanqui** [comment]
Perhaps although it doesn't look like something very urgent... Anyway, note that this is related to a more general problem: it would be fine if parse error messages were more informative, saying for instance what character or token was expected. Would it be possible?

**Comment by rlepigre** [comment]
It is not so easy with the current parsing technology, however I find that the given position makes it pretty clear that the lambda was not expected.

**Comment by fblanqui** [comment]
Well, it is not clear to me as λx,a is a valid expression... Will your new parser be able to handle that better?

**Comment by rlepigre** [comment]
The new parser will make it easier to report custom error messages, but it will not accept this example any more than the current parser. The best we can hope for here is a message saying that a term at priority level `PAppl` was expected.
