### ISSUE TITLE
Travis store a bad version in the cache

### ISSUE THREAD

**Issue by elhaddadyacine** [Deducteam/lambdapi#242]
Hello,
While trying to fix #171, Travis didn't succeed in the [Deducteam/lambdapi](https://github.com/Deducteam/lambdapi) repository but it worked with my repository [elhaddadyacine/lambdapi ](https://github.com/elhaddadyacine/lambdapi)which is very weird, I fixed the problem by deleting menhir from the installation script and put it back in the next commit which allows Travis to store a new version in the cache.
I am afraid that the problem will occur for future pull requests. Is there a way to tell Travis to not get a specific package from the cache?

**Comment by rlepigre** [comment]
You can delete the cache in Travis when you have such a problem. There is a button for that in the interface, this happens from time to time (I'm not exactly sure why). When the cache is deleted you can then restart the CI.

**Comment by elhaddadyacine** [comment]
Thank you @rlepigre. I didn't know about such a feature in the GUI.
