### ISSUE TITLE
Potential parser ambiguity due to assert and infix equiv

### ISSUE THREAD

**Issue by rlepigre** [Deducteam/lambdapi#254]
See the following FIXME.
https://github.com/Deducteam/lambdapi/blob/b290b24ae8d0d7c1b1f4a391005ddad5e68e03f6/src/parser.ml#L458-L461

**Comment by rlepigre** [comment]
Basically, we need to change the syntax for convertibility assertions. It is currently `assert t ≡ u` (or `assertnot t ≡ u`). There are a few propositions:
 - `assert conv(t, u)` / `assertnot conv(t,u)` (by me),
 - `asserteq t, u` / `assertnoteq t, u` (by @fblanqui).

I don't like the latter because it requires new reserved keywords. Any other ideas?

**Comment by fblanqui** [comment]
But you also add some new token with "conv"...

**Comment by rlepigre** [comment]
> But you also add some new token with "conv"...

Yes but this is not as problematic since they are guarded by the `assert` or `assertnot` keyword. And of course, for uniformity, we should also changed the type-checking assertions.

**Comment by fblanqui** [comment]
Like `assert type(t,u)` I guess.

**Comment by fblanqui** [comment]
Are parentheses really necessary?

**Comment by rlepigre** [comment]
Yes, exactly. And I was even thinking that we could replace `assertnot type(t,a)` by `assert ¬type(t,a)`.

**Comment by fblanqui** [comment]
Why parentheses are necessary is there is "," or ":" between the two terms?

**Comment by rlepigre** [comment]
I'm not sure they are necessary, but I fear the syntax will be hard to read otherwise. An alternative is to keep what we currently have, but lower the priority of terms so that they cannot have infix symbols at the top level. But that means we would often need to write `assert (t) : (a)` which is not great.

**Comment by rlepigre** [comment]
Note that the syntax with the negation symbol only works if we use the kind of syntax I first proposed. (Otherwise we have yet another potential conflict.)

**Comment by fblanqui** [comment]
Another problem: in both cases, the comma would be used for something different from an abstraction, which is already a problem in metavariable arguments...

**Comment by fblanqui** [comment]
So, what do you think of leaving the code as it is and close this issue?

**Comment by rlepigre** [comment]
There is no problem with the comma, it does not produce any ambiguity currently.

The problem with ≡ would anyway only show up if ≡ is defined to be associative (to the left or to the right).

Yes, anyway this is not a big problem. But we can keep the issue open to keep a trace.
