### ISSUE TITLE
Print infix symbols in an infix way

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#260]
Currently, the printing of a symbol depends on its pp_hint. Rewriting and tactics build symbols with pp_hint = Nothing. Hence, in proofs, infix symbols are often not printed in an infix way, or in a mixed way (some occurrences are infix and some others are infix) which is worse. In case of pp_hint = Nothing (or a new pp_hint for generated symbols), we should check whether the symbol is infix or not. This could also be done at the creation time of the symbol, by redefining the function Terms.symb.

**Comment by fblanqui** [comment]
I am wondering: is this pp_hint really a good idea? It seems to me that we could get rid of it and have the printing function depend on the current signature (open modules, aliases, builtins and infix symbols).

**Comment by rlepigre** [comment]
The idea is to print things as they were parsed. The notion of open module, aliases and all does not exist in the internals. This is all handled at scoping time. And it is the same story for implicit arguments. And anyway, through reduction the scope of a term can change so I really don't see how to do things better.

However I know how to print infix symbols correctly, with the least amount of parentheses. The main thing is precisely to extend the printing hints so that they contain the priority and associativity parameters in the infix case. Then we all all the informations we need in the terms, and we only need to do a better work in `src/print.ml`.

**Comment by fblanqui** [comment]
I don't understand what you mean by "the scope of a term can change".

Improving the the printing of infix symbols with less parentheses is the topic of #210 .

The point of this issue is that it happens that, in a goal with several occurrences of an infix, some occurrences of the infix are printed infix, while others are not. This is not consistent.

Instead of relying on inconsistent pp_hint's, I would prefer to print terms in a uniform way by adding in the signature what are the open modules, aliases and infix, and use this information for printing symbols and terms.

**Comment by rlepigre** [comment]
Imagine you have a module `m1` containing
```
open lib.nat
definition add x y = x + y
```
And then you have a module `m2` with
```
eval add lib.nat.zero lib.nat.zero
```
How should you print the result of the evaluation?
Currently we would get `lib.nat.zero + lib.nat.zero` which is not great since `lib.nat` is not open, so you should not get the infix symbol I think.

**Comment by fblanqui** [comment]
This is a matter related to require. Require could import symbols and rules only, and not notations. Only open would import notations as well.

**Comment by rlepigre** [comment]
> This is a matter related to require. Require could import symbols and rules only, and not notations. Only open would import notations as well.

Well, that's exactly the current behavior.

**Comment by fblanqui** [comment]
In your example, you assume that in m2 you have require m1 and that in lib.nat + is a binary infix mapped to an undefined symbol lib.nat.add, right?

Then, in what I propose, we would output `lib.nat.add lib.nat.zero lib.nat.zero`, as there is no notation for lib.nat.add while, in m1, the same term would be printed as `lib.nat.zero + lib.nat.zero`.

**Comment by fblanqui** [comment]
In https://github.com/Deducteam/lambdapi/pull/262#discussion_r345765945, @fblanqui wrote: "I don't understand why you want to be able to print out terms as they have been entered. This is not important to me. What is important is to print terms in a uniform and predictable way."

@rlepigre answered: "Because you want the user to be able to recognize their own terms! For example if there is a notation in scope that the user does not know about or does not want to use it is not a good idea to force them to see it when printing subterms of what the user typed."

Isn't it a user problem related to the structuration of its code? Notations could be defined in separate files the user could open or not.

**Comment by rlepigre** [comment]
Sure, that's exactly the behavior we want. What I described was only the current behavior. And I'm not quite sure how to do the right thing in a clean and simple way.
