### ISSUE TITLE
Comment missing in the code

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#264]
@gabrielhdt , in https://github.com/Deducteam/lambdapi/blob/cfee85433a7207c2716c9b8b6dfe45744a611668/src/tree.ml#L431 there is a List.hd that is not inside a try ... with. Is it the case that the clauses argument is always non empty? If so, please add a comment. Otherwise, thanks to fix this line.

**Comment by rlepigre** [comment]
Actually, it is in a `try ... with Not_found -> ...` block.

**Comment by gabrielhdt** [comment]
Ah indeed that one is a bit tricky: there is always at least one element because empty lines have been filtered out by the `Check_stack` instruction three lines above.  If the `rule_order` flag is set up, then we filter out empty rules

**Comment by fblanqui** [comment]
@rlepigre , List.hd does not raise Not_found. @gabrielhdt thanks to add a comment in the code.

**Comment by rlepigre** [comment]
> @rlepigre , List.hd does not raise Not_found. @gabrielhdt thanks to add a comment in the code.

Oh yes of course! :)

**Comment by fblanqui** [comment]
Fix in ec2ee4e6c05d8fc5ad200b609eaf7eb2724f82e9
