### ISSUE TITLE
doc: sections/structure.md should be updated

### ISSUE THREAD

**Issue by Rehan-MALAK** [Deducteam/lambdapi#267]
structure.md is a nice entry for new contributors but currently mentions  :

1) non existing files :
- src/treecstr.ml
- src/dtree.ml
- src/confluence.ml
- src/termination.ml
- tools/bench.ml
2) non existing directories :
- examples/
- proofs/

and doesn't mention :
- src/tree.ml
- src/tree_graphviz.ml
- src/external.ml
- src/hrs.ml
- src/queries.ml
- src/xtc.ml
- src/why3_tactic.ml

**Comment by fblanqui** [comment]
Right. This has been forgotten when we merged @gabrielhdt 's PR. Gabriel, could you please update this file?

**Comment by fblanqui** [comment]
Non existing files and directories should be removed from structure.md.

**Comment by fblanqui** [comment]
tree: compilation of rewriting rules to decision trees
tree_graphviz: representation of trees as graphviz files
external: call to external provers
hrs: translation of .lp files to .hrs files (format of the confluence competition)
queries: handling of queries to the system (type of a term, flags, assertions, etc.)
xtc: translation of .lp files to .xtc files (format of the termination competition)
why3_tactic.ml: why3 tactic (call to external provers)

**Comment by fblanqui** [comment]
I'm going to do the change myself directly.

**Comment by fblanqui** [comment]
Fixed in 1f6ec98.

**Comment by fblanqui** [comment]
The structure of editors/vscode/ should be refined. @Rehan-MALAK could you please do that?

**Comment by rlepigre** [comment]
Frankly, this section of the doc will never remain in sync. I think we should just remove it. Every module is documented and file names are quite self-explanatory.

**Comment by fblanqui** [comment]
No, I think that it is useful to get an idea of the organization of the project for a newcomer. It's not a big deal to keep it in sync. It's just that we didn't do it in the latest PRs. Next time, we will have to make sure that every PR includes the necessary modifications of the documentation.

**Comment by fblanqui** [comment]
Hello @Rehan-MALAK . Could you please update the content of structures.md to explain in one line what is the purpose of the files in editors/vscode/ so that we can close this issue?
