### ISSUE TITLE
Typable LHS is deemed untypable, breaking SR

### ISSUE THREAD

**Issue by Gaspi** [Deducteam/lambdapi#272]
The following file defines a confluent (orthogonal) and terminating system of 3 first order rewrite rules. Lambdapi currently type checks this file with a simple warning while it clearly breaks subject reduction: a term both is of type `A` and reduces to `A` which is of type `TYPE`.
```
symbol const A : TYPE
symbol const a : A
symbol f : A ⇒ A
symbol g : A ⇒ A

symbol const B : A ⇒ TYPE
symbol const C : A ⇒ TYPE
symbol const consB : ∀ a : A, B (g a)
symbol const consC : ∀ a : A, C (f a)

symbol calc : ∀ a : A, B a ⇒ C a ⇒ A

rule calc &a (consB &b) (consC &c) → A
rule f &x → &x
rule g &x → &x

type    calc a (consB a) (consC a)   // returns A
compute calc a (consB a) (consC a)   // returns A
```

**Comment by fblanqui** [comment]
I think that LP is right. `calc _ (consB _) (consC _)` is not typable without using the rules defining f and g that, in your files, come later. If you put the rules of f and g before, you get:
```
[272.lp, 21:5-38] [TYPE] and [A] are not convertible.
Rule [calc &a (consB &b) (consC &c) → A] does not preserve typing.
```

**Comment by GuillaumeGen** [comment]
I think that having a confluent rewriting system breaking SR and accepted by Dedukti is a bug, since checking SR is the purpose of the program.

**Comment by fblanqui** [comment]
The problem is that we should not conclude that the LHS is not typable as it depends on the rules of f and g.

**Comment by Gaspi** [comment]
Why was this issue closed ? This is not a bug ?
Is it acceptable in lambdapi that a typechecked, confluent and terminating rewrite system breaks subject reduction ?
I thought the whole point of typechecking rules was precisely to guarantee subject reduction...
Does the "Untypable LHS" actually means "Untypable for now but this rule may later break SR" ?

**Comment by francoisthire** [comment]
@Gaspi it has been fixed.
