### ISSUE TITLE
option --version is buggy

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/lambdapi#274]
lambdapi --version prints

```
Lambdapi %%VERSION%%
```

**Comment by rlepigre** [comment]
That's not a bug, that's a feature of Dune. Only releases have their version substituted.

**Comment by francoisthire** [comment]
Well If I do `make install` I expect to have something better than `%%%VERSION%%%`.

**Comment by francoisthire** [comment]
This is very frustrating because right now there is no easy way to know the current version of `lambdapi`.

**Comment by rlepigre** [comment]
I agree, I'm as pissed of as you are by how crappy dune is. I would expect a version number like `devel-<commit hash>`, but apparently that's not possible.

**Comment by rlepigre** [comment]
@francoisthire: I just discovered that if you install using `opam pin` then you get the version number.

**Comment by ejgallego** [comment]
You need to use the `build-info` library https://dune.readthedocs.io/en/stable/dune-libs.html#build-info

**Comment by rlepigre** [comment]
I find the idea of carrying build-system dependent code around in my project kind of worrying...

But anyway, is there any doc available for that library? I can't even find its source code in the middle of the whole dune repository. I'm hoping that it also provides installation paths.

**Comment by ejgallego** [comment]
> I find the idea of carrying build-system dependent code around in my project kind of worrying... But thanks @ejgallego! I did not know that already existed.

The version problem is not an easy problem; in particular it is hard to maintain a proper incremental build. You don't the binary rebuilt on every hash change.

You can use `build-info` or else you can roll your own wrapper to `git describe` too, but then you have to be very careful as to avoid the rebuild problem.

Code for build-info is here BTW https://github.com/ocaml/dune/tree/master/otherlibs/build-info

**Comment by rlepigre** [comment]
OK, do since build-info does not allow to do what I want, I don't think it is worth using it. I'm personally OK with the current situation where releases get a version number, and you also get a version number if you pin the repository. I'd rather not implement the version stuff myself.

As for the other limitations, I think I'm gonna have to hack around.

**Comment by ejgallego** [comment]
> since build-info does not allow to do what I want

What would you like it to do? At least for the original request in this issue, it should work.

**Comment by rlepigre** [comment]
Yeah, it would. But I also want to know where the `lib` directory used for the installation is (i.e., the result of `opam var lib`).

**Comment by ejgallego** [comment]
That's indeed your own https://github.com/ocaml/dune/issues/1534 and https://github.com/ocaml/dune/issues/1185 , IMHO it is better to have a small lookup function that considers different possibilities than to hardcode a path.

For example in Coq we set the data path at configure time, however in the build we can override in several ways so everything works (famous last words)

**Comment by rlepigre** [comment]
Exactly! This problem keeps coming up for me. And yeah, I would like to avoid hackish solutions, and would prefer to have some guarantees. But I guess I'll just rely on some lookup function to discover the configuration.

**Comment by ejgallego** [comment]
Lookup tends to be pretty convenient, IMHO rebuilding the binary on install is quite of a bit hammer to use just for this.
