### ISSUE TITLE
Rules where the LHS is not a pattern

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/lambdapi#275]
The last version of Lambdapi accets the rewrite rule in the example below but it cannot be used. This can be seen when someone prints the decision tree with the option `--write-tree`.

```
symbol const A : TYPE

symbol const a : A

symbol f : (A ⇒ A) ⇒ A

rule f (λ x, &X &Y) → a

symbol x : A ⇒ A

symbol y : A

compute f (λ z, (x y))
```

Hence, is that kind of rewrite rule should be accepted? Is this normal that it does not compute?

**Comment by rlepigre** [comment]
I guess that since we introduced decision trees that kind of rule cannot be used anymore. (We lost the syntactic matching feature that I liked.)

We should now probably reject the patterns that cannot be handled after scoping.

**Comment by francoisthire** [comment]
Once could recover this feature using dkmeta which exists only for Dedukti currently. I have to admit that from my point of view, syntactic pattern matching has no ther purpose that meta programmation so this is not a big loss.

**Comment by fblanqui** [comment]
Not sure that we should accept this kind of rule as this breaks many properties. See counter-example 2.3 in http://doi.org/10.4230/LIPIcs.RTA.2010.17 . Anyway decision trees should be able to handle that. @gabrielhdt should have a look at it to see what's wrong and perhaps fix it.

**Comment by GuillaumeGen** [comment]
To store a discussion I had with @francoisthire, with β, the rule `f (λ x, &A &B) -> &B` makes the conversion trivial, since for all `t` and `u`, `t <- f (λ x, (λ y, 0) t) ->β f (λ x, 0) <-β f (λ x, (λ y, 0) u) -> u`.

**Comment by rlepigre** [comment]
> Anyway decision trees should be able to handle that

No they cannot handle that case because there is no constructor to mach on in the body of the function.

**Comment by fblanqui** [comment]
The generated graph has an edge labeled "λtr". This "tr" is really strange. Why do we get "tr"?

**Comment by fblanqui** [comment]
We need to merge #262 before fixing this issue to avoid conflicts.

**Comment by gabrielhdt** [comment]
For the above comment, see the PR #279.

**Comment by fblanqui** [comment]
Rejecting non-patterns has been added in https://github.com/Deducteam/lambdapi/pull/288 since current decision trees cannot handle non-patterns. We do not plan to change this for the moment. So I close this issue.
