### ISSUE TITLE
Lambdapi vs Dedukti performance

### ISSUE THREAD

**Issue by 01mf02** [Deducteam/lambdapi#276]
Following a suggestion from @francoisthire, I have exported the Isabelle theory `HOL.Inductive` to the LP and DK formats, with the goal to measure performance.
The LP and DK files are [here](http://cl-informatik.uibk.ac.at/users/mfaerber/HOL-Inductive.lp.tar.bz2) and [there](http://cl-informatik.uibk.ac.at/users/mfaerber/HOL-Inductive.dk.tar.bz2). Both formats take roughly the same space, namely 72--73MB.

Running `lambdapi` on the LP files takes 131 seconds and peaks at about 800MB RAM usage.
Running `dkcheck --eta` on the DK file takes 20 seconds and peaks at about 160MB RAM usage.
We thus see that the current Lambdapi takes about 5x as much space and time as Dedukti on this theory. Is this performance to be expected? If not, I hope that my files might contribute to improving Lambdapi performance.

P.S.: It would be a nice experiment to check the DK file with Lambdapi. Unfortunately, this does not seem to be easily possible because the DK parser in Lambdapi does not recognise `{|...|}` syntax.

**Comment by fblanqui** [comment]
@01mf02 feel free to do a PR updating the legacy parser to handle {|...|}. ;-)
Then it would be nice to known the time spent in parsing and the time spent in type-checking.
The LP parser is known to be slower than the DK parser. This could be the reason.

**Comment by rlepigre** [comment]
The performance and memory issues most certainly come from the parser. Try running your files with the `--just-parse` option to see how long it takes to parse them.

**Comment by ejgallego** [comment]
Good instrumentation would be great [and hard] to have; it is often the case for example in Coq that devs have little idea on where time is being spent; OCaml does provide some nifty per-pass stats.

**Comment by fblanqui** [comment]
@01mf02 perhaps the newly available visibility marker `private` (https://github.com/Deducteam/lambdapi/pull/262) could be useful to slightly improve performances (private symbols are not exported). This may be useful for auxiliary symbols/theorems that are used only locally.

**Comment by 01mf02** [comment]
@rlepigre: Your assumption about the parser taking most of the time seem to be correct:

    time lambdapi output.lp --just-parse

takes 130 seconds, compared to 138 seconds with checking.

**Comment by 01mf02** [comment]
@fblanqui: I cannot declare things `private`, all theorems/definitions can be potentially reused in other theories.

**Comment by fblanqui** [comment]
Right. But if this is not the case it could be useful perhaps. But it would require to check that a given symbol is not used outside of its module, something that doesn't seem too difficult to do.

**Comment by rlepigre** [comment]
> Right. But if this is not the case it could be useful perhaps. But it would require to check that a given symbol is not used outside of its module, something that doesn't seem too difficult to do.

Space is cheap, I'm not sure that would be worth the effort.

**Comment by 01mf02** [comment]
@fblanqui: I also considered synchronising the menhir parser with the one in Dedukti, but they seem to have diverged too much for me to do this without additional research. Just to give you some taste:
In the Dedukti DK parser,

~~~
%token <Kernel.Basic.loc*Kernel.Basic.mident> REQUIRE
%token <Kernel.Basic.loc> TYPE
%token <Kernel.Basic.loc> KW_DEF
%token <Kernel.Basic.loc> KW_THM
~~~

corresponds to

~~~
%token <Syntax.p_module_path> REQUIRE
%token TYPE
%token KW_DEF
%token KW_INJ
%token KW_THM
~~~

in the Lambdapi DK parser. The `Kernel` module, however, does not seem to exist in Lambdapi ...
And that's probably just one of many obstacles ...

**Comment by 01mf02** [comment]
> Right. But if this is not the case it could be useful perhaps. But it would require to check that a given symbol is not used outside of its module, something that doesn't seem too difficult to do.

@fblanqui: This would break the extensibility of the export. Suppose you export theories A and B, where B depends on some symbols in A. Suppose you declare all symbols in A not used by B `private`. If you now want to export a theory C that depends on A, C might depend on symbols not used by B, so you now have to adapt the export of A in order to accommodate C.

**Comment by fblanqui** [comment]
This "issue" doesn't seem useful anymore. The dk parser of LP has been updated in #755. Some instrumentation has been added in #750. The performance gap between LP and Dk, or https://github.com/01mf02/kontroli-rs now, still exist and won't be solved soon, especially if we add new features like coercions (#696). The priority of LP is expressiveness currently, not so much efficiency even if we try to keep it reasonable of course. My vision of LP is now as a tool that can generate dk files (I plan to add some dk output to LP soon). It provides a higher-level language than Dk (metavariables, tactics, coercions, etc.) useful for translating the proofs of some systems like PVS.

**Comment by 01mf02** [comment]
I think that your vision of LP as a tool that provides a higher-level language than DK, but which can generate DK files, makes perfect sense.
