### ISSUE TITLE
[meta] Changelog?

### ISSUE THREAD

**Issue by ejgallego** [Deducteam/lambdapi#285]
Something that I've noticed when merging #284 is that we don't require commits to provide a changelog entry or a standardized commit message.

Maybe it is time to start requiring it? I guess a simple entry in CHANGES.md could do for now; Coq uses a more complex system as to avoid conflicts [one file per entry], so OMMV.

**Comment by rlepigre** [comment]
Yes, I think that would be a good idea. It might also be a good idea to ask for authors of pull-request to cleanup their commit history. Currently, we are merging loads of commits that do not make sense on their own, and that even break CI.

**Comment by fblanqui** [comment]
Right. Let's do that.

**Comment by rlepigre** [comment]
@ejgallego do you have any experience using merging bots with GitHub? I feel it would be better to prevent anyone from pushing to `master` directly. And it is probably a good idea to stop harmful merges (that break CI) before they are actually merged.

After a quick search, I could not find the relevant information. But I'm pretty sure it is just a matter of enabling the right branch protection and "application".

**Comment by ejgallego** [comment]
I have experience as a user, for example Mtac developers do use bors to ensure that; it seems to work fine.

We plan to do something like that in Coq however it is a bit more complicated due to the CI tracking a lot of external stuff.

What we do in Coq these days is to use a merge script and it is _mandatory_ to use it https://github.com/coq/coq/blob/master/dev/tools/merge-pr.sh 

See also https://github.com/coq/coq/blob/master/dev/tools/make-changelog.sh

The script could warn about missing changelog, etc... Another common alternative is using a pre-commit hook.

So in principle all PRs do require a changelog entry, unless you annotate the PR description with a `no-changelog-needed` tag or some scheme like that.
