### ISSUE TITLE
Behaviour of --just-parse 

### ISSUE THREAD

**Issue by elhaddadyacine** [Deducteam/lambdapi#286]
Why the option `--just-parse` is not applied for sub-files.
Example:
file.lp
```
require open a
require open b
require open c
```
`lambdapi --just-parse file.lp` outputs:
```
Checked [a.lp]
Checked [b.lp]
Checked [c.lp]
```

**Comment by rlepigre** [comment]
The `--just-parse` option only applies to the main file, the dependencies are compiled due to notations. Of course, if there are `.lpo` files then no checking is done and notations are simply loaded from these object files.

**Comment by fblanqui** [comment]
Hello @elhaddadyacine . Does this answer your question? Can we close this issue?

**Comment by elhaddadyacine** [comment]
@fblanqui Yes !
