### ISSUE TITLE
tests on Mac OS

### ISSUE THREAD

**Issue by elhaddadyacine** [Deducteam/lambdapi#290]
Hello,
make tests does not work on mac OS.
This is a fragment of what `make tests` outputs:
```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
## OK tests ##
KO tests/OK/test.lp
/bin/sh: --verbose: command not found
KO tests/OK/244.lp
/bin/sh: --verbose: command not found
KO tests/OK/245.lp
/bin/sh: --verbose: command not found
KO tests/OK/245b.lp
/bin/sh: --verbose: command not found
KO tests/OK/262_legacy_parsing.dk
/bin/sh: --verbose: command not found
KO tests/OK/262_pair_ex_1.lp
/bin/sh: --verbose: command not found
```

**Comment by rlepigre** [comment]
Yeah, you probably have the BSD version of `readlink`, which does not have the same interface as the GNU version. I think there is a way to install the GNU commands on mac OS.

**Comment by Rehan-MALAK** [comment]
I have seen several projects including in the Makefile a "portable version" or readlink.

**Comment by rlepigre** [comment]
Yeah, actually we can make it portable by just removing it.

**Comment by elhaddadyacine** [comment]
The purpose is to setup CI for mac OS.

**Comment by fblanqui** [comment]
Fixed in https://github.com/Deducteam/lambdapi/commit/ceba0a2383112aab85ec694be68ed4803316a27a.
