### ISSUE TITLE
Wrong warning

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#292]
With
```
symbol R : TYPE
constant symbol zero : R
symbol d2_1 : (R ⇒ R ⇒ R) ⇒ (R ⇒ R ⇒ R)
rule d2_1 (λ_ y,&F[y]) → λ_ _,zero
```
we get:
```
[tmp/wildcard.lp, 4:16-21] &F could be replaced by a wildcard.
```

**Comment by rlepigre** [comment]
The warning is not wrong since `&F` is unused. Rather, the syntax is wrong because it does not allow `&_[y]`. Note that my initial proposal for the syntax did allow for a wildcard precise for that purpose. And if I remember @fblanqui insisted that this would never be useful. :) Is it now?

**Comment by fblanqui** [comment]
I think that the warning is wrong because, for `d2_1(λxy,t)` to be reducible, we must check that x does not occur in `t`.

**Comment by fblanqui** [comment]
`rule d2_1 (λx y,&F[y]) → λ_ _,zero` outputs no warning although the two declarations should be equivalent.

**Comment by fblanqui** [comment]
The problem seems to come from the fact we check that that &F is applied to as many arguments as the number of variables in env:
https://github.com/Deducteam/lambdapi/blob/ceba0a2383112aab85ec694be68ed4803316a27a/src/scope.ml#L311
But in https://github.com/Deducteam/lambdapi/blob/ceba0a2383112aab85ec694be68ed4803316a27a/src/scope.ml#L241
and https://github.com/Deducteam/lambdapi/blob/ceba0a2383112aab85ec694be68ed4803316a27a/src/scope.ml#L246
we add no variable in env, and I think that it is important for metavariables to not get too many dependencies.

**Comment by rlepigre** [comment]
> I think that the warning is wrong because, for d2_1(λxy,t) to be reducible, we must check that x does not occur in t.

Sure, that's exactly the meaning of `&_[y]` (versus a simple wildcard). However, there is no need to name the pattern variable since it is not used.

**Comment by rlepigre** [comment]
> The problem seems to come from the fact we check that &F is applied to as many arguments as the number of variables in env:

Indeed, if an unused variable is applied to all variables in scope then it can be replaced by a wildcard since a wildcard automatically gets all the variables in its environment. That is not a very natural semantics for me, and I would rather force the user to give the list of variables that can appear in wildcards (if any). In any case, that only happens in higher-order patterns.

**Comment by fblanqui** [comment]
I understand your notation &_ and agree that we should add it. But this doesn't fix the problem.

It is important for _ to catch all named variables as this is used in implicit arguments.

A solution would be to change the type env from `(string * (tvar * tbox)) list` to `(string option * (tvar * tbox)) list` and filter out None's when necessary.

**Comment by rlepigre** [comment]
Actually, it pretty much fixes the problem I think (and maybe we should rather use `_[...]` as a notation, to match the `_`).

In rules declarations implicit arguments must be explicitly given (right?), so they should not be involved here.

**Comment by fblanqui** [comment]
No way we use _[...]. It's too heavy.

There may be implicit arguments in rules, hopefully. But this needs to be improved: https://github.com/Deducteam/lambdapi/issues/259.

**Comment by fblanqui** [comment]
Not sure it really solves the problem because why don't we get a warning for `rule d2_1 (λx y,&F[y]) → λ_ _,zero`?

**Comment by rlepigre** [comment]
> No way we use _[...]. It's too heavy.

That's only useful in higher-order patterns, most rules will still only use `_`.

**Comment by rlepigre** [comment]
> Not sure it really solves the problem because why don't we get a warning for `rule d2_1 (λx y,&F[y]) → λ_ _,zero`?

Here we don't get a warning because our current interpretation of wildcard is a pattern that uses all the patterns in scope. Since both `x` and `y` are in scope, it would not be equivalent to write `d2_1 (λx y,_) → λ_ _,zero`.

**Comment by fblanqui** [comment]
I was talking about the use of _ in terms (not only in rules).

**Comment by fblanqui** [comment]
I understand why we do not get a warning but it would be strange not to have one if you allow &_.

**Comment by rlepigre** [comment]
Well, we are only talking about rules LHS here. In terms wildcards have a different meaning and they should probably not have an attached environment. In fact maybe we can keep `_` to mean all variables in scope are included in the environment, and also have `&_[...]` to mean "an unnamed pattern with the given environment". And for a LHS, `_` would be equivalent to `&_[...]` with a full environment.

**Comment by rlepigre** [comment]
In fact, in all the rules you have given we should always have the warning that `&F` is unused. (And could be replaced by a wildcard.) The environment thingy is a different issue here, but solving the first issue will probably lead to a simpler solution for the second issue.

**Comment by fblanqui** [comment]
I am not in favor of adding yet another special notation that would be very rarely used because LHS with more than 2 nested bound variables will be rare.

**Comment by rlepigre** [comment]
What do you mean by "another special notation"? As I see it, `&_[x,y]` is just the unnamed version of `&F[x,y]`, so there is nothing to learn here.

**Comment by fblanqui** [comment]
I believed that you wanted to introduce the notation "..." to replace 
the list of variables in scope. Isn't it the case?

Le 27/11/2019 à 09:33, Rodolphe Lepigre a écrit :

**Comment by rlepigre** [comment]
Of course not, what would be the interest of doing that against using just `_`?
