### ISSUE TITLE
Correctness of subject-reduction with higher-order pattern-matching ?

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#294]
As remarked in https://github.com/Deducteam/lambdapi/pull/293/files?file-filters%5B%5D=.bnf&file-filters%5B%5D=.lp&file-filters%5B%5D=.ml#r351439534, the following rules are equivalent:
```
rule f (λx y, &M[y]) → a
rule f (λ_ y, &M[y]) → a
```
But, in scoping, in the first rule, y is given a type &A[x] that may depend on x, while in the second rule y is given a type &A that cannot depend on x. This has no impact on rewriting because, during matching, type annotations in abstractions are ignored. However, the subject-reduction algorithm translates pattern variables into meta variables in order to compute the constraints under which the LHS is typable. Therefore, in the second rule, it may not capture all the possible instantiations of the type of y, which is incorrect.

**Comment by fblanqui** [comment]
```
symbol A:TYPE;
symbol a:A;
symbol b:A;
symbol T:A → A → TYPE;

symbol f:Π u:A, (Π v:A, T u v → A) → A;
rule f _ (λ x y, $_.[y]) ↪ a;
flag "print_domains" on;
print f;
rule f _ (λ _ y, $_.[y]) ↪ b;
print f;

symbol g:Π u:A, (Π v:A, T u v → A) → A;
rule g _ (λ _ y, $_.[y]) ↪ b;
compute g a (λ x:A, λ y:T a x, a); // in nf

rule T a _ ↪ A;
compute g a (λ x:A, λ y:T a x, a); // reduces to b
```
generates the following output:
```
17:26 ~/src/lambdapi (master) lp tmp/294.lp 
Loading "/home/blanqui/src/lambdapi/tmp/294.lp" ...
flag print_domains on
symbol f : Π u: A, (Π v: A, T u v → A) → A;
rule f $0 (λ x: $1, λ y: $2.[x], $3.[y]) ↪ a;

[/home/blanqui/src/lambdapi/tmp/294.lp:9:17-23]
Pattern [$_.[y]] could be replaced by [_].
symbol f : Π u: A, (Π v: A, T u v → A) → A;
rule f $0 (λ x: $1, λ y: $2.[x], $3.[y]) ↪ a
with f $0 (λ _: $1, λ y: $2, $3.[y]) ↪ b;

[/home/blanqui/src/lambdapi/tmp/294.lp:13:17-23]
Pattern [$_.[y]] could be replaced by [_].
g a (λ x: A, λ _: T a x, a)
b
```
We can see that the two rules are indeed different, and that `g a (λ x: A, λ _: T a x, a)` does not reduce to `b` if the domain of the second λ depends on `x`. So it looks like matching applies to abstraction domains too. @gabrielhdt is it right?

**Comment by gabrielhdt** [comment]
Indeed, domains of abstraction are taken into account when matching, it can be seen approximately there
https://github.com/Deducteam/lambdapi/blob/29750e1acb43107237c299b70298a096225461af/src/core/tree.ml#L590
where the domain is added into the pattern matrix

**Comment by fblanqui** [comment]
Ok, then this issue is not an issue anymore and we can close it.

**Comment by gabrielhdt** [comment]
One may want this feature to appear in the documentation.

**Comment by fblanqui** [comment]
Could you please make a PR?
