### ISSUE TITLE
Support OCaml 4.08 and 4.09

### ISSUE THREAD

**Issue by Rehan-MALAK** [Deducteam/lambdapi#300]
related to https://github.com/rlepigre/ocaml-earley/issues/2

**Comment by craff** [comment]
Hello moving deducti to pacomb would be a solution...

Le 12 décembre 2019 06:28:52 GMT-10:00, Rehan MALAK <notifications@github.com> a écrit :
>related to https://github.com/rlepigre/ocaml-earley/issues/2
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Deducteam/lambdapi/issues/300

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by rlepigre** [comment]
> Hello moving deducti to pacomb would be a solution...

I'm planning to do that, but my time is limited...

**Comment by craff** [comment]
Quelq'un d'autres peut retrousser ses manches.... La je bosse sur mon parseur du français et la grammaire de phox, c'est sur qu'avec ppx c'est moyen, par exemple il faut des parenthèses ou begin autour des actions, mais c'est pas si mal en pratique.

Le 12 décembre 2019 07:26:04 GMT-10:00, Rodolphe Lepigre <notifications@github.com> a écrit :
>> Hello moving deducti to pacomb would be a solution...
>
>I'm planning to do that, but my time is limited...
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Deducteam/lambdapi/issues/300#issuecomment-565104194

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by rlepigre** [comment]
> Quelq'un d'autres peut retrousser ses manches.... La je bosse sur mon parseur du français et la grammaire de phox, c'est sur qu'avec ppx c'est moyen, par exemple il faut des parenthèses ou begin autour des actions, mais c'est pas si mal en pratique.

Ouais, c'est le truc qui me gène un peu. Surtout que j'ai vraiment entendu beaucoup de mal des PPX. C'est impossible à maintenir comme il faut... Donc j'ai du mal à croire qu'on va arriver à supporter le code du parser pendant longtemps facilement. (Regarde Earley, on se retrouve bloqué parce que j'ai pas le temps de faire les changements nécessaires, même si j'ai déjà fait un gros bout.)

**Comment by craff** [comment]
C'est différent, le code ne comprends que la grammaire ppx, c'est à dire une fonction transformant l'ast de caml en fait. C'est donc beaucoup plus petit à maintenir. De plus, si on compile les grammaires, en plus d'un gain de vitesse, on a du code pur ocaml en attendant d'adapter le ppx.

Mais c'est sur que ppx c'est pas sérieux. Mais un truc comme earley-ocaml ne tient la route que si ca devient officiel. Je ferais bien d'ailleurs un pacomb-ocaml en rapprochant les interfaces de earley et pacomb... Mais est-ce vraiment utile?

Le 12 décembre 2019 08:34:41 GMT-10:00, Rodolphe Lepigre <notifications@github.com> a écrit :
>> Quelq'un d'autres peut retrousser ses manches.... La je bosse sur mon
>parseur du français et la grammaire de phox, c'est sur qu'avec ppx
>c'est moyen, par exemple il faut des parenthèses ou begin autour des
>actions, mais c'est pas si mal en pratique.>
>>
>Ouais, c'est le truc qui me gène un peu. Surtout que j'ai vraiment
>entendu beaucoup de mal des PPX. C'est impossible à maintenir comme il
>faut... Donc j'ai du mal à croire qu'on va arriver à supporter le code
>du parser pendant longtemps facilement. (Regarde Earley, on se retrouve
>bloqué parce que j'ai pas le temps de faire les changements
>nécessaires, même si j'ai déjà fait un gros bout.)>
>>
>-- >
>You are receiving this because you commented.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/Deducteam/lambdapi/issues/300#issuecomment-565129583

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by rlepigre** [comment]
> Mais c'est sur que ppx c'est pas sérieux. Mais un truc comme earley-ocaml ne tient la route que si ca devient officiel. Je ferais bien d'ailleurs un pacomb-ocaml en rapprochant les interfaces de earley et pacomb... Mais est-ce vraiment utile?

Je ne sais pas, mais ce qui serait utile c'est de faire que `pa_ocaml` fonctionne déjà. On a plein de projets qui se basent dessus, et ce serait bien que ça continue à marcher. Surtout qu'avec les modifications que j'ai fait dans la branche [cleanup_for_4_08](https://github.com/rlepigre/ocaml-earley/tree/cleanup_for_4_08) le code devrait être bien plus facile à maintenir. Le problème c'est que l'interface avec les `compiler-libs` n'est pas tout à fait assez générale (des types ont été déplacés il me semble pour `4.08`).

**Comment by craff** [comment]
Salut,

J'ai pushé une branche pacomb pour lambdapi ... le make tests passe.
4.07.1 et 4.09 marche. Le seul test que j'ai fait c'est le make tests.

On perd un petit peu en performance, sans doute le module Input UTF8 et la
gestion des positions en utilisant le type pos de Pacomb qui n'est pas lazy.
Pas exclu que ce soit une connerie (levée d'ambiguïté tardive dans le parsing).

Il faudrait tester les fichiers qui posent de vrai pb de parsing.

Il faut la dernière github de pacomb.

A+
Christophe

**Comment by craff** [comment]
On 19-12-13 02:06:17, Rodolphe Lepigre wrote:
>     Mais c'est sur que ppx c'est pas sérieux. Mais un truc comme earley-ocaml
>     ne tient la route que si ca devient officiel. Je ferais bien d'ailleurs un
>     pacomb-ocaml en rapprochant les interfaces de earley et pacomb... Mais
>     est-ce vraiment utile?
>
> Je ne sais pas, mais ce qui serait utile c'est de faire que pa_ocaml fonctionne
> déjà. On a plein de projets qui se basent dessus, et ce serait bien que ça
> continue à marcher. Surtout qu'avec les modifications que j'ai fait dans la
> branche cleanup_for_4_08 le code devrait être bien plus facile à maintenir. Le
> problème c'est que l'interface avec les compiler-libs n'est pas tout à fait
> assez générale (des types ont été déplacés il me semble pour 4.08).

Salut, Franchement, le passge de lambdapi à pacomb m'a pris 4h et comptant
un bug complètement idiot sur une des fonctions que j'ai ajoutée à pacomb
pour le rapprocher d'earley.

Franchement, on doit pouvoir faire passer pa_ocaml à pacomb:

1°) on extrait des fichiers bootstrap la liste des fonctions earley vraiment
 utile et on crée un module earley compatible

2°) on test la compilation

3°) on passe la génération sur la librairie Pacomb à la place de Earley.

Mais est-ce vraiment utile .... Par exemple la grammaire de lambdapi
est finalement pas si mal comme ça.

A+
Christophe

**Comment by craff** [comment]
On 19-12-14 15:21:36, Christophe Raffalli wrote:
>
> Salut,
>
> J'ai pushé une branche pacomb pour lambdapi ... le make tests passe.
> 4.07.1 et 4.09 marche. Le seul test que j'ai fait c'est le make tests.
>
> On perd un petit peu en performance, sans doute le module Input UTF8 et la
> gestion des positions en utilisant le type pos de Pacomb qui n'est pas lazy.
> Pas exclu que ce soit une connerie (levée d'ambiguïté tardive dans le parsing).
>
> Il faudrait tester les fichiers qui posent de vrai pb de parsing.
>
> Il faut la dernière github de pacomb.

Bon make et make tests passe pour pacomb et lambdapi en 4.04.1 et en 4.09.0,
je suppose que ça passe entre les deux.

> A+
> Christophe

**Comment by rlepigre** [comment]
> Bon make et make tests passe pour pacomb et lambdapi en 4.04.1 et en 4.09.0, je suppose que ça passe entre les deux.

Cool, merci! Par contre ça compile pas comme il manque un module `Blank` ( probablement un oubli de `git add`?).

Pour `earley` je pense que ce serait bien de finir le travail de nettoyage que j'ai commencé pour faire fonctionner 4.08 et 4.09. Je ne sais pas si c'est utile de faire l'adaptation pour `pacomb` mais on utilise encore `earley` pour `patoline`, et là on peut pas juste passer à `pacomb`. Si on le fait pas, `patoline` est définitivement mort. Je pense que faire fonctionner `earley` avec les nouvelles versions de Caml est pas si compliqué si on utilise la bibliothèque "migrate parse tree".

En gros, l'idée est de laisser tomber les compiler libs et de simplement compiler vers l'AST de la version la plus récente de Caml (donc 4.09). Pour ça, on pourrait partir de ma branche pour profiter du nettoyage que j'ai fait. Une fois que c'est fait, on peut ensuite utiliser la version de l'AST donnée par "migrate parse tree", et utiliser les fonctions pour descendre ou monter de version jusqu'à la version de Caml de l'utilisateur. Tu en penses quoi?

**Comment by craff** [comment]
Salut,

On 19-12-15 01:56:45, Rodolphe Lepigre wrote:
>     Bon make et make tests passe pour pacomb et lambdapi en 4.04.1 et en
>     4.09.0, je suppose que ça passe entre les deux.
>
> Cool, merci! Par contre ça compile pas comme il manque un module Blank (
> probablement un oubli de git add?).

C'est un module de pacomb que j'ai ajouté, car il était dan earley et je trouve
ça plus propre.  Tu as la dernière version de Pacomb ?

>
> Pour earley je pense que ce serait bien de finir le travail de nettoyage que
> j'ai commencé pour faire fonctionner 4.08 et 4.09. Je ne sais pas si c'est
> utile de faire l'adaptation pour pacomb mais on utilise encore earley pour
> patoline, et là on peut pas juste passer à pacomb. Si on le fait pas, patoline
> est définitivement mort. Je pense que faire fonctionner earley avec les
> nouvelles versions de Caml est pas si compliqué si on utilise la bibliothèque
> "migrate parse tree".
>
> En gros, l'idée est de laisser tomber les compiler libs et de simplement
> compiler vers l'AST de la version la plus récente de Caml (donc 4.09). Pour ça,
> on pourrait partir de ma branche pour profiter du nettoyage que j'ai fait. Une
> fois que c'est fait, on peut ensuite utiliser la version de l'AST donnée par
> "migrate parse tree", et utiliser les fonctions pour descendre ou monter de
> version jusqu'à la version de Caml de l'utilisateur. Tu en penses quoi?
>

On a tous les deux pas beaucoup de temps. Donc je pense que si on est que 2
comme contributeur de earley, la solution ppx me semble mieux que réécrire un
parser pour tout OCaml. Après si un petit groupe d'utilisateur d'OCaml trouve
que quand même earley c'est bien mieux que ppx et même que le défun camlp4,
alors ça vaut vraiment le coup.

Et Earley a quand même un problème de perf dans certains cas. C'est juste une
grosse contante. Donc même si on garde earley, il faudrait tester pacomb, car je
pense que le moteur est mieux ... On va voir avec les gros exemples de dedukti.

Et effectivement, ça serait bien quand même de garder earley pour patoline ...

A+
Christophe

**Comment by fblanqui** [comment]
Salut Christophe!

Le 16/12/2019 à 20:36, Christophe Raffalli a écrit :
>
> > Cool, merci! Par contre ça compile pas comme il manque un module Blank (
> > probablement un oubli de git add?).
>
> C'est un module de pacomb que j'ai ajouté, car il était dan earley et 
> je trouve
> ça plus propre. Tu as la dernière version de Pacomb ?
>
Moi, ça compile.:-)

**Comment by craff** [comment]
> >
> Moi, ça compile.:-)

Salut,

Et tu as testé sur un gros exemple qui parsait trop lentement ?  Sur le make
tests, pacomb est un tout petit peu plus lent qu'earley, car comme c'est pleins
de petits fichiers, on a le cout de la compilation de la grammaire.

**Comment by rlepigre** [comment]
J'ai testé, c'est lent sur des gros exemples (cf mon mail).

**Comment by craff** [comment]
Coucou,

Je suis maintenant à 12s pour dk_hol_groups.lp avec pacomb
contre 30s avec earley. Comme earley en en général avec un *10
par rapport à ocamlyacc, ça veut dire que pacomb arrive à un *3.

Les deux pbs étaient:

- calcul des positions utf8: j'ai rajouté du lazy dans le module input
de pacomb

- il manque la factorisation gauche dans pacomb. En factorisant à la
main, ça fini un peu le boulot.

1°) Je vais essayer d'ajouter la factorisation gauche dans pacomb.
ça ne doit pas poser trop de problème, sauf l'égalité ...

2°) Et je vais réfléchir pour les positions unicode dans Input.
Je pense que l'on peut gagner un peu plus en utilisant
que des bytes pour input, et une conversion bytes => utf8
complètement indépendante du record input, sauf peut être pour un
cache.

Petite question: je pense abandonner complètement les positions en caractère
unicode ou bytes de puis le début du fichier et ne garder que les couples
(ligne,numéro de colonne). Vous en pensez quoi ?

**Comment by fblanqui** [comment]
j'ai testé sur make dklib, make focalide et make holide. je n'ai pas 
regardé le temps mais cela me semblait plus lent en effet.

**Comment by craff** [comment]
On 19-12-16 23:54:01, Frédéric Blanqui wrote:
> j'ai testé sur make dklib, make focalide et make holide. je n'ai pas
> regardé le temps mais cela me semblait plus lent en effet.
>

Bon j'ai revu input de Pacomb avec des positions lazy.

J'ai mis un peu de factorisation gauche (je vais encore bosser là dessus).

Il faut puller pacomb et lambdapi/pacomb.

Maintenant avec le --just-parse, lambdapi/pacomb est 3 fois plus rapide
environ que lambdapi/earley ...

Il faut faire plus de test biensur.

**Comment by rlepigre** [comment]
Après quelque tests, je ne vois pas d'amélioration significative. C'est même un peu plus lent pour le "make iprover". Aussi, j'ai un "assert failure" quand je teste sur un gros fichier (https://gofile.io/?c=4BfSvx).

**Comment by craff** [comment]
On 19-12-17 04:21:15, Rodolphe Lepigre wrote:
> Après quelque tests, je ne vois pas d'amélioration significative. C'est même un
> peu plus lent pour le "make iprover". Aussi, j'ai un "assert failure" quand je
> teste sur un gros fichier (https://gofile.io/?c=4BfSvx).

Tu as testé les toutes dernière versions que j'ai pushé ?
Quand je teste sur le plus gros fichier que tu m'as envoyé avec --just-parse
je passe bien de plus de 30s à 13s.

L'assert failure, quel message ? Une trace ? Le fichier est trop gros pour
que je le ramène en Edge ;-)

**Comment by rlepigre** [comment]
J'ai pas testé toutes les versions, mais en tout cas la dernière (à l'instant) oui. Voilà le message d'erreur.
```
Fatal error: exception File "lib/utf8.ml", line 6581, characters 37-43: Assertion failed
```

**Comment by craff** [comment]
On 19-12-17 14:16:37, Rodolphe Lepigre wrote:
> J'ai pas testé toutes les versions, mais en tout cas la dernière (à l'instant)
> oui. Voilà le message d'erreur.
>
> Fatal error: exception File "lib/utf8.ml", line 6581, characters 37-43: Assertion failed

Merci, UTF8.prev supposait que l'on part d'un charractère unicode ... Et pour
les lignes trop longues, il faut revenir en arrière à partir d'une position
arbitraire.  Avec ce que j'ai fait, ça devrait marcher. Il m'a fallu m'y
reprendre à deux fois car si le buffer termine par un caractère utf8 sur 4
caractères, plus les 3 premiers byte d'une autre utf8 sur 4 caractères, prev
doit retourner de 7 caractère en arrière.

Dis moi si ça corrige le pb

Si tu as un exemple entre 1 et 5Mo où pacomb n'est pas 2 à 3 fois plus rapide
qu'earley, je veux bien ...

Un peu plus de chose sur earley/pacomb. Ptet pas bien ici ?

Remarque: il faut que earley et pacomb utilise le même input. J'étais reparti du
dernier input d'earley, mais en essayant de faire un truc correct pour les
graphemes (c'est effectivement imporant, si on normalise), j'ai redivergé.
De toutes façon, je ne suis pas vraiment content de ce qu'on a.

Un truc qui coute cher, c'est le nombre de copie des segments du fichier:

- 1 copie cachée dans le buffer du input channel

- 1 seconde copie avec Stdlib.input (et on scanne deux fois pour faire cette copie)

- une copie si remain est non vide (c'est à dire on était dans le cas ci-dessous pour le
  buffer précédent).

- Si à ce stade le buffer correspond à un buffer qui ne finit pas par un saut de
  ligne, encore une copie pour juste ajuster la fin sur un grapheme. On copie
  systématiquement car hors newline, il faut le caractère suivant pour savoir si
  la fin du buffer est ok.

Si on a de très longue ligne, toutes les morceaux de lignes à part la première
et la dernière sont donc copiés 4 fois. Si les lignes sont courtes, tous est
copié deux fois.

Bref c'est vraiment pas top!!!

Solution que j'envisage une interface functionnelle pour utf8 et les preprocesseur
et on arrête complètement de copier (sauf la copie interne du input_buffer).

ça vaut le cout de bosser là dessus, car c'est à la fois pour earley et pacomb.

A+

**Comment by rlepigre** [comment]
Sur le gros fichier pour lequel j'ai donné un lien plus haut (https://gofile.io/?c=4BfSvx) Pacomb est plus lent que Earley (342 contre 348 secondes pour parser).

**Comment by craff** [comment]
Salut,

OK, dès que j'ai de l'internet, je ramène le fichier. C'est un peu bizarre quand même.
Si tu as un exemple plus petit qui fait pareil je veux bien, car plus de 5mn, ça doit
être gros.

A+
Christophe

PS: pacomb est dans opam, mais donc plus la bonne version pour les branches pacomb
de pml et lambdapi. Quand ça se stabilise, je fais une release 1.1 ou 2.0, on verra.
Pas de pub avant ça.

**Comment by craff** [comment]
Salut,

J'ai pu télécharger le gros fichier. Il semble que là ça soit un problème de mémoire.
Tu vois une raison de produire l'AST des commandes, au lieu de les executer.
Je sais même faire un ";" ou ";;" pour lancer l'évaluation immédiatement. Le problème est
d'évaluer l'action avant de parser les blancs. Donc ça donnerait un mode interactif à lambdapi.

Je pense que l'AST avec les clôtures de position, c'est gros ... earley a le
même problème en un peu moins grave. C'est un pb d'OCaml, quand j'avais joué
avec SAT, sur les très grosses formules, le problème est qu'en C les gens on des
représentations des arbres de syntaxe ultra compacte, en 64 bits, il y a avait
un facteur 20 ou 30. Sans aller jusque là, ça serait cool de trouver un moyen de
faire des AST compactes en OCaml.

Pour les positions, je crois que l'on devrait juste stocker le "byte_pos" et faire une fonction
pour calculer le reste. On peut garder un cache donnant un début de ligne tous les 1Mo pour
pas rescanner tout le fichier. Tu en penses quoi ? Il me semble que tu suggérais un truc du genre.
On peut même faire que ça soit transparant avec Input, et que finalement ça ressemble beaucoup
aux positions lazy.


A+
Christophe

**Comment by craff** [comment]
Salut,

J'ai pas mal avancé avec pacomb, encore gagné un peu de temps.  J'ai aussi
trouvé un bug que je n'ai pas encore corrigé, donc le dernier pacomb risque de
casser le make tests de lambdapi jusqu'à ce que je corrige. En utilisant plus et
mieux le test avec les charsets, j'ai vu que mon charset est toujours faux dans
certains cas ... C'est pourtant pas si compliqué.


Bon sinon, je propose de garder earley, et donc je vais regarder quand j'aurai un
peu de temps. Un gros pb est le manque de doc ou d'exemples avec ppxlib. J'ai
unicolib qui ne compile plus car je ne fais pas comme il faut pour faire un programme
qui produit une ast OCaml (donc pas juste un ppx). Mais en fait je ne trouve pas d'exemples ...
Donc dur dur. Si tu as des pointeurs.

Sinon, tu peux me dire brièvement ce que tu as fait dans les modifications
récentes de earley ?

à par ça, je pense que l'on doit soit

- remplacer le moteur earley par pacomb dès que pacomb sera stabilisé,
- soit garder les deux moteurs, ce qui oblige à faire converger les interfaces ...
Ce n'est pas si dur.

Si on ne garde pas les deux, il suffit que pacomb propose juste ce qu'il y a dans
les fichiers du bootstrap, et on y est presque. Il y a juste un pb avec le test des blanks,
car pacomb propose un "no_blank_after" ou "no_blank_before" mais pas juste un test sur
les blanks. ça pose un pb car c'est un terminal qui accepte le vide et ce n'est pas
autorisé dans pacomb et ça empêche la factorisation du vide. C'est pas vraiment un gros pb.

A+
Christophe

**Comment by fblanqui** [comment]
Le 21/12/2019 à 06:29, Christophe Raffalli a écrit :
> Tu vois une raison de produire l'AST des commandes, au lieu de les 
> executer.

Oui, ça serait vraiment bien de faire cela! cf. 
https://github.com/Deducteam/lambdapi/issues/261

**Comment by fblanqui** [comment]
Salut @craff. Merci pour ton travail sur LP! Peux-tu nous dire où tu en es un peu?

@01mf02 Je t'invite à tester les fichiers Isabelle avec la branche pacomb de Christophe pour nous dire dans quelle mesure cela améliore les performances.

**Comment by 01mf02** [comment]
Je ne peux pas compiler la branche pacomb de lambdapi :

~~~
$ make
File "src/pos.ml", line 10, characters 18-38:
Error: Unbound value Pos.interval_of_spos
~~~

J'utilise OCaml 4.05.0 avec les paquets suivants :

~~~
$ opam install odoc menhir yojson cmdliner bindlib.5.0.0 timed.1.0 pacomb ppx_inline_test why3.1.2.0
[NOTE] Package why3 is already installed (current version is 1.2.0).
[NOTE] Package ppx_inline_test is already installed (current version is v0.13.0).
[NOTE] Package pacomb is already installed (current version is 1.0).
[NOTE] Package timed is already installed (current version is 1.0).
[NOTE] Package bindlib is already installed (current version is 5.0.0).
[NOTE] Package cmdliner is already installed (current version is 1.0.4).
[NOTE] Package yojson is already installed (current version is 1.7.0).
[NOTE] Package menhir is already installed (current version is 20190924).
[NOTE] Package odoc is already installed (current version is 1.4.2).
~~~

**Comment by rlepigre** [comment]
Je pense qu'il faut installer la dernière version de `pacomb`, à partir du dépôt.

**Comment by Rehan-MALAK** [comment]
Est-ce que vous avez un couple de commit lambdapi + pacomb où LSP fonctionne ? Et est-ce que dune fabrique un .merlin correct pour parser.ml (compatible ppx pacomb) de votre côté ?

**Comment by Rehan-MALAK** [comment]
Le couple
Lambdapi : 2163715 
Pacomb : craff/pacomb@aea0c76
compile bien pour 4.09.0 et avec lp-lsp qui fonctionne comme avant. (mais pas 7efef463)
Je vais me baser sur ça en attendant que les choses se stabilisent.
Merci

**Comment by craff** [comment]
Hello,

Le 8 janvier 2020 15:05:19 GMT-10:00, Rehan MALAK <notifications@github.com> a écrit :
>Le couple>
>Lambdapi : 2163715 >
>Pacomb : craff/pacomb@aea0c76>
>compile bien pour 4.09.0 et avec lp-lsp qui fonctionne comme avant.
>(mais pas 7efef463)>

Pour moi ça marche, chaque commende est évaluée quand la suivante est parsée. Je viens de tester. Impossible de faire mieux car des cmds peuvent être prefix d'autres cmds. On peut introduire un ;; comme en ocaml...

**Comment by Rehan-MALAK** [comment]
Je parlais de LSP.

**Comment by Rehan-MALAK** [comment]
Par exemple avec :
66e6f38
craff/pacomb@db83446
je peux parser/typechecker
```
constant symbol nat : TYPE
constant symbol n0 : nat
```
mais emacs/eglot/flymake donne ``Unbound symbol or variable [nat]`` en ligne 2.
et cette erreur semble arriver avec  7efef46

**Comment by Rehan-MALAK** [comment]
Voici le diff entre log-lsp.txt pour le code lambdapi précédent
2163715 (cas qui marche)
```json
            "diagnostics": [
              {
                "range": {
                  "start": { "line": 0, "character": 0 },
                  "end": { "line": 0, "character": 11 }
                },
                "severity": 4,
                "message": "OK"
              },
              {
                "range": {
                  "start": { "line": 1, "character": 0 },
                  "end": { "line": 1, "character": 9 }
                },
                "severity": 4,
                "message": "OK"
              }
            ]
```
7efef46 (cas qui marche pas)
```json
            "diagnostics": [
              {
                "range": {
                  "start": { "line": 1, "character": 5 },
                  "end": { "line": 1, "character": 8 }
                },
                "severity": 1,
                "message": "Unbound symbol or variable [nat]."
              },
              {
                "range": {
                  "start": { "line": 0, "character": 0 },
                  "end": { "line": 0, "character": 11 }
                },
                "severity": 4,
                "message": "OK"
              }
            ]
```

**Comment by fblanqui** [comment]
Hi @craff , @rlepigre and @Rehan-MALAK . So, what's the current situation wrt parsers and ocaml versions. Could you please summarize it?

**Comment by craff** [comment]
On 20-03-20 10:11:28, Frédéric Blanqui wrote:
> Hi @craff , @rlepigre and @Rehan-MALAK . So, what's the current situation wrt
> parsers and ocaml versions. Could you please summarize it?
>

Hi,

I just merged master in pacomb to keep the branch up to date.
The lambdapi/pacomb branch requires the latest git version of pacomb.
Before releasing pacomb, I need to test more the new strategy for position
(reparsing).

I am waiting for someone to evaluate the lambdapi/pacomb branch and
comment. Expecially testing speed on large file. The large file I have do not
type-check, so I do not know the ratio parsing/checking time

Moving for real grammar extension instead of the current infix table should
increase performance a bit more. To see the difference you can compare
examples/calc_ext.ml examples/calc_ext2.ml in pacomb repository. Note: syntax of
extension (examples/test_ext2.txt) in calc_ext2.ml is a bit cumbersome because
it lacks lambda-calculus to write action.

**Comment by fblanqui** [comment]
LP is now working with every version of ocaml >= 4.07.1.
