### ISSUE TITLE
OCaml dependencies

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/lambdapi#305]
Using OCaml in version 4.05.1, I have an error while trying to compile the project

```
      ocamlc lp-lsp/.lp_lsp_lib.objs/lp_lsp_lib__Lsp_base.{cmi,cmti} (exit 2)
(cd _build/default && /home/fthire/.opam/4.05.0/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I lp-lsp/.lp_lsp_lib.objs -I lp-lsp/.lp_lsp_lib.objs/.private -I /home/fthire/.opam/4.05.0/lib/base -I /home/fthire/.opam/4.05.0/lib/base/caml -I /home/fthire/.opam/4.05.0/lib/base/shadow_stdlib -I /home/fthire/.opam/4.05.0/lib/bindlib -I /home/fthire/.opam/4.05.0/lib/biniou -I /home/fthire/.opam/4.05.0/lib/bytes -I /home/fthire/.opam/4.05.0/lib/cmdliner -I /home/fthire/.opam/4.05.0/lib/earley/core -I /home/fthire/.opam/4.05.0/lib/easy-format -I /home/fthire/.opam/4.05.0/lib/menhirLib -I /home/fthire/.opam/4.05.0/lib/num -I /home/fthire/.opam/4.05.0/lib/ppx_inline_test/config -I /home/fthire/.opam/4.05.0/lib/ppx_inline_test/runtime-lib -I /home/fthire/.opam/4.05.0/lib/result -I /home/fthire/.opam/4.05.0/lib/sexplib0 -I /home/fthire/.opam/4.05.0/lib/timed -I /home/fthire/.opam/4.05.0/lib/why3 -I /home/fthire/.opam/4.05.0/lib/yojson -I src/.core.objs -I src/pure/.pure.objs -no-alias-deps -opaque -open Lp_lsp_lib -o lp-lsp/.lp_lsp_lib.objs/lp_lsp_lib__Lsp_base.cmi -c -intf lp-lsp/lsp_base.mli)
File "lp-lsp/lsp_base.mli", line 18, characters 26-29:
Error: Unbound type constructor J.t
GNUmakefile:11: recipe for target 'bin' failed
make: *** [bin] Error 1
fthire@elitebook:~/Git/lambdapi$ make clean
fthire@elitebook:~/Git/lambdapi$ make
      ocamlc lp-lsp/.lp_lsp_lib.objs/lp_lsp_lib__Lsp_base.{cmi,cmti} (exit 2)
(cd _build/default && /home/fthire/.opam/4.05.0/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I lp-lsp/.lp_lsp_lib.objs -I lp-lsp/.lp_lsp_lib.objs/.private -I /home/fthire/.opam/4.05.0/lib/base -I /home/fthire/.opam/4.05.0/lib/base/caml -I /home/fthire/.opam/4.05.0/lib/base/shadow_stdlib -I /home/fthire/.opam/4.05.0/lib/bindlib -I /home/fthire/.opam/4.05.0/lib/biniou -I /home/fthire/.opam/4.05.0/lib/bytes -I /home/fthire/.opam/4.05.0/lib/cmdliner -I /home/fthire/.opam/4.05.0/lib/earley/core -I /home/fthire/.opam/4.05.0/lib/easy-format -I /home/fthire/.opam/4.05.0/lib/menhirLib -I /home/fthire/.opam/4.05.0/lib/num -I /home/fthire/.opam/4.05.0/lib/ppx_inline_test/config -I /home/fthire/.opam/4.05.0/lib/ppx_inline_test/runtime-lib -I /home/fthire/.opam/4.05.0/lib/result -I /home/fthire/.opam/4.05.0/lib/sexplib0 -I /home/fthire/.opam/4.05.0/lib/timed -I /home/fthire/.opam/4.05.0/lib/why3 -I /home/fthire/.opam/4.05.0/lib/yojson -I src/.core.objs -I src/pure/.pure.objs -no-alias-deps -opaque -open Lp_lsp_lib -o lp-lsp/.lp_lsp_lib.objs/lp_lsp_lib__Lsp_base.cmi -c -intf lp-lsp/lsp_base.mli)
File "lp-lsp/lsp_base.mli", line 18, characters 26-29:
Error: Unbound type constructor J.t
```

Trying to install lambdapi-lsp from opam, I have an error that my version of OCaml should be `>= 4.06'. However, one of the dependencies of the project (earley, timed or bindlib I forget) require a version of OCaml `< 4.07`. Hence, for compilation, only the version 4.06 is supported?

**Comment by Rehan-MALAK** [comment]
earley that needs <= 4.07
but may be replaced by pacomb in future versions
cf #300
cf https://github.com/Rehan-MALAK/lambdapi/tree/model

**Comment by francoisthire** [comment]
But the dependencies and especially the constraints in README.md  seem not up to date.

**Comment by Rehan-MALAK** [comment]
true...
I hope decisions w.r.t #300 will be taken soon

**Comment by francoisthire** [comment]
Sure, but in the meantime, it would be nice to commit the actual constraints and dependencies.

**Comment by Rehan-MALAK** [comment]
It seems opam version has not been updated for ages.. The opam lambdapi doesn't even accept ''*.lp'' extensions !
I will have a look at the ''opam publish'' and ''dune publish'' documentation

**Comment by fblanqui** [comment]
@gabrielhdt:
I note that lambdapi.opam requires ocaml >= 4.05.0 but .travis.yml only tests ocaml >= 4.07.1.
Shouldn't we fix lambdapi.opam and close this issue?

**Comment by gabrielhdt** [comment]
Ah indeed, I can take care of this. In fact the current parser needs ocaml >= 4.07

**Comment by ejgallego** [comment]
You can have dune generate the opam files, it works pretty well modulo a bug in dune subst with unicode files which is fixed in dune master.

**Comment by gabrielhdt** [comment]
It seems to be a good idea, @ejgallego, and furthermore, dune announces that using `.opam` will become deprecated. I tried something on <https://github.com/Deducteam/lambdapi/compare/master...gabrielhdt:auto-opam>, but a consequence of using `dune` is that we cannot install vim files automatically, because for the moment, vim files are not installed in a prefix handled by dune.

**Comment by fblanqui** [comment]
But can't you add some 'make install_vim' to do this?

**Comment by gabrielhdt** [comment]
Well not with dune only, this maneuver was possible because of the `lambdapi.opam`. But are vim files still maintained?

**Comment by fblanqui** [comment]
Not really. But vim users could still install the necessary vim files by themselves.

**Comment by gabrielhdt** [comment]
All right, so it looks like we agree that we can drop the automatic installation of vim files?

**Comment by fblanqui** [comment]
Yes. Who's using vim in the team? The Emacs and VSCode interfaces are much more advanced.
But I do not fully understand why it's a problem with vim and not for emacs. Can't we install the vim files somewhere where we can with dune and let vim users to add a link from their ~/.vim file?

**Comment by gabrielhdt** [comment]
No one is using vim in the team, and It may be better to provide nothing than providing outdated files. I'll see if I can update them so that they're at least not wrong.

Yes, your last suggestion can be performed indeed. In fact it makes sense, let's settle it that way.

**Comment by fblanqui** [comment]
Ok. But we should also mention in the doc that the use of vim is deprecated.

**Comment by ejgallego** [comment]
We can write a dune rule to install vim files.

**Comment by gabrielhdt** [comment]
If I'm not mistaken, dune can't install files anywhere, can it? I have implemented such an installation in the pull request aforementioned, is it what you had in mind, @ejgallego?

**Comment by ejgallego** [comment]
It more of an opam constraint I think, in theory builds are sandboxes so all files have to go under the corresponding prefix dir, but `ocaml-user-setup` does install some vi stuff in opam , then updated vimrc to add that directory, maybe we could do something similar?

**Comment by gabrielhdt** [comment]
It seems to me that `ocaml-user-setup` is quite different, because its purpose is to edit user space files. Therefore, it's the program itself that edits user files, not the installation process. At least it's what I understand.

**Comment by ejgallego** [comment]
It adds the right path to emacs / vim so files under opam are understood.

**Comment by gabrielhdt** [comment]
I think to achieve the same result, we should use a phony target, but I don't know if that's possible with dune.

**Comment by ejgallego** [comment]
Yup, I think you can do that with aliases, but maybe indeed not worth it, suggest the user to modify vimrc or use user-setup that should already do that for tuareg etc...
