### ISSUE TITLE
assertion failed with implicit arguments

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#306]
See the following code,
```
symbol Sort : TYPE
symbol Univ : Sort ⇒ TYPE
symbol Term {s : Sort} : Univ s ⇒ TYPE

symbol Rule : Sort ⇒ Sort ⇒ Sort
symbol prod {s1 s2 : Sort} (A : Univ s1) :
  (@Term s1 A ⇒ Univ s2) ⇒ Univ (Rule s1 s2)

rule @Term _ (@prod &s1 &s2 &A &B) → ∀ x : Term &A, Term (&B x) // KO
rule Term _ (@prod &s1 &s2 &A &B) → ∀ x : Term &A, Term (&B x) // OK
```
the `KO` tagged line fails with
```
Uncaught exception [File "src/basics.ml", line 113, characters 36-42: Assertion failed]
```
what is the behaviour of implicit arguments in rewriting rules? I would expect the second line to fail because the first argument is considered implicit.

On the other hand, I have rewriting rules for projection which use implicit arguments behaves correctly, such as
```
symbol fst {T : Univ Type} {U : @Term Type T ⇒ Univ Prop}:
  @Term Type (psub T U) ⇒ @Term Type T
rule @fst &T &U (@pair &T &U &M _) → &M // OK
rule fst &T &U (@pair &T &U &M _) → &M // KO
```

**Comment by fblanqui** [comment]
This seems related to #303 .

On the other hand, I don't understand why you do not get an error when you write `Term _ (@prod &s1 &s2 &A &B)`, or at least a warning. Since the first argument of Term is declared as implicit, _ is added at scoping time. Then, `Term _ (@prod &s1 &s2 &A &B)` should not be typable since Term is applied to too many arguments. Of course, if a LHS is not typable, then SR is guaranteed trivially, but there should a warning.

**Comment by fblanqui** [comment]
Thanks to check the result of `type Term _ (@prod _ _ _ _)`.

**Comment by gabrielhdt** [comment]
What do you expect from this? I only obtain
`Cannot solve [Univ (Rule ?3 ?5)] = [Univ ?1].`

**Comment by gabrielhdt** [comment]
It seems that the problem is that
`symbol prod {s1 s2: Sort} ...` is parsed as having only `s1` as implicit argument.

It works with `prod {s1: Sort} {s2: Sort}...` though

**Comment by rlepigre** [comment]
I investigated a bit, and everything seems to work as expected on the side of implicit arguments there. The behavior of implicit arguments is the same in a LHS as in any other form of term. So when you write `Term t` what you really get is `Term _ t` and when you write `@Term _  t` you get `Term _ _ t` (which is not well-typed).

**Comment by rlepigre** [comment]
The problem really comes from SR checking.

**Comment by rlepigre** [comment]
For some reason, `TEnv` nodes can end up in the type of a metavariable inside a RHS (even though every `TEnv` is supposed to be replaced by a metavariable).

**Comment by gabrielhdt** [comment]
Yes, indeed, the problem really was that implicits arguments can't be grouped `{s1 s2: ...}`.

Ah, your last remarks concerns #303. The lifting function does not operate on the type of metavariables, so they are not substituted. I have tried to lift in meta types and meta val in https://github.com/gabrielhdt/lambdapi/tree/iss303, but it raises other issues.

**Comment by rlepigre** [comment]
> Yes, indeed, the problem really was that implicits arguments can't be grouped `{s1 s2: ...}`.

I don't see any indication of that. How can I reproduce this behaviour?

> @rlepigre your last remarks concerns #303. The lifting function does not operate on the type of metavariables, so they are not substituted. I have tried to lift in meta types and meta val in https://github.com/gabrielhdt/lambdapi/tree/iss303, but it raises other issues.

I tried that kind of thing as well, but the problem remains the same: there are still `TEnv` nodes around. I don't think that is the issue. Anyway, what you are doing in your branch is wrong: the value field should absolutely contain the original pointer (it always contain `None` anyway at this point since the metavariable is not instantiated).

I'm gonna investigate more later.

**Comment by gabrielhdt** [comment]
> I'm gonna investigate more later.

OK

I misread your first message, what do you mean by, "you really get"?

I would expect to have to use, in a LHS, `Term {_} t` equivalently to `Term t`, and I expect `Term _ t` to not type check since `Term _` should unfold to `Term _ _` with the first `_` being the implicit argument.

> How can I reproduce this behaviour?

I am working on it.

**Comment by rlepigre** [comment]
> I misread your first message, what do you mean by, "you really get"?

Yeah that is not really clear. What I meant is that the elaborated term you get is of the given form, where underscores are fresh metavariables.

**Comment by gabrielhdt** [comment]
For the implicitness, see
```
constant symbol U: TYPE

constant symbol cA: U
constant symbol cB: U

injective symbol T: U ⇒ TYPE

constant symbol a: T cA
constant symbol b: T cB

symbol f {t u: U} (x: T t) (y: T u): TYPE
symbol g {t: U} {u: U} (x: T t) (y: T u): TYPE

type f {cA} cB a b
type f cB a b

type g {cA} {cB} a b
type g a b
```
where `f` has only the `{t: U}` declared as implicit whereas `g` correctly has its two arguments set as implicit.

> What I meant is ...

So the term we get with `@Term _ t` should be `Term _ t`, right?

**Comment by rlepigre** [comment]
I still don't understand what you mean. Implicit arguments are only syntactic sugar. After scoping, they do not play any role. However, `Print.pp` does not print implicit arguments by default (and it never prints the `@`). To do that, you can use `set flag "print_implicits" on` at the top of your file.

**Comment by gabrielhdt** [comment]
Yes, so I expect that `Term t` is unfolded as `Term _ t`, and
```
rule Term (@prod &s1 &s2 &A &B) ...
```
unfolded to
```
rule Term _ (@prod ...) ...
```

and
```
rule @Term _ (@prod ...)
```
unfolded to
```
rule Term _ (@prod ...)
```

**Comment by rlepigre** [comment]
Isn't that the case?

**Comment by gabrielhdt** [comment]
Since
```
rule Term _ (@prod &s1 &s2 &A &B) → ∀ x : Term &A, Term (&B x) // OK
```
type checks, the implicit arguments seem to be automatically "explicited" in lhs, otherwise it should be
```
rule Term (@prod...)
```
unfolded to `rule Term _ (@prod ...)` that should type check, shouldn't it?

**Comment by rlepigre** [comment]
From what I remember this rule is accepted with some warning saying that its LHS is not typable. Isn't that the case? Anyway, use the debugging flags and have a look at the actual term with printing of implicits enabled. That is the only way to actually know what is happening.

**Comment by gabrielhdt** [comment]
Aah you're right about the "non typable LHS" warning, I wasn't looking at the terminal output since I was in emacs, a warning should be displayed in emacs as well I guess.

So the implicitness behaves correctly, sorry for the noise. I think we can close this issue since the main one is #303.
