### ISSUE TITLE
Type checking a single file

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/lambdapi#316]
When I use lambdapi to type check a single file called test with the following command:
```
lambdapi check test.dk
```

`lambdapi` returns an error and says I need to have a `lambdapi.pkg` file. And there is little documentation (using `--help`) that helps me to write such file.

I would be in favor to avoid such configuration file is we are interested to type check a single file. Is this doable?

**Comment by fblanqui** [comment]
Hi François. Which version of LP do you use? The one installed with opam using 'opam pin add ...`?

**Comment by francoisthire** [comment]
Yes. The version given by `lambdapi`:

```
2f660fe
```

**Comment by rlepigre** [comment]
Everything is documented [here](https://github.com/Deducteam/lambdapi/blob/master/doc/sections/module.md). Note that you can use the `--map-dir` option to map a directory under the library root. If you are in the same folder as your file you can do something like:
```
lambdapi check --map-dir local:. test.dk
```
This leads your file to be compiled under the module path `local.test`.

> I would be in favor to avoid such configuration file is we are interested to type check a single file. Is this doable?

It should be possible, but I'm not sure if I like that. Let's see what everyone thinks. However, I was thinking of providing a `lambdapi init` command to create an empty development package and a generated `lambdapi.pkg`.

**Comment by francoisthire** [comment]
Ok, if there are solutions that already exist, maybe it would be interesting to have a better error message? The link you mention is not really easy to find and the error message does not mention the option `--map-dir`. For me, it is acceptable as long as the error message give me enough information to solve the issue.
