### ISSUE TITLE
Strange error message

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#319]
```
16:03 ~/src/SKonverto/examples/eprover_trace ((HEAD détachée sur yacine/master)) lambdapi check copy.lp 
Ill-formed argument to "--map": empty module path member.
```

**Comment by rlepigre** [comment]
Are you using a package file? If yes, can you dump the content here?

**Comment by fblanqui** [comment]
No, I have no package file. And there is no '--map' option.

**Comment by fblanqui** [comment]
You can test by yourself by cloning https://github.com/elhaddadyacine/SKonverto .

**Comment by rlepigre** [comment]
I get the expected error:
```
[/home/rodolphe/dev/SKonverto/examples/eprover_trace/copy.lp] cannot be mapped under the library root.
Consider adding a package file [lambdapi.pkg] under your source tree, or use the [--map-dir] option.
```
I'm quite sure there is a package file in some parent directory on your machine. It does not have to be in the repository, it could be anywhere on the branch to the file system root.

**Comment by fblanqui** [comment]
1) Why are you checking files in directory parents??
2) This does not explain the error message. There is no --map option.

**Comment by rlepigre** [comment]
1. Because that is the whole point of package files! They define the root module path of a package, and then the rest of the module path is constructed according to the directory structure. If you load a file, there is no way to know how deep it appears in the tree, so you have to go up the tree and hope to find a package file.
2. I know, but I want to see what the package file that is used contains so that I can fix the problem in the right way.

**Comment by fblanqui** [comment]
The package file was:
```
package_name = ex
root_path = .
```

**Comment by fblanqui** [comment]
I can compile @elhaddadyacine 's files by doing `lambdapi check --lib-root . copy.lp`. But, now, I get no feedback from emacs anymore because, I guess, emacs doesn't know that we need to use the option `--lib-root .`.

**Comment by rlepigre** [comment]
Emacs is going to need a package file.

The root path is not valid in your package file: it should be a module path.

**Comment by fblanqui** [comment]
I get the same error as previously if I put nothing before ":.":
```
17:02 ~/src/SKonverto/examples/eprover_trace ((HEAD détachée sur yacine/master)) lambdapi check --map-dir :. copy.lp 
Ill-formed argument to "--map": empty module path member.
```

**Comment by rlepigre** [comment]
In fact, you should not use the `--lib-root` option here, this is not what it should be used for. And it should not be used at all once Lambdapi is installed. The only option that should then be used is `--map-dir`, or better, use a package file.

**Comment by rlepigre** [comment]
The empty string is not a valid module path.

**Comment by fblanqui** [comment]
Perhaps. But why LP talks about a non-existing option? And why not simply saying that the modulo path, found in lambdapi.pkg or in --map-dir, is not valid?

**Comment by fblanqui** [comment]
What you suggest doesn't seem to work:
```
17:11 ~/src/SKonverto/examples/eprover_trace ((HEAD détachée sur yacine/master)) cat lambdapi.pkg 
package_name = example
root_path = example
17:12 ~/src/SKonverto/examples/eprover_trace ((HEAD détachée sur yacine/master)) lambdapi check copy.lp 
[/home/blanqui/src/SKonverto/examples/eprover_trace/copy.lp, 1:0-20] Error when loading module [lemmas.c_0_4].
File [/home/blanqui/.opam/4.07.1/lib/lambdapi/lib_root/lemmas/c_0_4.{lp|dk}] not found.
```

**Comment by rlepigre** [comment]
The reason why you get an error talking about `--map-dir` even when it is not used is because I am using the same function to parse module paths given on the command line and in package files. I will fix that when I have a moment.

Of course that cannot work with what you did! There is no module named `lemmas.c_0_4`. Only a module named `example.lemmas.c_0_4` now. The package file defines the prefix of the module path (here, just `example`), and the path to the file (starting from the directory containing the package file) defined the rest.

**Comment by fblanqui** [comment]
So, what should I do exactly to get Yacine's files compile and Emacs to work with them??

**Comment by rlepigre** [comment]
You need to modify the files so that they use the correct module qualifications.

**Comment by fblanqui** [comment]
Do you mean that, in copy.lp, he should write `require example.lemmas.c_0_4` instead of `require lemmas.c_0_4`?

**Comment by fblanqui** [comment]
Ok, I better understand now. But the doc needs to be revised and, above all, a "Hello World!" example must be given.

@elhaddadyacine here is how I finally compiled copy.lp:

In the same directory as copy.lp, add a file lambdapi.pkg with these 2 lines:
```
package_name = eprover_trace_example
root_path = example
```

The package_name is the name you would give to this development if you wanted to add it, say, on opam. It is not important for compilation.

The root_path on the other hand is important for compilation. This is the prefix you have to use for all the files of your development. For instance, in lemmas/c_0_4.lp, you have to write `require example.eprover_trace` instead of `require eprover_trace`. In fact, I suggest to use an alias and write `require example.eprover_trace as trace`, and use trace everywhere instead of example.eprover_trace.

The same applies to logic files that are local. However, if logic files were installed somewhere using opam for instance, with its own root_path = ekstrakto, then you would refer to zen.lp by ekstrakto.zen.
