### ISSUE TITLE
Parsing problem with set declared and set infix

### ISSUE THREAD

**Issue by amelieled** [Deducteam/lambdapi#333]
You can consider this code: 

```
require open tests.preuves_Ledein.notation
//require open tests.preuves_Ledein.Logic
                                  
// //////////////////////// Entiers naturels
                  
symbol plus : N ⇒ N ⇒ N
rule plus 0      &m → &m
 and plus (S &v) &m → S (plus &v &m)

set declared "+"
set infix right 6 "+" ≔ plus
                                  
// //////////////////////// Logique sur les booléens

require open tests.preuves_Ledein.Logic

// ...

// //////////////////////// Retour sur les entiers naturels

theorem plus_0_n : ∀n, π (eq {nat} (O+n) n)
proof
  assume n
  refine eq_refl n
qed
```
I can't understand why eglot/emacs tells me my proofs are right, but when I go through the terminal, `lambdapi check . . . ` tells me parser error (on symbol "+"). 
A priori, everything comes in the order that I transform `O+n` into `plus O n`.

The problem seems to come from the line: `require open tests.preuves_Ledein.Logic`. 
If I write it at the beginning of the file, I get another message :
Checked [notation.lp]
Checked [Logic.lp]
merging ( term_<...> * )         at  `(O+n) ` in `theorem plus_0_n : ∀n, π (eq {nat} (O+n) n) `
merging term_<...> * <tree>  at  `(O+n) ` in `theorem plus_0_n : ∀n, π (eq {nat} (O+n) n) `
Checked [ my file]

So the file is checked, but the other messages are OK ?

**Comment by fblanqui** [comment]
Just some remarks not related to your problem:
- you don't need to write set declared "+". set declared is necessary only for declaring non-ascii characters to use as identifiers.
- in your code, please write your comments in English.

**Comment by amelieled** [comment]
OK. If I delete `set declared "+"`, eglot find a parse error too.

**Comment by fblanqui** [comment]
I guess that this is the combination of `set declared "+"` and `set infix right 6 "+" ≔ plus`. @rlepigre, could you confirm?

**Comment by rlepigre** [comment]
Clearly, if you define `+` as a declared name and as an infix symbols you can run into trouble. Maybe we should do slightly more checks there. We should probably shadow previous declarations of a name when a new one is given. In your case, the declaration would then never be used.

Note that `set declared "..."` is solely used to define a name that can be used for a stand-alone symbol or variable. You should typically not do that and then define the same symbol as an infix.

**Comment by amelieled** [comment]
Everything is OK in this case:

```
require open amelie.notation
require open amelie.Logic
                                  
// //////////////////////// Entiers naturels
                  
symbol plus : N ⇒ N ⇒ N
rule plus 0      &m → &m
 and plus (S &v) &m → S (plus &v &m)

set infix right 6 "+" ≔ plus
                                  
// //////////////////////// Logique sur les booléens

//require open amelie.Logic

// ...

// //////////////////////// Retour sur les entiers naturels

theorem plus_0_n : ∀n, π ((O+n) = n)
proof
  assume n
  refine eq_refl n
qed
```
(except the fact that when I ran "lambdapi check ...":
`Checked [/home/camel/Bureau/Stage_LSV/lambdapi/tests/lambdapi_examples/Logic.lp]`
`Checked [/home/camel/Bureau/Stage_LSV/lambdapi/tests/lambdapi_examples/qr_eLuQfs.lp]`
So, I don't know what is `qr_eLuQfs.lp`)

But in this case:
```
require open amelie.notation
                                  
// //////////////////////// Entiers naturels
                  
symbol plus : N ⇒ N ⇒ N
rule plus 0      &m → &m
 and plus (S &v) &m → S (plus &v &m)

set infix right 6 "+" ≔ plus
                                  
// //////////////////////// Logique sur les booléens

require open amelie.Logic

// ...

// //////////////////////// Retour sur les entiers naturels

theorem plus_0_n : ∀n, π ((O+n) = n)
proof
  assume n
  refine eq_refl n
qed
```
I have a parse error on the line `theorem plus_0_n : ∀n, π ((O+n) = n)` with `lambdapi check ...` (but not with eglot).
I didn't define another "+" notation in notation.lp and Logic.lp as you can see:

```
// Proposition type
constant symbol Prop : TYPE      // Type of propositions
set declared "π"
injective symbol π : Prop ⇒ TYPE // Interpretation of propositions in TYPE

// Set type
constant symbol Set : TYPE       // Type of set codes
set declared "τ"
injective symbol τ : Set ⇒ TYPE  // Interpretation of set codes in TYPE

// Boolean type
constant symbol bool : Set       // Type of booleans
definition B ≔ τ bool
constant symbol true : B
constant symbol false : B

// Nat type
constant symbol nat  : Set       // Type of natural numbers
definition N ≔ τ nat
constant symbol O : N
constant symbol S : N ⇒ N
set builtin "0"  ≔ O             // Enabling builtin natural number literals
set builtin "+1" ≔ S

// Leibniz equality
constant symbol eq {a} : τ a ⇒ τ a ⇒ Prop
set infix 8 "=" ≔ eq
constant symbol eq_refl {a} (x : τ a) : π (x = x)
constant symbol eq_ind {a} (x y : τ a) : π (x = y) ⇒ ∀p, π (p y) ⇒ π (p x)

// Set builtins for the rewrite tactic
set builtin "P"     ≔ π
set builtin "T"     ≔ τ
set builtin "eq"    ≔ eq
set builtin "refl"  ≔ eq_refl
set builtin "eqind" ≔ eq_ind

// Properties of Leibniz equality
theorem eq_sym {a} (x y:τ a) : π (x=y) ⇒ π (y=x)
proof
  assume a x y xy
  symmetry
  apply xy
qed
```
```
require open amelie.notation

// Conjunction
constant symbol conj : Prop ⇒ Prop ⇒ Prop
set infix right 7 "∧" ≔ conj
constant symbol conj_intro p q : π p ⇒ π q ⇒ π (p ∧ q)
symbol conj_elim_left  p q : π (p ∧ q) ⇒ π p
symbol conj_elim_right p q : π (p ∧ q) ⇒ π q
//and_ind : ∀ A B P:Prop, (A→B→P)→A∧B→P
// assert p q r ⊢ p ∧ q ∧ r ≡ p ∧ (q ∧ r)

// Disjunction
constant symbol disj : Prop ⇒ Prop ⇒ Prop
set infix right 6 "∨" ≔ disj
constant symbol disj_intro_left  p q : π p ⇒ π (p ∨ q)
constant symbol disj_intro_right p q : π q ⇒ π (p ∨ q)
symbol disj_elim p q r : π (p ∨ q) ⇒ (π p ⇒ π r) ⇒ (π q ⇒ π r) ⇒ π r

// assert p q r ⊢ p ∨ q ∧ r ≡ p ∨ (q ∧ r) // check that propositions are parsed correctly
  
// False
set declared "⊥"
constant symbol ⊥ : Prop
symbol false_elim p : π ⊥ ⇒ π p

// True
set declared "⊤"
symbol ⊤ : Prop
symbol I : π (⊤)

// Negation
set declared "¬"
constant symbol ¬ : Prop ⇒ Prop
constant symbol neg_intro p : (π p ⇒ π ⊥) ⇒ π (¬p)
symbol neg_elim  p : π (¬ p) ⇒ π p ⇒ π ⊥
rule π (¬ &p) → π &p ⇒ π ⊥

// assert p q ⊢ ¬ p ∧ q ≡ (¬ p) ∧ q

// Intro and Elimination of imp
constant symbol imp : Prop ⇒ Prop ⇒ Prop
set infix right 5 "⊃" ≔ imp
//constant symbol imp_intro p q : (π p ⇒ π q) ⇒ π (imp p q)
//symbol imp_elim  p q : π (imp p q) ⇒ π p ⇒ π q
rule π (&p ⊃ &q) → π &p ⇒ π &q

// assert p q r s ⊢ p ∧ q ⊃ r ∨ s ≡ (p ∧ q) ⊃ (r ∨ s)

// assert a (x y : τ a) ⊢ x = y ∧ x = y ⊃ x = y ∨ x = y ≡ (x = y ∧ x = y) ⊃ (x = y ∨ x = y)

// Universal quantification
constant symbol forall {a} : (τ a ⇒ Prop) ⇒ Prop
rule π (forall &f) → ∀x, π (&f x)

// Existential quantification
set declared "∃"
constant symbol ∃ {a} : (τ a ⇒ Prop) ⇒ Prop
constant symbol ex_intro {a} p (x:τ a) : π (p x) ⇒ π (∃ p)
symbol ex_elim {a} p q : π (∃ p) ⇒ (∀x:τ a, π (p x) ⇒ π q) ⇒ π q

// Set builtins for the rewrite tactic
set builtin "all"   ≔ forall
set builtin "bot"   ≔ ⊥
set builtin "top"   ≔ ⊤
set builtin "imp"   ≔ imp
set builtin "and"   ≔ conj
set builtin "or"    ≔ disj
set builtin "not"   ≔ ¬
```
except in `set builtin "+1" ≔ S`

If I delete this line, `lambdapi check ...` runs correctly (but I have always a strange file:
`Checked [/home/camel/Bureau/Stage_LSV/lambdapi/tests/lambdapi_examples/notation.lp]`
`Checked [/home/camel/Bureau/Stage_LSV/lambdapi/tests/lambdapi_examples/Logic.lp]`
`Checked [/home/camel/Bureau/Stage_LSV/lambdapi/tests/lambdapi_examples/qr_HG7eB9.lp]`

So, I should define "+" notation xor `set builtin "+1" ≔ S` ?

**Comment by rlepigre** [comment]
> So, I should define "+" notation xor `set builtin "+1" ≔ S` ?

No, here `"+1" is only a specific string. It does not interact in any way with notations (except that, when defined, it allows you to use decimal notations).

**Comment by rlepigre** [comment]
I have no idea where these weird file names come form. In any case, I can't reproduce if you don't provide me with an archive containing all your files and an explanation of how to run `lambdapi` to get the same output. Also, what version of Lambdapi do you use? (run `lambdapi version`).

**Comment by amelieled** [comment]
Ok thank.

In fact, the second problem comes from `quickrun`: if I run `lamndapi check` in terminal, the result is correct:
```
lambdapi check test.lp
Checked [/home/camel/Bureau/Stage_LSV/lambdapi/tests/lambdapi_examples/notation.lp]
Checked [/home/camel/Bureau/Stage_LSV/lambdapi/tests/lambdapi_examples/Logic.lp]
Checked [/home/camel/Bureau/Stage_LSV/lambdapi/tests/lambdapi_examples/test.lp]
```

**Comment by rlepigre** [comment]
Oh I see. I guess `quickrun` generates some temporary file name.

**Comment by amelieled** [comment]
Ok but to recap:


```
// ///////////////////////// Notation
////////////////////////////////////////
// Proposition type
constant symbol Prop : TYPE      // Type of propositions
set declared "π"
injective symbol π : Prop ⇒ TYPE // Interpretation of propositions in TYPE

// Set type
constant symbol Set : TYPE       // Type of set codes
set declared "τ"
injective symbol τ : Set ⇒ TYPE  // Interpretation of set codes in TYPE

// Leibniz equality
constant symbol eq {a} : τ a ⇒ τ a ⇒ Prop
set infix 8 "=" ≔ eq
constant symbol eq_refl {a} (x : τ a) : π (x = x)
constant symbol eq_ind {a} (x y : τ a) : π (x = y) ⇒ ∀p, π (p y) ⇒ π (p x)
constant symbol nat : Set

require open amelie.Logic

// //////////////////////// Entiers naturels
/////////////////////////////////////////////
set declared "ℕ"
definition ℕ ≔ τ nat
constant symbol zero : ℕ
constant symbol succ : ℕ ⇒ ℕ

// Enabling builtin natural number literals
set builtin "0"  ≔ zero
set builtin "+1" ≔ succ

///////////////////////////////
// Addition
///////////////////////////////
symbol plus : ℕ ⇒ ℕ ⇒ ℕ
set infix left 6 "+" ≔ plus
assert λx y z,x+y+z ≡ λx y z,(x+y)+z // check that x+y=z is parsed correctly
rule       0 + &y → &y
 and succ &x + &y → succ (&x + &y)

// //////////////////////// Logique sur les booléens

//require open amelie.Logic

// ...

// //////////////////////// Retour sur les entiers naturels

theorem plus_0_n : ∀n, π ((0+n) = n)
proof
  assume n
  refine eq_refl n
qed
```
No parser error here, but if you open Logic.lp after the definition of "+", there is a parse error.

Nothing is defined about "+", as you can see before.

**Comment by rlepigre** [comment]
Do you mean that you have the problem when you have `require open amelie.Logic` twice in your file?

And again, I cannot help you if I don't have all of your files in hand. Especially if the problem you have seems to come for modules and notations scoping.

**Comment by amelieled** [comment]
No, just once.

Yes but you have the code. Just to remember you, Logic.lp is:

```
require open amelie.notation

// Conjunction
constant symbol conj : Prop ⇒ Prop ⇒ Prop
set infix right 7 "∧" ≔ conj
constant symbol conj_intro p q : π p ⇒ π q ⇒ π (p ∧ q)
symbol conj_elim_left  p q : π (p ∧ q) ⇒ π p
symbol conj_elim_right p q : π (p ∧ q) ⇒ π q
//and_ind : ∀ A B P:Prop, (A→B→P)→A∧B→P
// assert p q r ⊢ p ∧ q ∧ r ≡ p ∧ (q ∧ r)

// Disjunction
constant symbol disj : Prop ⇒ Prop ⇒ Prop
set infix right 6 "∨" ≔ disj
constant symbol disj_intro_left  p q : π p ⇒ π (p ∨ q)
constant symbol disj_intro_right p q : π q ⇒ π (p ∨ q)
symbol disj_elim p q r : π (p ∨ q) ⇒ (π p ⇒ π r) ⇒ (π q ⇒ π r) ⇒ π r

// assert p q r ⊢ p ∨ q ∧ r ≡ p ∨ (q ∧ r) // check that propositions are parsed correctly
  
// False
set declared "⊥"
constant symbol ⊥ : Prop
symbol false_elim p : π ⊥ ⇒ π p

// True
set declared "⊤"
symbol ⊤ : Prop
symbol I : π (⊤)

// Negation
set declared "¬"
constant symbol ¬ : Prop ⇒ Prop
constant symbol neg_intro p : (π p ⇒ π ⊥) ⇒ π (¬p)
symbol neg_elim  p : π (¬ p) ⇒ π p ⇒ π ⊥
rule π (¬ &p) → π &p ⇒ π ⊥

// assert p q ⊢ ¬ p ∧ q ≡ (¬ p) ∧ q

// Intro and Elimination of imp
constant symbol imp : Prop ⇒ Prop ⇒ Prop
set infix right 5 "⊃" ≔ imp
//constant symbol imp_intro p q : (π p ⇒ π q) ⇒ π (imp p q)
//symbol imp_elim  p q : π (imp p q) ⇒ π p ⇒ π q
rule π (&p ⊃ &q) → π &p ⇒ π &q

// assert p q r s ⊢ p ∧ q ⊃ r ∨ s ≡ (p ∧ q) ⊃ (r ∨ s)

// assert a (x y : τ a) ⊢ x = y ∧ x = y ⊃ x = y ∨ x = y ≡ (x = y ∧ x = y) ⊃ (x = y ∨ x = y)

// Universal quantification
constant symbol forall {a} : (τ a ⇒ Prop) ⇒ Prop
rule π (forall &f) → ∀x, π (&f x)

// Existential quantification
set declared "∃"
constant symbol ∃ {a} : (τ a ⇒ Prop) ⇒ Prop
constant symbol ex_intro {a} p (x:τ a) : π (p x) ⇒ π (∃ p)
symbol ex_elim {a} p q : π (∃ p) ⇒ (∀x:τ a, π (p x) ⇒ π q) ⇒ π q

// Set builtins for the rewrite tactic
set builtin "all"   ≔ forall
set builtin "bot"   ≔ ⊥
set builtin "top"   ≔ ⊤
set builtin "imp"   ≔ imp
set builtin "and"   ≔ conj
set builtin "or"    ≔ disj
set builtin "not"   ≔ ¬
```

**Comment by rlepigre** [comment]
> Yes but you have the code. Just to remember you, Logic.lp is:

For instance I have no `notation` module. And I don't have time to copy paste stuff from the browser, and I also don't have your package file.

What is it so hard to create a tarball, use whatever file sharing website you want, and paste the link to the file here?

**Comment by amelieled** [comment]
You can go here:
[github.com/amelieled/lambdapi_examples/blob/master/333.lp](github.com/amelieled/lambdapi_examples/blob/master/333.lp)

Just a remark: I think it's better to have the code in the discussion because right now there's no viable way to transmit files, so the outcome loses its appeal over time. So I propose to make a Deducteam/lambdapi_issues directory and to make one folder per issue to put the code (if necessary). This avoids downloading these codes at the same time as lambdapi, and allows everyone to put code easily.

**Comment by fblanqui** [comment]
@amelieled  it is already possible in Github to attach files in your comments...

**Comment by rlepigre** [comment]
Thanks for the report @amelieled, it turns out that the parser was not reentrant but nobody had noticed it yet because notations have not been used that heavily until now. The parser needs to be reentrant because it may call itself through the require command, which may trigger compilation (and hence also parsing).
