### ISSUE TITLE
Multi-lines comments

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#335]
Hi @rlepigre . Could you please add multi-lines like in Dedukti? Chantal Keller already pointed out this missing feature some time ago. I do agree with her. The advantages surpass the disadvantages.

**Comment by rlepigre** [comment]
I already made an argument against that. This is going to be a problem to implement a `lambdapi depend` command sometime later. And it is not like editors cannot comment regions.

**Comment by francoisthire** [comment]
In that case maybe this feature should be added by the editor modes supporting `lambdapi`. Is it already the case of `vscode` and `emacs`?

**Comment by gabrielhdt** [comment]
@francoisthire, if you're talking about commenting regions, it's `M-;` in emacs (after selection of region).

**Comment by fblanqui** [comment]
@gabrielhdt thanks to add this in the doc of emacs since this question will be asked often

**Comment by francoisthire** [comment]
> @francoisthire, if you're talking about commenting regions, it's `M-;` in emacs (after selection of region).

Yes ! I agree with @fblanqui  that this should be in the doc. But for that kind of question, maybe the doc needs an FAQ or something similar, it would be easier to find the answer if this was in an FAQ IMHO.

**Comment by fblanqui** [comment]
Yes, we could create a FAQ.md as well. Good idea!

**Comment by gabrielhdt** [comment]
> @gabrielhdt thanks to add this in the doc of emacs since this question will be asked often

Would writing a doc on my PR #308 be OK?

**Comment by fblanqui** [comment]
yes

**Comment by fblanqui** [comment]
Multi-line comments are allowed since #516 .
