### ISSUE TITLE
builtins not exported

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#337]
I have in a file `lhol.lp`
```
set builtin "T" ≔ η
set builtin "P" ≔ ε
```
and I want to set in a file `equality.lp` which require opens `lhol.lp`
```
symbol equal {T: Set}: η T ⇒ η T ⇒ Bool
set builtin "eq" ≔ equal
```
but it fails with
> `Builtin symbol [T] undefined`.

Bug or feature?

**Comment by rlepigre** [comment]
Sounds like a bug, can you give a self-contained (preferably minimal) example?

**Comment by gabrielhdt** [comment]
Here it is. with a package named `am`,
- file `bg1.lp`
```
symbol U: TYPE
symbol Prop : TYPE
injective symbol T: U ⇒ TYPE
injective symbol P: Prop ⇒ TYPE
set builtin "T" ≔ T
set builtin "P" ≔ P
```
- file `bg2.lp`
```
require open am.bg1
symbol equal {t: U}: T t ⇒ T t ⇒ Prop
set builtin "eq" ≔ equal
```
answer of `lambdapi check bg2.lp`
> `Checked [/tmp/bg1.lp]`
> `[/tmp/bg2.lp, 3:0-24] Builtin symbol [T] undefined.`

If I collapse the two files into one, there is no error.

**Comment by rlepigre** [comment]
OK, that was not a very complex bug, but it still took me a while to debug. The problem was first introduced by @fblanqui in feb25de73ceb50af09f5ce9ccdf7255630bd17b3, and it is due to the fact that builtins were not looked for in the right map (signature map versus scoping map).
