### ISSUE TITLE
Add computations of critical pairs and check local confluence

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#345]
As already discussed elsewhere, it would be nice to add in master an algorithm for computing critical pairs, and another one to check local confluence by trying to join critical pairs up to some maximal number of reduction steps (flag that could be changed by the user if needed).
I believe there has been various implementations of this by @wujuihsuan2016 , @gabrielhdt , @Rehan-MALAK or @barras . It would be nice to summarize the situation and know whether someone could make a PR about this soon.

**Comment by fblanqui** [comment]
Jui Hsuan's code is:
https://github.com/wujuihsuan2016/lambdapi/blob/9aa4992af63daaddbc5c9567d30d32d5b3dd4a3a/src/confluence.ml#L45-L80

**Comment by gabrielhdt** [comment]
<https://github.com/Deducteam/resystance/blob/master/src/critical_pairs.ml> searches for critical pairs, but I believe it has been improved by @barras.

**Comment by fblanqui** [comment]
@barras do you confirm?

**Comment by fblanqui** [comment]
Fixed in #824 .
