### ISSUE TITLE
Module names and relative paths for symbols tree graphs

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#346]
There is a utf8 error when someone tries to write the tree of a utf8 symbol:
```
Writing file [personoj/encodings/lhol.ϕ.gv]
[Sys_error("personoj/encodings/lhol.\207\149.gv: No such file or directory")]
```

Do you know how to handle this, @rlepigre?

**Comment by rlepigre** [comment]
Weird, is the file created correctly? This might be a normalisation problem.

**Comment by gabrielhdt** [comment]
No it's not created.

**Comment by rlepigre** [comment]
It is probably a limitation of the `Sys` API so that it works the same on every platform. I'm not sure about that though. A solution would be to sanitise the file name using some encoding. For example replace every non-ascii character by its hex value or something.

**Comment by gabrielhdt** [comment]
My bad, the error does not come from unicode, but from the path since the modules have been changed. There is no folder that corresponds to the `root_path`, hence the error.
