### ISSUE TITLE
Emacs mode does not work when opening a file that does not exist yet

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#348]

**Comment by fblanqui** [comment]
When we launch emacs with, as argument, a filename that does not exist yet, type some LP code (e.g. symbol N:TYPE) and do Ctrl-C Ctrl-N, emacs loop. The same thing happens when, in emacs, we open a file that does not exist yet. @firewall2142, could you please have a look at this problem?

**Comment by firewall2142** [comment]
I have nothing to say other than what has been discussed in #432. I could make emacs create the file if it doesn't exist, but, as said there, it is a workaround.
