### ISSUE TITLE
Remove "and" keyword?

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#353]
Is it useful to declare a pack of rules rather that  a single rule?

**Comment by fblanqui** [comment]
For preserving confluence, yes. But we could perhaps replace it by something else. Any idea? But why this question?

**Comment by fblanqui** [comment]
"with" which has the advantage of having 4 letters too?

**Comment by gabrielhdt** [comment]
Could you explain a little bit? I don't see the connection. I was wondering if its purpose wan only to build fewer trees.

**Comment by fblanqui** [comment]
When you add a rule, you may create unjoinable critical pairs. So, to preserve (local) confluence, you need to add several rules at the same time.

**Comment by gabrielhdt** [comment]
Does it assume that we want to maintain local confluence each time we add rules? Otherwise, if adding a rule `r1` creates a critical pair which is closed by `r2`, what is the difference, implementation-wise, between
```
rule r1
rule r2
```
and
```
rule r1
 and r2
```
?
As I see it, it makes no difference to lambdapi. Is it related to the confluence checker?

**Comment by fblanqui** [comment]
Local confluence (or termination) should be checked at each rule keyword. In the first case, you would generate a warning or an error. Not in the second case.

**Comment by gabrielhdt** [comment]
I see, so it's just that we don't check yet for local confluence.
