### ISSUE TITLE
Parsing declared identifiers of imported modules

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#369]
Consider files given by
https://gist.github.com/gabrielhdt/c70c1f859fc6bbd29dd49996f8af1936

Declared identifiers of imported modules can't be used.

**Comment by rlepigre** [comment]
Notations are only imported if you `open` the module. So that is normal behaviour it seems.

**Comment by gabrielhdt** [comment]
Is there a reason for not allowing `S.χ`? Because it only looks like a limitation to me.

**Comment by rlepigre** [comment]
This is more complicated to parse, that is the only reason. And I would rather not spend too much time working on the parser now given that it will be replaced soon. Moreover, it is pretty easy to work around this problem by having files containing mostly notations and opening them everywhere they are needed.

**Comment by gabrielhdt** [comment]
Alright.

**Comment by rlepigre** [comment]
That is still something we might want to have in the future though.

**Comment by fblanqui** [comment]
For me, it's a bug and should be fixed within the current parser or the next one.

**Comment by rlepigre** [comment]
That is why I left the issue open. I would not say this is a bug, it is more of a feature right now (I never considered this use case when designing this). But I agree this is a desirable feature. I would prefer not to implement that in the current parser though.

**Comment by fblanqui** [comment]
Fixed in #516 as there is no declared identifiers anymore.
