### ISSUE TITLE
Assertion failed in type command

### ISSUE THREAD

**Issue by elhaddadyacine** [Deducteam/lambdapi#370]
Hello,
This is an example where the command type produces an `assert false`:
```lambdapi

symbol prop  : TYPE
symbol _type  : TYPE
symbol Proof : prop → TYPE
symbol term  : _type → TYPE

constant symbol iota  : _type
symbol False : prop

symbol not : prop → prop
symbol imp : prop → prop → prop

symbol forall : Π (a : _type), (term a → prop) → prop
symbol exists : Π (a : _type), (term a → prop) → prop

symbol seq : TYPE

rule seq ↪ Proof False
rule Proof False ↪ Π (p : prop), Proof p
rule Proof (not $p) ↪ Proof $p → Proof False

rule Proof (imp $p $q) ↪ Proof $p → Proof $q

rule Proof (exists $a $p) ↪ Π(P:prop), (Π(x : term $a), Proof ($p x) → Proof P) → Proof P
rule Proof (forall $a $p) ↪ Π(x : term $a), Proof ($p x)
constant symbol xmid       : Π (p : prop) (z : prop),
	     (Proof p → Proof z) →
	     (Proof (not p) → Proof z) →
	     Proof z

symbol {|a|} : term iota
symbol {|p|} : term iota → term iota →  prop
symbol {|f|} : term iota →  term iota
symbol axiom_A : Proof (forall iota (λ (X1 : (term iota)), exists iota (λ (Y : term iota), ({|p|} X1 Y ))))

type (λax_goal ax_ax, xmid (imp (forall iota (λ{|v_Vm|}, not ({|p|} {|a|} {|v_Vm|}))) (imp (forall iota (λ{|v_Vm|}, {|p|} {|v_Vm|} ({|f|} {|v_Vm|}))) False)) (imp (forall iota (λ{|v_Vm|}, not ({|p|} {|a|} {|v_Vm|}))) (imp (forall iota (λ{|v_Vm|}, {|p|} {|v_Vm|} ({|f|} {|v_Vm|}))) False)) (λH2, H2) (λH3, H3 (λH4, H3 (λH5 H5, axiom_A {|a|} (Proof False) (λz h, H4 z (H5 {|a|})) False) (imp (forall iota (λ{|v_Vm|}, {|p|} {|v_Vm|} ({|f|} {|v_Vm|}))) False)) (imp (forall iota (λ{|v_Vm|}, not ({|p|} {|a|} {|v_Vm|}))) (imp (forall iota (λ{|v_Vm|}, {|p|} {|v_Vm|} ({|f|} {|v_Vm|}))) False))) (xmid (imp (forall iota (λ{|v_Vm|}, not ({|p|} {|a|} {|v_Vm|}))) (forall iota (λ{|v_Vm|}, not ({|p|} {|a|} {|v_Vm|})))) (imp (forall iota (λ{|v_Vm|}, not ({|p|} {|a|} {|v_Vm|}))) (forall iota (λ{|v_Vm|}, not ({|p|} {|a|} {|v_Vm|})))) (λH2, H2) (λH3, H3 (λH4, H3 (λH5, H4) (forall iota (λ{|v_Vm|}, not ({|p|} {|a|} {|v_Vm|})))) (imp (forall iota (λ{|v_Vm|}, not ({|p|} {|a|} {|v_Vm|}))) (forall iota (λ{|v_Vm|}, not ({|p|} {|a|} {|v_Vm|}))))) (xmid (imp (not (exists iota (λ{|v_Vm|}, {|p|} {|a|} {|v_Vm|}))) (forall iota (λ{|v_Vn|}, not ({|p|} {|a|} {|v_Vn|})))) (imp (not (exists iota (λ{|v_Vm|}, {|p|} {|a|} {|v_Vm|}))) (forall iota (λ{|v_Vn|}, not ({|p|} {|a|} {|v_Vn|})))) (λH2, H2) (λH3, H3 (λH4, H3 (λH5 t, xmid (not ({|p|} {|a|} t)) (not ({|p|} {|a|} t)) (λH2, H2) (λH5, H5 (λ{|v_Vt|}, H4 (λz H3, H3 t {|v_Vt|})) (not ({|p|} {|a|} t)))) (forall iota (λ{|v_Vn|}, not ({|p|} {|a|} {|v_Vn|})))) (imp (not (exists iota (λ{|v_Vm|}, {|p|} {|a|} {|v_Vm|}))) (forall iota (λ{|v_Vn|}, not ({|p|} {|a|} {|v_Vn|}))))) (xmid (imp (not (exists iota (λ{|v_Vm|}, {|p|} {|a|} {|v_Vm|}))) (not (exists iota (λ{|v_Vm|}, {|p|} {|a|} {|v_Vm|})))) (imp (not (exists iota (λ{|v_Vm|}, {|p|} {|a|} {|v_Vm|}))) (not (exists iota (λ{|v_Vm|}, {|p|} {|a|} {|v_Vm|})))) (λH2, H2) (λH3, H3 (λH4, H3 (λH5, H4) (not (exists iota (λ{|v_Vm|}, {|p|} {|a|} {|v_Vm|})))) (imp (not (exists iota (λ{|v_Vm|}, {|p|} {|a|} {|v_Vm|}))) (not (exists iota (λ{|v_Vm|}, {|p|} {|a|} {|v_Vm|}))))) ax_goal))) (xmid (imp (forall iota (λ{|v_Vm|}, {|p|} {|v_Vm|} ({|f|} {|v_Vm|}))) (forall iota (λ{|v_Vm|}, {|p|} {|v_Vm|} ({|f|} {|v_Vm|})))) (imp (forall iota (λ{|v_Vm|}, {|p|} {|v_Vm|} ({|f|} {|v_Vm|}))) (forall iota (λ{|v_Vm|}, {|p|} {|v_Vm|} ({|f|} {|v_Vm|})))) (λH2, H2) (λH3, H3 (λH4, H3 (λH5, H4) (forall iota (λ{|v_Vm|}, {|p|} {|v_Vm|} ({|f|} {|v_Vm|})))) (imp (forall iota (λ{|v_Vm|}, {|p|} {|v_Vm|} ({|f|} {|v_Vm|}))) (forall iota (λ{|v_Vm|}, {|p|} {|v_Vm|} ({|f|} {|v_Vm|}))))) (xmid (imp (forall iota (λ{|v_Vm|}, {|p|} {|v_Vm|} ({|f|} {|v_Vm|}))) (forall iota (λ{|v_Vm|}, {|p|} {|v_Vm|} ({|f|} {|v_Vm|})))) (imp (forall iota (λ{|v_Vm|}, {|p|} {|v_Vm|} ({|f|} {|v_Vm|}))) (forall iota (λ{|v_Vm|}, {|p|} {|v_Vm|} ({|f|} {|v_Vm|})))) (λH2, H2) (λH3, H3 (λH4, H3 (λH5, H4) (forall iota (λ{|v_Vm|}, {|p|} {|v_Vm|} ({|f|} {|v_Vm|})))) (imp (forall iota (λ{|v_Vm|}, {|p|} {|v_Vm|} ({|f|} {|v_Vm|}))) (forall iota (λ{|v_Vm|}, {|p|} {|v_Vm|} ({|f|} {|v_Vm|}))))) ax_ax)))
```

**Comment by gabrielhdt** [comment]
Rewriting products isn't handled.

**Comment by francoisthire** [comment]
But where do you see a rule which rewrite a product? And why is it
trigerred during a type command?

**Comment by gabrielhdt** [comment]
It ends evaluating `Proof (Proof False)` which rewrites to `Proof (Π (p : prop), Proof p)`, and thus the engine tries to rewrite the product, hence the failure. It can be seen with `set debug +e`.

**Comment by gabrielhdt** [comment]
So if one computes first the type of `axiom_A`, one finds
```
axiom_a: Π(x:term iota) (P:prop), (Π(x0:term iota), Proof ({|p|} x x0) → Proof P) → Proof P
```
since the 2nd argument (`P` of `axiom_A` is `Proof False), we obtain indeed `Proof (Proof False)`.

We may not raise an error and just not rewrite anything? (I can implement this)

**Comment by rlepigre** [comment]
@gabrielhdt it seems that you have minimized the example, could you post the result here? It will be easier to understand what precisely happens with a smaller file with less rules and as few definitions as possible. I don't have yet a clear understanding why that case can actually trigger; and I am wondering why we thought it could not when implementing the decision trees.

**Comment by gabrielhdt** [comment]
Here is the example
```
symbol prop  : TYPE
symbol _type  : TYPE
symbol Proof : prop → TYPE
symbol term  : _type → TYPE

constant symbol iota  : _type
symbol False : prop

symbol forall : Π (a : _type), (term a → prop) → prop
symbol exists : Π (a : _type), (term a → prop) → prop

rule Proof False ↪ Π (p : prop), Proof p
rule Proof (exists $a $p) ↪ Π(P:prop), (Π(x : term $a), Proof ($p x) → Proof P) → Proof P
rule Proof (forall $a $p) ↪ Π(x : term $a), Proof ($p x)

symbol {|a|} : term iota
symbol {|p|} : term iota → term iota →  prop
symbol axiom_A :
Proof (forall iota (λ (X1 : (term iota)),
                    exists iota (λ (Y : term iota), ({|p|} X1 Y ))))

compute Proof (forall iota (λ (X1 : (term iota)),
                    exists iota (λ (Y : term iota), ({|p|} X1 Y ))))
type (λH4 H5 H5, axiom_A {|a|} (Proof False) (λz h, H4 z (H5 {|a|})) False)
```

**Comment by rlepigre** [comment]
What is weird with that example is that we end up evaluating an ill-typed term during type checking, which probably should not happen right?

I am also wondering, can we get to a similar error with a more legit example?

As far as reduction is concerned, I think we could simply replace the line
https://github.com/Deducteam/lambdapi/blob/ef7ea222a61c3a96c075631cd554d2c00a5f7145/src/core/eval.ml#L319
with
```ocaml
         | _          -> default ()
```
Is that what you had in mind @gabrielhdt?

**Comment by gabrielhdt** [comment]
Yes, but it must be a bad idea. This would allow terms of the form `f (Πx, ...)` to be computed, whereas they aren't valid.

**Comment by fblanqui** [comment]
This is not weird. The starting term is ill-typed. The second argument 
of axiom_A is of type prop. So it should be False instead of Proof 
False. Currently, type inference works in 2 steps. First, we generate 
constraints. Second, we try to solve them. When generating constraints, 
we evaluate subterms that are potentially ill-typed because we didn't 
solve their constraints yet... This problem is not new, and solving it 
won't be easy (see the numerous papers on unification)... What we could 
do for the moment perhaps is to raise a fatal error saying that there is 
probably a typing error...

Le 21/04/2020 à 23:14, Rodolphe Lepigre a écrit :
> What is weird with that example is that we end up evaluating an 
> ill-typed term during type checking, which probably should not happen 
> right?

**Comment by fblanqui** [comment]
One simple thing we could do as well is, in Infer.conv, call Unif.solve instead of Eval.eq_modulo, in order to detect unsolvable constraints as soon as possible. In the above example, a constraint TYPE = prop is generated that would be rejected by Unif.solve.

**Comment by francoisthire** [comment]
> What we could
do for the moment perhaps is to raise a fatal error saying that there is
probably a typing error...

I am not completely sure about this solution. Well I agree on your diagnostic, I think that it would be easier if Yacine, which could be considered now as an extensive user of `lambdapi` could debug the code himself.  However, if you generate big lambda terms, spotting such a bug with this error message seems difficult.

For example in the current version of Dedukti the error message we have is:
```
[ERROR CODE:101]  [/tmp/test.dk] [line:23 column:35] 
Error while typing 'test.Proof test.False' in context:
[
  x : test.prop
].
---- Expected:
test.prop
---- Inferred:
Type
```

Which is more informative. Of course, I had to provide a type for `x` which does not exist in the example, but this is somehow irrelevant here. 

A naïve solution I have in mind would be for `lambdapi` to print a debugging file. This file would be a valid `lambdapi` file which adds:
- unsolved meta-variables as axioms
- constraints as rewrite rules

This way, the user would have a file which would be "debuggable" and see the issue by calling the type checker on this file without the use of the inference mechanism.

**Comment by rlepigre** [comment]
> One simple thing we could do as well is, in Infer.conv, call Unif.solve instead of Eval.eq_modulo, in order to detect unsolvable constraints as soon as possible. In the above example, a constraint TYPE = prop is generated that would be rejected by Unif.solve.

None of this would have happened if you kept using syntactic equality instead of calling conversion there @fblanqui, so maybe we should go back to that. The point of this code was to eliminate all trivial equations as soon as possible because there are many of them in practice. And this was harmless with respect to reduction. I think it would be better to let unification deal with this problem I think.

Another solution would be to not do any test at all, but that would be annoying for debugging as this would add a lot of unnecessary equations.

**Comment by fblanqui** [comment]
Syntactic equality or not, this does not change anything on the fact that type inference reduces ill-typed terms and so whnf can fail or not terminate.

**Comment by fblanqui** [comment]
In fact, changing eq_modulo by eq doesn't change anything. The same error occurs with eq. @rlepigre, you should better check before accusing people...

**Comment by fblanqui** [comment]
Anyway, as mentioned by Gabriel, rewriting should not fail. The shape of terms on which rewriting is applied should not matter. Whether they are well-typed or not either. So, it seems there is a bug in rewriting anyway. @gabrielhdt could you please try to fix it?

**Comment by rlepigre** [comment]
> Syntactic equality or not, this does not change anything on the fact that type inference reduces ill-typed terms and so whnf can fail or not terminate.

Indeed, but at least syntactic equality would give us (I think) the invariant that type-checking cannot evaluate ill-typed terms. It would be better to leave heuristics to unification and guarantee that type-checking cannot fail due to bad evaluation.

> In fact, changing eq_modulo by eq doesn't change anything. The same error occurs with eq. @rlepigre, you should better check before accusing people...

OK, I thought unification would catch the problem early enough (i.e., before trying to evaluate). I did not intend to "accuse" anyone, only to point to the fact that the error was traced to your recent change (which I think is wrong due to the reason I mentioned above). I made an hypothesis which seemed plausible, if you disproved it then good: my hypothesis was wrong. And sorry if I hurt you feelings in any way.

> Anyway, as mentioned by Gabriel, rewriting should not fail. The shape of terms on which rewriting is applied should not matter. Whether they are well-typed or not either. So, it seems there is a bug in rewriting anyway. @gabrielhdt could you please try to fix it?

I think you an simply apply the change I proposed in a previous message. The only question is: should we use `None` or `default ()`. Both can make sense I guess, but  maybe `default ()` would be more robust. If we can evaluate arbitrary terms then this is probably the way to go.

**Comment by gabrielhdt** [comment]
With the PR, the error message becomes

```
Cannot solve Proof (Π(p:prop), Proof p) ≡ Π(x0:prop), ?11[x,x0].
Cannot solve TYPE ≡ prop.
Cannot infer the type of [λx, axiom_A {|a|} (Proof False) x False].
```

**Comment by fblanqui** [comment]
No. infer calls whnf anyway. It has nothing to do with conv.

Le 22/04/2020 à 14:33, Rodolphe Lepigre a écrit :
>
>     Syntactic equality or not, this does not change anything on the
>     fact that type inference reduces ill-typed terms and so whnf can
>     fail or not terminate.
>
> Indeed, but at least syntactic equality would give us (I think) the 
> invariant that type-checking cannot evaluate ill-typed terms. It would 
> be better to leave heuristics to unification and guarantee that 
> type-checking cannot fail due to bad evaluation.
>
