### ISSUE TITLE
Admitted and admit

### ISSUE THREAD

**Issue by amelieled** [Deducteam/lambdapi#380]
Is it possible to change "admit" to "admitted" (like in Coq) to add the tactic "admit" (like in Coq) in the future?

**Comment by fblanqui** [comment]
Why would you like admit as a *tactic*?

**Comment by amelieled** [comment]
It a very useful tactic when you tried to do a proof.
I know that LP isn't a proof assistant but maybe it's a good feature.

**Comment by fblanqui** [comment]
LP *is* a proof assistant. It is just missing more tactics and a better interface.

Why not a tactic "fail"? The advantage is that you could put "fail" in the middle of a proof script.

**Comment by amelieled** [comment]
Yes but it's before a logical framework, no?
Yes, your tactic "fail" is exactly the tactic Coq "admit".
Maybe "break" or "skip" are better then "fail", I don't know.

**Comment by amelieled** [comment]
I tested it today, but it seems to be not correct.
This tactic just raises an error, but does nothing?

**Comment by fblanqui** [comment]
Right.

**Comment by amelieled** [comment]
Here, there is a problem again.
