### ISSUE TITLE
Forbidden character in parser.ml

### ISSUE THREAD

**Issue by amelieled** [Deducteam/lambdapi#381]
Why ";" is a forbidden character? I mean, that character isn't used in the parser, is it?
(It could be a good one for the tactical (like in Coq).)

It's the same thing for "&" whereas the new character for metavariable in pattern is "$", right ?

**Comment by fblanqui** [comment]
";" is forbidden as it may well be used later in the syntax. As for "&", it should be fine to use it as it is not in the syntax anymore. Do you have problems using it?

**Comment by amelieled** [comment]
No, I haven't problem about it.
But "$" must be added as a forbidden character, no?

**Comment by fblanqui** [comment]
It is already i think. See https://github.com/Deducteam/lambdapi/blob/3775cbbc876eb36c6569883c4ee008409594f13e/src/core/parser.ml#L125-L130

**Comment by amelieled** [comment]
Yes you right. I did a mistake.
So in conclusion, ";" can be a tactical, like in Coq.
