### ISSUE TITLE
Multiple quantification

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#401]
If I'm not mistaken, quantifiers only allow to quantify on one variable, so if `Q` is set as a quantifier, we can only write `Q x, t`. It would be convenient to allow quantifying on several variables: `Q x y z, t` or `Q (x: t) (y: u) (z: v), w`.

**Comment by fblanqui** [comment]
Fixed in https://github.com/Deducteam/lambdapi/pull/516.
