### ISSUE TITLE
Error in emacs mode: void-variable math-symbol-list-subscripts

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#410]
```
Eager macro-expansion failure: (void-variable math-symbol-list-subscripts)
File mode specification error: (void-variable math-symbol-list-subscripts)
```

**Comment by gabrielhdt** [comment]
Have you upgrade your `math-symbol-lists` package?

**Comment by fblanqui** [comment]
I have the version 20151215.1043 installed.

**Comment by gabrielhdt** [comment]
You need version 1.2.1 published in 2019.

**Comment by fblanqui** [comment]
The version 1.2.1 is "Available Obsolete from gnu". The last version is 20200131.2333. See https://melpa.org/#/math-symbol-lists. Similarly, I have eglot 1.6 but there is a version 20200526.2003. See https://melpa.org/#/eglot. There is something wrong in my config. How do I get the latest version. The latest versions do not appear in my emacs...

**Comment by gabrielhdt** [comment]
It might be obsolete, but it will still be better than what you have now. But the best would be to install it form melpa. Have you tried going through https://melpa.org/#/getting-started ?
