### ISSUE TITLE
recreate make install_emacs

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#411]
@gabrielhdt could you please recreate in Makefile a target install_emacs. make install should not install the emacs mode in case it gets broken. On the other hand, the opam install script should call it. The same should be done for vim. What do you think?

**Comment by gabrielhdt** [comment]
OK but does it really solve the issue? Suppose the lambdapi-mode is broken, you'll notice it only after having installed it, so whether you have a separate install command or not does not matter. Or can you explain your workflow?

**Comment by fblanqui** [comment]
Currently the emacs mode is broken. But to test my local branch, I need to do make install for emacs to use my local LP. In this case, it installs the broken emacs mode as well, and erase the installed emacs mode as well which may not have this problem. An alternative would be to tell emacs to use my version of LP and not the installed one.

**Comment by fblanqui** [comment]
I have the version 20151215.1043 installed.

**Comment by gabrielhdt** [comment]
Choosing the version of LP to use in emacs seems to be a better idea to me, but it does not change the fact that once you have a broken emacs mode, there is no way to revert, so you're stuck with the broken mode. And I don't see how having a separate install command helps: you'll remark that it's broken once it's installed and it will already be too late.

Perhaps setting up CI for the emacs mode would prevent this, wdyt?

**Comment by fblanqui** [comment]
Well, if the current mode is broken, I can come back to a commit where it is not and do make install_emacs.

**Comment by gabrielhdt** [comment]
Yes I see, what if we have a `install_bin`, `install_emacs` and `install` calls both?

**Comment by gabrielhdt** [comment]
In fact it is trickier than I thought, dune must install everything, you can't choose if you don't make several packages (determined by `.opam` files). So in fine the best would perhaps be to install the emacs mode through MELPA to control its version (you can select the commit you want). `make install` will still install the broken mode, but your emacs configuration won't load it since it loads the one from melpa. It's not really a solution, but a workaround. But anyway, installing through melpa should be advised since it takes care of the dependencies.

**Comment by fblanqui** [comment]
But how to tell emacs to use your own version of the mode when you want to use it?

**Comment by gabrielhdt** [comment]
What do you mean by your own? The one you're developing?

**Comment by fblanqui** [comment]
When you want to modify and test the emacs mode.

**Comment by gabrielhdt** [comment]
Yes, it's a bit inconvenient. There must be a way with `cask`, but I'm not very familiar with it. For this, I made a `test.sh` that launches an emacs with the new mode loaded.
