### ISSUE TITLE
Installing lambdapi on Ubuntu 18.04

### ISSUE THREAD

**Issue by francois-lefoulon** [Deducteam/lambdapi#415]
I tried several installation methods.

The first one is detailed here :
https://github.com/Deducteam/lambdapi/blob/master/README.md

First, I could not install earley.2.0.0 and why3.1.3.1 since opam doesn't recognize them as packages, so I went simply with "earley" and "why3". When trying to pin the package, I got this error :

![Capture d’écran de 2020-06-04 11-14-36](https://user-images.githubusercontent.com/66321594/83854912-a7d40d80-a717-11ea-8f39-73d28f8d9be9.png)
 
Thus, I tried cloning the repository, but make wouldn't work : 
![Capture d’écran de 2020-06-05 10-06-20](https://user-images.githubusercontent.com/66321594/83855541-83c4fc00-a718-11ea-87e1-25e4a14eb178.png)
_______________________________
Other installation method : 
https://github.com/Deducteam/lambdapi/blob/master/doc/devel.md

This time, only earley.2.0.0 would not be recognized : 
![Capture d’écran de 2020-06-05 10-06-10](https://user-images.githubusercontent.com/66321594/83855984-28dfd480-a719-11ea-8c83-ca37a50b783f.png)

and I still got the same error : 
![Capture d’écran de 2020-06-05 10-06-20](https://user-images.githubusercontent.com/66321594/83856032-401ec200-a719-11ea-9325-8103b6b10e97.png)

**Comment by gabrielhdt** [comment]
Which version of opam do you have?

**Comment by francois-lefoulon** [comment]
1.2.2

**Comment by gabrielhdt** [comment]
You need >= 2.0. Btw, I think this kind of issues should be first addressed on the gitter https://gitter.im/Deducteam/lambdapi, and then made into a real issue if there is one.

**Comment by fblanqui** [comment]
To get the last version of opam on XUbuntu do:
```
sudo add-apt-repository ppa:avsm/ppa
sudo apt update
sudo apt-get install opam
```
By the way, to get the last version of emacs do:
```
sudo add-apt-repository ppa:kelleyk/emacs
sudo apt-get update
sudo apt-get install emacs26 emacs-goodies-el
```

**Comment by francois-lefoulon** [comment]
@gabrielhdt I followed the procedure on the opam website (quoted by @fblanqui), and after some fixing in the opam-project file and installing stdlib-shims, my lambdapi installation worked ! Thank you, I wil prefrer using gitter in the future.

@fblanqui Thank you, I had installed opam and emacs via a dummy sudo apt install

**Comment by gabrielhdt** [comment]
@francois-lefoulon what did you have to fix? We might want to fix the file on the repo!

**Comment by francois-lefoulon** [comment]
@gabrielhdt I had to replace 1.2.1 with 1.11 in the file dune-project (which is weird since my version is indeed 1.2.1)

**Comment by gabrielhdt** [comment]
It is 1.11, do you mean the other way round?

**Comment by francois-lefoulon** [comment]
No, I did as I said. I might have modified the file during previous tests though, since make woudn't work, so I think this issue was my mistake.

**Comment by gabrielhdt** [comment]
Ah ok, I guess we can close then.
