### ISSUE TITLE
lambdapi and vscodium

### ISSUE THREAD

**Issue by gares** [Deducteam/lambdapi#417]
I'm trying to use codium and lambdapi, I'm following the instruction in https://github.com/Deducteam/lambdapi/blob/master/doc/ui.md

- The first problem is that the makefile in editors/vscode/ installs the extension to `~/.vscode/extensions/lp-vscode` while vscodium uses `~/.vscode-oss/extensions/lp-vscode`. I guess this is expected, it may be mentioned in the doc how to override this path by passing a variable to make
- the "manage" button of the vscode extension uses a wrong filer for the settings, namely `@ext:mines paristech / inria.vscode-lp`, that returns no result. I could find the settings of the extension by removing the filter
- I've installed lambdapi system wide and `lambdapi lsp` starts. Still the extension seems to not run it (it gives no error, but does not react to changing a `.lp` file and saving it). I've tried both setting `lp.path` to `lambdapi lsp` and writing a simple shell script that execs that command and set `lp.path` to the absolute path of that script. Am I doing something wrong? Is there a way to debug this?

**Comment by fblanqui** [comment]
Hi Enrico! Thanks for your reports. We never tested the extension with vscodium, just code. Hence, the problems. We will try to fix this but it will probably take some time. Hopefully, we currently have until July two people that could help. @vycastor (SED engineer) and @francois-lefoulon (intern).

**Comment by gares** [comment]
For the records, Code and Codium are identical, in the sense that Codium is just removing a "telemetry" file that sends usage statistics to Microsoft. Apart from the config directory name, they should be identical.

I suspect I'm doing something silly, or that there is an actual problem affecting both editors.
