### ISSUE TITLE
How use correctly the tactic "refine"?

### ISSUE THREAD

**Issue by amelieled** [Deducteam/lambdapi#420]
I'm trying to do semantic proofs, but I have a problem that I don't understand:
[tests.txt](https://github.com/Deducteam/lambdapi/files/4770911/tests.txt)
(the correct extension is ".lp")

**Comment by amelieled** [comment]
A possible correct solution is:
```
  assume e s v1 v2
  refine EA_ind (λe, eval_EA e s v1 ⊃ eval_EA e s v2 ⊃ v1 = v2) _ _ _ _ _ e
```

**Comment by amelieled** [comment]
BUT, I need to the quantification on s v1 v2 on every hypothesis where it's possible, to finish the proof.
I mean, my problem can be resolved with the tactic `generalize dependant` in Coq.

**Comment by fblanqui** [comment]
@amelieled can we close this issue ?
