### ISSUE TITLE
Question about "Debugging flags"

### ISSUE THREAD

**Issue by amelieled** [Deducteam/lambdapi#424]
I'm trying to understand how works "Debugging flags".

In doc/option.md, one can find:
```
--debug FLAGS enables the debugging modes specified by every character of FLAGS. Details on available character flags are obtained using --help.
```

In doc/command.md, one can find:
```
debug mode The user can activate (with +) or deactivate (with -) the debug mode for some functionalities as follows:

set debug +ts
set debug -s
Each functionality is represented by a single character. For instance, i stands for type inference. To get the list of debuggable functionalities, run the command lambdapi --help.
```

But I don't see anything about flags and options with the command `lambdapi --help`, except `--help` and `--version`.

**Comment by gabrielhdt** [comment]
Ah that's true, the documentation has to be updated (it was available before subcommand were implemented). You can see the flags with `lambdapi check --help`.

**Comment by amelieled** [comment]
Ah yes perfect! It works, thanks! :+1:
