### ISSUE TITLE
Ill formed patterns allowed

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#433]
The following is allowed although it's not a valid pattern (pattern variable applied)
```
symbol A: TYPE
symbol f: (A → A) → A
rule f $a ↪ f (λx, $a x)
```

**Comment by fblanqui** [comment]
I don't understand. What is the problem? There is no error. Why isn't `$a` a valid pattern? What do you mean by "valid"? By the way, note that your rule does not terminate...

**Comment by gabrielhdt** [comment]
Are we allowed to apply pattern variables? Shouldn't we use `λx, $a[x]`?

**Comment by gabrielhdt** [comment]
Ah sorry, I've been confused: we're not allowed to *match* on pattern application but it's totally fine to apply a pattern variable in the rhs.

**Comment by fblanqui** [comment]
Yes, we can apply variables. Example: the map function!

**Comment by fblanqui** [comment]
But some time ago you told me it was possible to match bound variable applications like in `\lambda x, x $a`. Is it right? So it seems possible to match application nodes to some extent. What about `\lambda x, $a x`?

**Comment by gabrielhdt** [comment]
Yes we can match on `\x, x $a`, see the last example of `tests/OK/patterns.lp`. The pattern `\x, $a x` is rejected at scoping (line 154 of `scope.ml`).

**Comment by fblanqui** [comment]
But is there anything that prevents your decision trees to handle this case as well? Perhaps scoping is too restrictive.

**Comment by gabrielhdt** [comment]
I think the trees are able to handle this. But isn't it redundant to have both `$b x` and `$b[x]`?

**Comment by fblanqui** [comment]
`$b x` and `$b[x]` are not equivalent. In the second case, the matched term does not need to be an application node and, in the first case, `$b` cannot depend on `x`.

**Comment by gabrielhdt** [comment]
Ah indeed, it's a bit subtle because I was thinking that writing `\x, $b[] x` is the same as writing `\x, (\y, $b[y]) x`, but `$b[y]` can contain bound variable `x`.

**Comment by fblanqui** [comment]
Well, in `\x, (\y, $b[y]) x`, `$b[y]` cannot contain `x`. But this term is not in beta-normal form. We should reject this pattern just for this reason.

**Comment by gabrielhdt** [comment]
Right, terms not in beta normal form are rejected by the trees at least, but we should have a test file.
