### ISSUE TITLE
Assertion failed exception when checking termination

### ISSUE THREAD

**Issue by faustind** [Deducteam/lambdapi#438]
**Description**
The documented command to check termination raises an exception (?).

**To Reproduce**
1. run `lambdapi init my_package`
2. run `cd my_package && make`
3. run `lambdapi check --termination "cat > output.xml; echo MAYBE" nat.lp`
  `Uncaught [File "src/core/xtc.ml", line 69, characters 31-37: Assertion failed]`
  
**Expected behavior**
Actually, I don't know what to expect.

**System:**
 - OS: Ubuntu 20.04 on WSL 2
 - OCaml: 4.07.1

**Comment by fblanqui** [comment]
Hello @faustind . Sorry for the inconvenience. @GuillaumeGen should be able to have a look at this very soon hopefully.

**Comment by fblanqui** [comment]
Hi @faustind . After Gabriel's fix, it should better work. Don't hesitate to open other issues if you get other problems!
