### ISSUE TITLE
No example with the focus tactic

### ISSUE THREAD

**Issue by Rehan-MALAK** [Deducteam/lambdapi#443]
add a proof with the focus tactic https://github.com/Deducteam/lambdapi/blob/master/docs/tactics.rst#focus

**Comment by fblanqui** [comment]
For the record, an example is provided in https://github.com/Deducteam/lambdapi/pull/444 .

**Comment by fblanqui** [comment]
Fixed in #598 in file tests/OK/admit.lp.
