### ISSUE TITLE
Remove compilation option -w -27 due to Earley

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#447]
https://github.com/Deducteam/lambdapi/blob/9e080cd73ab5d655086197fcdee5a8290b87ce71/src/core/dune#L15

**Comment by Rehan-MALAK** [comment]
I would be very happy to find a solution for this... even a very crappy hackish one.
Let the compiler find for us unused variable avoid so much stupid errors in ocaml.
