### ISSUE TITLE
security vulnerability in VSCode interface

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#448]
Github found a vulnerable dependency:
Known  low severity security vulnerability detected in minimist < 0.2.1 defined in package-lock.json.
You have Dependabot security updates enabled, so we are attempting to create a pull request to update the vulnerable dependency.

https://github.com/Deducteam/lambdapi/blob/9e080cd73ab5d655086197fcdee5a8290b87ce71/editors/vscode/package-lock.json#L214-L219

https://github.com/Deducteam/lambdapi/network/alert/editors/vscode/package-lock.json/minimist/open

**Comment by fblanqui** [comment]
Should we add some code scanning tool? See https://github.com/Deducteam/lambdapi/security/code-scanning

**Comment by fblanqui** [comment]
Hello @francois-lefoulon . Would you mind to make a PR and test it to fix this problem?

**Comment by francois-lefoulon** [comment]
I don't have access to my computer until late this evening ; can it wait?

Should I just delete the minimist part in package-lock? (this isn't my work so I don't know what it is for)

**Comment by fblanqui** [comment]
Of course. There is no hurry. In https://github.com/Deducteam/lambdapi/network/alert/editors/vscode/package-lock.json/minimist/open, they propose:
```
Remediation

Upgrade minimist to version 0.2.1 or later. For example:

"dependencies": {
  "minimist": ">=0.2.1"
}

or…

"devDependencies": {
  "minimist": ">=0.2.1"
}
````
I don't know what is minimist. If it is not useful anymore, you can remove it.

**Comment by firewall2142** [comment]
This can be closed as `minimist` is a development dependency. It won't get bundled with the extension.

**Comment by fblanqui** [comment]
Ok, but I would like the warning to disappear from npm and github...
