### ISSUE TITLE
hangover OK KO tests with alcotest test suite

### ISSUE THREAD

**Issue by Rehan-MALAK** [Deducteam/lambdapi#450]
Dear all !
We used to test each OK / KO test as separate shell commands.
Now, if I understand #449 correctly, the ok_ko.ml is a big executable linked against lambdapi 
(Core module) so one can theoretically do unit tests against the ocaml code.

We are still using these OK / KO tests doing I/O, parsing, scoping, typing.... to check inference, unification, tactics... as if they were unit tests without side effect. Maybe this confusion is a pragmatic choice as it is more enjoyable to write lambdapi files than unit test ocaml code.
And we can still add later proper unit tests.
  
But for now, each OK / KO test has consequences on the following ones.

For example, if I add the following tests/OK/univ2.lp
```
set debug +ui
```
all, the following tests will be done with ``set debug +ui`` (and tests/OK/triangular.lp will take ages)

And we could imagine much much more problematics examples...

**Comment by gabrielhdt** [comment]
I see what you mean. But these issues ought to be solved since if we want to use Dedukti3 for interoperability, we will have to compile several files/modules in the same runtime environment.

**Comment by fblanqui** [comment]
@Rehan-MALAK if you add some `set debug +ui` in a file, you can also add a `set debug -ui` later in the same file. Doesn't this solve your problem?

**Comment by gabrielhdt** [comment]
Another way to solve this is to reset the flags after each compilation, using commands in `Console`.

**Comment by fblanqui** [comment]
Or rather at the beginning of each file. Good idea.

**Comment by ejgallego** [comment]
Even better would be if you would make the top-level interface purely functional so flags have to be specified in each call.

**Comment by Rehan-MALAK** [comment]
My point was to warn a lambda(pi) user that he/she should not be surprised if ``make tests`` has erratic behaviours since #449 because of a debug flag or something else.

@gabrielhdt @ejgallego I don't understand your solution, you want to go from this

```ocaml
let rec infer : ctxt -> term -> term = fun ctx t
```

to this :

```ocaml
let rec infer : ?options -> ctxt -> term -> term =
  fun ?(options:options) ctx t
```

in dozens and dozens of functions in lambdapi ?

**Comment by gabrielhdt** [comment]
I'm not certain on how to implement this, but I guess it would happen at a higher level.

**Comment by francoisthire** [comment]
As @gabrielhdt pointed me out, This could be solved via the `Processors` implemented in Dedukti 2.7 : 

> https://github.com/Deducteam/Dedukti/blob/master/api/processor.mli

Processors give a high-level way to `process` Dedukti files. The interface is not pure because of `Env.t`. 

Environment is needed for example to keep in memory reductions rules and types of values defined in another module. In the Lambdapi case, the environment has to remember some parsing stuff I guess.

Processor interface could ease the development of interoperability tool also because they give IMHO a nice API to process files.

**Comment by ejgallego** [comment]
> @gabrielhdt @ejgallego I don't understand your solution, you want to go from this
> 
> ```ocaml
> let rec infer : ctxt -> term -> term = fun ctx t
> ```
> 
> to this :
> 
> ```ocaml
> let rec infer : ?options -> ctxt -> term -> term =
>   fun ?(options:options) ctx t
> ```
> 
> in dozens and dozens of functions in lambdapi ?

Just do it in the entry points, then set the proper references there.

**Comment by ejgallego** [comment]
> Just do it in the entry points, then set the proper references there.

But in general, for flags really affecting type-checking, it is much better to pass them functionally; otherwise multithreading / incremental TC will be pretty much not robust.

**Comment by Rehan-MALAK** [comment]
I am talking about debug flags (log function) and they are lots of entry points.

**Comment by ejgallego** [comment]
> I am talking about debug flags (log function) and they are lots of entry points.

Debug flags can be set in the entry points, but it is still good to expose them functionally in the API, so you do:

```ocaml
let entry_point ?flags =
   let old_flags = current_flags in
   current_flags := flags;
   ....
   current_flags := old_flags
```
with the proper error handling etc...

**Comment by Rehan-MALAK** [comment]
I am giving up with this conversation.

**Comment by ejgallego** [comment]
> I am giving up with this conversation.

The problem is still there tho, right?

**Comment by ejgallego** [comment]
Just note that what I call "entry point" , there are only 2/3 in the code; for example in the LSP server here is only one, `initial_state`

**Comment by Rehan-MALAK** [comment]
I just realized that meta variable counter is not reset too. I hope we have no algorithm using it. There are probably other side-effects we haven't thought about.

**Comment by ejgallego** [comment]
Oh, indeed the meta counter is a very interesting example once you start delegating proofs; imagine you have two heaps, how do you consider meta equality? This is a big pain point in Coq's proof delegation [I can provide more details if anyone is interested]

Going back on topic, I would propose to solve this by doing small changes pushing "functional" entry points to the places needed, sorry if my proposal was understood as a large-scope change.

For example in this setting fixing `compile` should be enough.

**Comment by gabrielhdt** [comment]
@ejgallego are you thinking of something of the kind (the module `Pure`)
https://github.com/gabrielhdt/lambdapi/blob/e7393db6c48bacdf4760f170180254a041a6ae81/src/core/compile.ml#L124
?
For some reason though, it doesn't work...

**Comment by ejgallego** [comment]
@gabrielhdt , yup something like that, let's have the users of that top-level function specify the flags as a parameter and set / restore them there ; should also help with handling of cmd line args, etc...

@Rehan-MALAK you seemed reluctant to this solution , would that be a problem for you?
