### ISSUE TITLE
regression bug with emacs lsp mode

### ISSUE THREAD

**Issue by Rehan-MALAK** [Deducteam/lambdapi#451]
it seems that tests/OK/unif_hint.lp (unification hint via ``set unif_rule <patt> ≡ <patt> ↪ <term> ≡ <term>``) doesn't work anymore with emacs mode since #434

are you able to reproduce this or is it just me ?

**Comment by ejgallego** [comment]
Note that the server doesn't "freeze", it just errors on checking; we should tweak that; fix submitted.

**Comment by Rehan-MALAK** [comment]
Thanks !
