### ISSUE TITLE
Bug in unification rule scoping

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#455]
When scoping the RHS of a unification rule, underscores (and thus implicit arguments) should be substituted by fresh pattern variables.
The rationale is that a rule (including a unification rule) added in a signature must not contain any metavariable.

**Comment by gabrielhdt** [comment]
As discussed previously, we might have to change the scoping mode of RHSs of unification rules since we want this
https://github.com/Deducteam/lambdapi/blob/1068b496291dad5b0e9fed0522d6418e2023f410/src/core/scope.ml#L250
to happen, rather than this
https://github.com/Deducteam/lambdapi/blob/1068b496291dad5b0e9fed0522d6418e2023f410/src/core/scope.ml#L253

**Comment by Rehan-MALAK** [comment]
simplified tests/OK/unif_hint.lp to debug scoping
```
set verbose 3
set flag "print_implicits" on
symbol U: TYPE
symbol T: U → TYPE
constant symbol Pair: U → TYPE
constant symbol pair {t:U}:  T t → T t → Pair t
symbol fst {t:U}: Pair t → T t
set unif_rule fst $p ≡ $f ↪ $p ≡ pair $f $s
```

**Comment by gabrielhdt** [comment]
It seems to me that the best way to fix this issue would be check unification rules after they have been scoped, following the model of rewrite rules with SR. We will then be able to enrich this check with meaningful safety checks. The scoping algorithm is already complicated.

**Comment by fblanqui** [comment]
What would be the types of `#equiv` and `#cons` ?... The only thing we can do for a unif_rule l0=r0 --> l1=r1; ..; ln=rn is to check that the types of l0 and r0 unify, the types of l1 and r1 unify, etc. This is not the same treatment as standard rules.

**Comment by gabrielhdt** [comment]
Indeed it is not the same, we need to make a new one. When I said "following the model" I meant following the workflow, so we have pre unification rules transformed into unification rules.
We can also check that the variables `l1`, `l2`, ... are in `FV(l0) \cup FV(r0)`.

**Comment by fblanqui** [comment]
Not sure that you can do that in fact because, here, you need to convert a meta into a patt, possibly in some env!
It seems much much simpler to have a new scoping mode for unif_rule rhs's, say UR_RHS: there is only one case to add (P_Wild with UR_RHS).

**Comment by fblanqui** [comment]
In addition, why do you want to have "the variables l1, l2, ... are in FV(l0) \cup FV(r0)" ? It doesn't seem to be a problem to have extra variables in li. All these extra (pattern) variables are replaced by fresh metavariables anyway.

**Comment by gabrielhdt** [comment]
It's required for the correctness of unification hint.

**Comment by fblanqui** [comment]
Perhaps. But it is not urgent to check this. There are other properties we do not check ;-)
