### ISSUE TITLE
Bug in unification rule application

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#456]
Unification rules can contain in their RHS pattern variables that do not occur in the LHS. At rule application time, these extra pattern variables are replaced by fresh metavariables. Currently, those freshly created metavariables are declared of type KIND. This is incorrect. They should be of type yet another metavariable of type TYPE, like it is done in the scoping of underscores in terms.

**Comment by gabrielhdt** [comment]
This one is easy, it comes from
https://github.com/Deducteam/lambdapi/blob/1068b496291dad5b0e9fed0522d6418e2023f410/src/core/eval.ml#L221

**Comment by Rehan-MALAK** [comment]
sure ... but this is the part I have remove in the PR #454
because I'm not sure what we want to put here and how we want to do it
I used to do another inference in Unif.try_rule
and give the result to Eval.tree_walk

**Comment by gabrielhdt** [comment]
Don't we just want to create a new meta of type Type `mt` and do `make_meta [] mt`?

**Comment by Rehan-MALAK** [comment]
From what I remember, this is not what your pair/projection example in tests/OK/unif_hint.lp seemed to show 
One of the contraint generated by the additional inference in Unif.try_rule (the part I removed) showed that the meta should be a Nat.
If you put Type... you will have a constrain ``Nat ≡Type`` and if you put Kind... ``Nat≡Kind``

**Comment by fblanqui** [comment]
@Rehan-MALAK could you please add your example here for the record?

**Comment by Rehan-MALAK** [comment]
simplified tests/OK/unif_hint.lp until ``compute J``
```
set verbose 3
set flag "print_implicits" on
symbol U: TYPE
injective symbol T: U → TYPE
symbol Nat: TYPE
symbol n: Nat
symbol nat: U
rule T nat ↪ Nat
set unif_rule T $x ≡ Nat ↪ $x ≡ nat
constant symbol Pair: U → TYPE
constant symbol pair {t: U}:  T t → T t → Pair t
symbol fst {t:U}: Pair t → T t
set unif_rule fst $p ≡ $f ↪ $p ≡ pair $f $s
constant symbol K {t:U}: T t → TYPE
constant symbol J {t:U} (p: Pair t): K (fst p) → TYPE
constant symbol kn: K n
set flag "print_contexts" on
set flag "print_meta_type" on
set debug +ui
compute J (pair _ n) kn
```
