### ISSUE TITLE
Logging facilities: redundancy

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#460]
Is the `log_enabled` really useful? Loggers can be already be activated individually using the `enabled` field of `logger_data`. Removing it would reduce the number of shared references, and ease the work of #457.

**Comment by fblanqui** [comment]
ok

**Comment by gabrielhdt** [comment]
It appears to be a bad idea: it avoids computing the arguments of the the printing messages: considering a line such as
```ocaml
if !log_enabled then log_eval "bla bla bla %a" pp (computation)
```
we can remove `if !log_enabled then`: the result is the same because `log_eval` already outputs nothing is the logger attached to key 'e' (eval) is deactivated. But, the computations of `(computation)` are performed. The slowdown is significant: `make holide` goes from 4min to 10min.

**Comment by fblanqui** [comment]
Ah right, I remember now!
