### ISSUE TITLE
Right dependencies for make tests ?

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#461]
After merging #454, I recompiled LP and run make tests but it didn't do all the tests again. There seems to be something wrong.

**Comment by gabrielhdt** [comment]
Dune performs a form of caching, try again with a `make clean`

**Comment by ejgallego** [comment]
> Dune performs a form of caching, try again with a `make clean`. I'm not sure on how it works.

Indeed dune rules will only run if the dependencies have been updated, so it could be a problem on the rules being used for tests.
