### ISSUE TITLE
Migrate continuous integration

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#478]
Some problem arise from the use of Travis (see #473). It seems we should change the continuous integration system. The alternatives seem to be either github actions, or an inria based ci.

**Comment by ejgallego** [comment]
Github actions should be pretty easy to set up, an example with ocaml can be found here: https://github.com/ocaml/dune/blob/master/.github/workflows/workflow.yml

**Comment by fblanqui** [comment]
When I click on details concerning CI, I get directed to travis-ci.org which prints the following message: "Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information." This means that our current CI won't work in a few weeks anyway. We have to do something quickly anyway.

**Comment by ejgallego** [comment]
That's no super-critical, when the accounts migrate the main problem is that the amount of CI minutes is limited to around 1000 per month unless some request is done; but I do agree that migrating to GitHub actions is easy enough as to do it quick.
