### ISSUE TITLE
Documentation of parser level symbols

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#482]
Pull request #422 changes the arguments of `P_symbol`, but the different elements of the tuple aren't documented:
```ocaml
  | P_symbol     of p_modifier loc list * p_statement * p_term option
                    * (p_tactic list * p_proof_end loc) option
                    * Terms.proof_meaning
```
As a side note, a inlined record may be used.

The same goes for `p_statement`,
```ocaml
type p_statement = (ident * p_arg list * p_term option) loc
```

It would be nice to have a description of what ends where considering a declaration
```
symbol foo (x: T): U := u
begin
 ...
end
```

**Comment by fblanqui** [comment]
I am working on this. I will do a PR soon. Concerning `symbol foo(x:T):U := u begin ... end`, this should be discussed in https://github.com/Deducteam/lambdapi/issues/483.

**Comment by fblanqui** [comment]
See https://github.com/Deducteam/lambdapi/pull/485

**Comment by gabrielhdt** [comment]
Thanks @fblanqui!
