### ISSUE TITLE
Documentation of new commands and syntax

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#483]
The documentation haven't been changed after the modifications of #422, so the syntax for symbol declaration isn't documented, and the section about `definition` and `theorem` ought to be removed, if I'm correct.

**Comment by fblanqui** [comment]
Right, I missed this. Here are the modifications:
- definition -> symbol
- theorem -> opaque symbol
- proof -> begin
- qed -> end
I am going to do a PR fixing the doc.

**Comment by fblanqui** [comment]
Btw, https://lambdapi.readthedocs.io has not been updated by the last commits. It's not automatic? What do we have to do to update this site?

**Comment by amelieled** [comment]
Same for `syntax.bnf` (inductive type too).

**Comment by gabrielhdt** [comment]
> Btw, https://lambdapi.readthedocs.io has not been updated by the last commits. It's not automatic? What do we have to do to update this site?

it should be automatic

**Comment by fblanqui** [comment]
Ok. Any remark on https://github.com/Deducteam/lambdapi/pull/484 ?

**Comment by amelieled** [comment]
No, it's correct I think.
But you can add a comment about the tactic `proofterm`?

**Comment by fblanqui** [comment]
I completed the doc on symbols and tactics. @gabrielhdt does it answer your questions?

**Comment by gabrielhdt** [comment]
> I completed the doc on symbols and tactics. @gabrielhdt does it answer your questions?

Could you describe the elements of the tuple that makes a `P_symbol`? Just as comments in the type declaration.

**Comment by fblanqui** [comment]
Fixed in https://github.com/Deducteam/lambdapi/pull/484
