### ISSUE TITLE
Emacs interface: a goal buffer is open each time a file is open

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#486]
There should be only one goal buffer whatever the number of open files.

**Comment by fblanqui** [comment]
There is only one buffer but several windows.
![Capture d’écran_2020-12-16_16-18-28](https://user-images.githubusercontent.com/10852505/102368019-b058ab00-3fba-11eb-8be8-9adb6c20c433.png)

**Comment by fblanqui** [comment]
Note also that the initial size of the goal buffer is too small. Rehan put the goal buffer on the right side to do like in VSCode but it is not convenient in emacs. I think that we should revert this change and put the goal buffer at the bottom of the Emacs window.

**Comment by fblanqui** [comment]
https://github.com/Deducteam/lambdapi/pull/422/files#diff-843135d822086ec90107e11c9c2d8cf8f353e040bf8481969c8d789a2badc95f

**Comment by Rehan-MALAK** [comment]
if there is only one goal buffer opened each time, I find vertical split better on our 16:9 screen

would be better to let the user choose

**Comment by fblanqui** [comment]
Right. @firewall2142 would it be possible to dynamically change the organization of the windows or at least let the user set some variable to choose which one he prefers?
Anyway, `(goalswindow (split-window nil -10 'below)))` is probably fine but `(goalswindow (split-window nil -10 'right)))` is not: -10 for a vertical window is not enough.
Btw, what is the unit of this -10? Is it a number of columns? Wouldn't it be better to use a percentage of the window size?

**Comment by firewall2142** [comment]
> would it be possible to dynamically change the organization of the windows or at least let the user set some variable to choose which one he prefers?

> Wouldn't it be better to use a percentage of the window size?

Sure, I remember Proof General had such a feature too. I will implement it in PR #472 .

> Btw, what is the unit of this -10? Is it a number of columns?

Yes. Negative opens a new window. So to fix this issue, i guess we just need to remove negative sign.
