### ISSUE TITLE
Emacs/VSCode: navigation in files command-by-command

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#515]
Currently navigation is done line by line, which is incorrect when a command spreads out on several lines (e.g. inductive/rule ... with ...). Navigation should be command by command. Note that there may be several commands on the same line as well. Perhaps the introduction of a command terminator ";" in the new parser will make things easier.

**Comment by ejgallego** [comment]
Shouldn't matter too much, the lsp server already can map a position to the concrete sentence, so you could just call lp to obtain sentence information.
