### ISSUE TITLE
Problem for parsing module names containing dash

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#520]
With `require file-1`, we get the error:
```
[/home/blanqui/src/lambdapi/tmp/bug.lp, 1:0-17] Error when loading module [file].
File [/home/blanqui/.opam/4.11.1/lib/lambdapi/lib_root/file.{lp|dk}] not found.
```
The filename is truncated.
If the filename is not a valid name, then an error should be raised.

**Comment by gabrielhdt** [comment]
Honestly I wonder whether we should just limit the module names to non keywords, ascii characters, it would ease many things, and allow us to focus on more interesting problems, and leverage the maintenance of the code.

**Comment by fblanqui** [comment]
After #516, the error message is now:
```
[file-2.lp, 1:8-14] Unexpected token [file-1].
```
I don't understand why the string "file-1" is not recognized as an identifier. @gabrielhdt do you have any idea?

**Comment by gabrielhdt** [comment]
Could you please post the content of your files?

**Comment by fblanqui** [comment]
file-1 is empty and file-2 only contains "require file-1;"

**Comment by gabrielhdt** [comment]
Aren't you supposed to prefix `file-1` by its package?

**Comment by fblanqui** [comment]
Ah right!

**Comment by fblanqui** [comment]
@gabrielhdt Can't Menhir provide some data on what are the expected tokens so as to provide a more informative error message?

**Comment by gabrielhdt** [comment]
Indeed it would be interesting, I'm not sure, but we may have a look at the incremental parsing api which allows to have very friendly error messages, <https://baturin.org/blog/declarative-parse-error-reporting-with-menhir/>
