### ISSUE TITLE
Doc: wrong link to syntax.bnf

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#538]
Currently, syntax.bnf refers to file:///home/blanqui/lambdapi/docs/_build/html/_downloads/be42b307be1296d41b9f4511c3543941/syntax.bnf which does not correspond to the current version. Why not simply put a link to https://raw.githubusercontent.com/Deducteam/lambdapi/master/docs/syntax.bnf ?

**Comment by amelieled** [comment]
In which file you see this?

The folder `_build` is a temporary one, so if you want the lastest version of `syntax.bnf`, you just need to synchronize your remote with the Deducteam one and run `make doc` or `make docs` I don't know. Right?

**Comment by fblanqui** [comment]
Ah, my mistake. Anyway, a link would be better than a download.

**Comment by amelieled** [comment]
Where you would like to put this link? It's not clear.

**Comment by fblanqui** [comment]
All links to syntax.bnf in docs/

**Comment by fblanqui** [comment]
In addition, shouldn't syntax_dedukti.bnf be re-generated as well?

**Comment by fblanqui** [comment]
Fixed in #541 (except syntax_dedukti.bnf).
