### ISSUE TITLE
The dk lexer and parser need to be updated

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#545]
And, to help comparison and maintenance, dkLexer.mll and dkParser.mly should be as closed as possible to their Dedukti counterparts:
https://github.com/Deducteam/Dedukti/blob/master/parsing/lexer.mll
https://github.com/Deducteam/Dedukti/blob/master/parsing/menhir_parser.mly
Note in particular that, compared to the master branch of Dedukti, some tokens are missing: `#NAME`, `#CHECK`, `#CHECKNOT`, `#PRINT`, `#GDT`, `defac` and `defacu`. @francoisthire what is `#GDT`?

**Comment by francoisthire** [comment]
`#GDT` was a debugging command to print the decision tree of some symbol.
