### ISSUE TITLE
Issue with PrintC.lp

### ISSUE THREAD

**Issue by amelieled** [Deducteam/lambdapi#548]
As you can see on the PR #492 , a previous test file, named `PrintC.lp` and deleted by error, doesn't work at the moment:
```
require tests.OK.PrintA as A;
compute tests.OK.PrintA.f; // should print A.f
compute A.f; // should print A.f
assert ⊢ tests.OK.PrintA.f ≡ A.f;
```
Only the last line doesn't work.

**Comment by fblanqui** [comment]
I don't understand. LP succeeds on tests/OK/PrintC.lp...
```
19:25 ~/src/lambdapi (master) lp tests/OK/PrintC.lp 
(comp) a + a           
(comp) a + a
(asrt) it is true that a + a ≡ a + a
Checked /home/blanqui/src/lambdapi/tests/OK/PrintA.lp
(comp) A.f
(comp) A.f
(asrt) it is true that A.f ≡ A.f
Checked /home/blanqui/src/lambdapi/tests/OK/PrintC.lp
```

**Comment by amelieled** [comment]
Ah yes sorry the file `PrintC.lp` is on the current repository.
Thanks, now the problem on #492 is fixed, but be careful because some tests files were deleted recently (there are on #492 so).
