### ISSUE TITLE
p_command.pos has line numbers always 0

### ISSUE THREAD

**Issue by firewall2142** [Deducteam/lambdapi#549]
`p_command.pos` has line numbers always 0

**Comment by gabrielhdt** [comment]
Hi @firewall2142, could you please provide some steps to reproduce the issue, or attest it?

**Comment by fblanqui** [comment]
But is the column number changing?

**Comment by amelieled** [comment]
I think it's related to my problem too : only the first line can be red or green.
So the errors aren't readable because if you have a problem on line 10, for instance, a part of the line 1 is red.

**Comment by ejgallego** [comment]
I have reproduced the problem [using #550 ]

```ocaml
  [[tests/OK/apply.lp, 0:0-25] constant symbol A : TYPE;;
   [tests/OK/apply.lp, 0:0-27] constant symbol Nat : TYPE;;
   [tests/OK/apply.lp, 0:0-27] constant symbol zero : Nat;;
   [tests/OK/apply.lp, 0:0-33] constant symbol succ : Nat → Nat;;
   [1:0-0:30] symbol plus : Nat → Nat → Nat;;
   [tests/OK/apply.lp, 0:0-28] rule plus zero $m ↪ $m;;
   [tests/OK/apply.lp, 0:0-43] rule plus (succ $n) $m ↪ succ (plus $n $m);;
   [tests/OK/apply.lp, 0:0-33] constant symbol Vec : Nat → TYPE;;
   [tests/OK/apply.lp, 0:0-31] constant symbol nil : Vec zero;;
   [tests/OK/apply.lp, 0:0-58] constant symbol cns : Π (n : Nat), A → Vec n → Vec (succ n);]
```
Something is resetting the position to zero at each call [maybe some incorrect lambda-lifting] or newlines are not handled properly.

**Comment by fblanqui** [comment]
Thank you very much @ejgallego !

Yes, I am wondering if it's not related to the fact that the new lexer doesn't use Sedlexing.new_line. But that's kind of strange because file parsing works well without that. But the LSP server uses string parsing instead of file parsing. Perhaps Sedlex automatically handle new lines in file parsing but not in string parsing?...

Anyway, there is something strange in the line `[1:0-0:30] symbol plus : Nat → Nat → Nat;;` which is different from the others: no filename and an invalid range (origine > destination).

**Comment by ejgallego** [comment]
> I see also that a semi-colon is added at the end of each command except the last one, but it's probably just because a List.pp ";" is used.

Yes, this is due to being in the toplevel, it has a printer for lists that inserts `;` automatically, the printer for commands is the one installed with the attribute in the mli.

Indeed the missing file is bizarre ....

**Comment by ejgallego** [comment]
Let me see for file parsing tho.

**Comment by ejgallego** [comment]
For file parsing, it works. It turns out sedlex is just buggy, when called from `from_string` it will setup the initial buffer incorrectly, with current line = 0, then this code triggers:
```ocaml
let new_line lexbuf =
  if lexbuf.curr_line != 0 then
  lexbuf.curr_line <- lexbuf.curr_line + 1;
  lexbuf.curr_bol <- lexbuf.pos + lexbuf.offset
```

that's pretty worrying as even a basic unit test should have caught this.
