### ISSUE TITLE
Wrong position given by the parser

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#553]
In the example given https://github.com/Deducteam/lambdapi/pull/550, the position computed by the parser for the command `symbol plus : Nat → Nat → Nat;` is wrong. A bug in menhir to report upstream?
Anyway, we need to fix it. A solution could be to recompute the right position ourselves from the position of the first modifier to the position of the semi-colon. @gabrielhdt could you please have a look at this?

**Comment by gabrielhdt** [comment]
This is likely related to <http://gallium.inria.fr/~fpottier/menhir/manual.html#sec50> and we should use `($symbolstartpos, $endpos)` rather than `$loc` which stands for `($startpos, $endpos)` in the rule for symbols.

**Comment by fblanqui** [comment]
Remark: you can now get command positions by using `--debug +h`.

**Comment by fblanqui** [comment]
Thanks @gabrielhdt . It works indeed. I am going to fix master.
