### ISSUE TITLE
Performance slowdown with variable shadowing

### ISSUE THREAD

**Issue by QGarchery** [Deducteam/lambdapi#565]
A recent commit seems to make Lambdapi slower on some inputs. To show this, since the syntax changed recently, I show tests realized on the same example but with appropriate syntax for each considered commit. 
The files are given with the `.txt` extension (so that I can upload them), to test it yourself you should rename them with the `.lp` extension.
- test 1, December 11 commit 402e9dfe90c3bad6e6ab6dbcd328e071c943ac06, example file [syntax1.txt](https://github.com/Deducteam/lambdapi/files/5981481/syntax1.txt)
- test 2, December 15 commit 8a09f7ee239a12b790478f6f9f35551c45e15084, example file [syntax2.txt](https://github.com/Deducteam/lambdapi/files/5981491/syntax2.txt)
- test 3, current commit, example file [syntax3.txt](https://github.com/Deducteam/lambdapi/files/5981494/syntax3.txt)

The example files use the (adapted) Lambdapi encoding of the first order logic found in `tests/OK/firstOrder.dk`.

On my machine, on test 1, checking with Lambapi terminates in about 0.05s.
On test 2 and 3, it takes approximately 10 seconds to terminate. If you comment the lines 43-64 (and 66), time comes down to 0.05s again. It seems like every variable shadowing we add (adding a line like the line 43) doubles the time taken by Lambdapi.

Note that the example has been simplified for concision sake. In practice, the performance problem comes with far less 'useless' added terms, and finding what to remove to make Lambdapi finish in reasonable time is not always possible.

**Comment by fblanqui** [comment]
Thank you very much @QGarchery for reporting this issue. It should now be fixed.

**Comment by QGarchery** [comment]
Thank you for the very fast fix !
