### ISSUE TITLE
Performance with growing context

### ISSUE THREAD

**Issue by QGarchery** [Deducteam/lambdapi#579]
I have experienced performances to be very much impacted when the context grows in a theorem and its proof. I show a simplfied example where the same hypothesis is added 20 times to the context. In reality, when a different hypothesis is added, the problem arrives much faster.

The files are given with the .txt extension (so that I can upload them), to test it yourself you should rename them with the .lp extension. The example files use the (adapted) Lambdapi encoding of the first order logic found in `tests/OK/firstOrder.dk`.

On my machine, on file [or_elim_fast.txt](https://github.com/Deducteam/lambdapi/files/6012436/or_elim_fast.txt), checking with Lambapi terminates in about 0.05s.
On file [or_elim_long_2.txt](https://github.com/Deducteam/lambdapi/files/6012437/or_elim_long_2.txt), where we add the same hypothesis 20 times,  it takes approximately 13 seconds to terminate. 

It seems to me that this problem did not occur in my project in a previous version of Lambdapi, about a year ago. I did not manage to check because I don't know how to compile older versions anymore (before mid 2020).

**Comment by fblanqui** [comment]
Thanks @QGarchery for your report. I'll try to have a look at it this week.

**Comment by fblanqui** [comment]
The problem seems to come from the fact that, when computing unification constraints, we try not to duplicate them. If we do not do that, your second file is checked in 0,136s instead of 11s. However, if we do not do that, then the resolution of unification constraints is slowed down: make tests takes 42s instead of 12s.

**Comment by QGarchery** [comment]
Thank you for looking into it ! 

I'm a bit surprised because I found in testing that having duplicates actually speeds up the type checking.
The example [long_no_duplicate.txt](https://github.com/Deducteam/lambdapi/files/6070468/long_no_duplicate.txt) where we distinguish the 20 `b` into `b1` ... `b20` takes about 50 seconds to type check for me.

But maybe I'm not talking about the same duplicates ?

**Comment by fblanqui** [comment]
No, we are not talking about the same duplicates. With the fix I suggested, it takes only 0,216s. But before changing this, I need to understand why it increases the time in other files...

**Comment by fblanqui** [comment]
@QGarchery you can try https://github.com/Deducteam/lambdapi/pull/583/commits/e1735cffb93dcf0bc512e1d5a3dc7d37165ba576
