### ISSUE TITLE
Induction tactic and inductive symbols

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#580]
The last proof named `length_app` of `inductive.lp` fails on the branch `refiner` with the error message `τ is not an inductive type` on line 720.

This happens because the inductive symbol that is stored in `sign_ind` is `List`, but there is a reduction rule `rule List ↪ τ list;` and hence the function `ind_data` looks whether `τ list` is an inductive type, which is not the case because only `List` is in `sign_ind`, and symbols are not compared up to convertibility. I'm not completely sure, but I think that there is no error on the master branch because the type checker is not bidirectional.

One solution would be to use an association list rather than a `SymMap` for `sign_ind`, and using `assoc_eq` with the convertibility relation as equality.

**Comment by fblanqui** [comment]
Perhaps. But this is kind of wrong to add a rule on an inductive type. This is currently allowed for some bad reason and should be fixed. Inductive types should be "constant". Hence, you should write your rule in the other way and, perhaps, add some unification rule too. Could you please tell me if it works if you do this?

**Comment by gabrielhdt** [comment]
Right, I fully agree with your point. But in `inductive.lp`, we have the rule `List -> \tau list` with `List` being an inductive. It works when we reverse the rule, indeed.

**Comment by fblanqui** [comment]
See https://github.com/Deducteam/lambdapi/pull/583
