### ISSUE TITLE
Performances with nested applications in context

### ISSUE THREAD

**Issue by QGarchery** [Deducteam/lambdapi#584]
In some cases, performances seem to be drastically impacted when having nested applications, even if they are trivial.

I give an example of this using  the first order logic encoding found in `firstOrder.dk`. The files are given with the `.txt` extension (so that I can upload them), to test it yourself you should rename them with the `.lp` extension. 

Checking [c_fast.txt](https://github.com/Deducteam/lambdapi/files/6078070/c_fast.txt) takes about 0.1s on my machine.
In example [c_slow.txt](https://github.com/Deducteam/lambdapi/files/6078062/c_slow.txt) where we added an abstraction for each symbol but immediately applied to the symbol in question, checking takes approximately 17 seconds.

It could seem like its OK because there is just more work to do (although I would argue not very much?). In reality, as for #579, this issue comes from a 'recent' update and I did not experience such a slowdown before.

**Comment by fblanqui** [comment]
This slow download has been introduced by the last commit...

**Comment by QGarchery** [comment]
This fixes most of my use cases, thank you ! I will try to find what is wrong with the rest as soon as possible.
