### ISSUE TITLE
Performances with both new variables and hypotheses in context

### ISSUE THREAD

**Issue by QGarchery** [Deducteam/lambdapi#595]
In some cases, performances seem to be impacted when adding new variable names, even if those variables are unused.

I give an example of this using the first order logic encoding found in `tests/OK/firstOrder.dk`. The file is given with the `.txt` extension (so that I can upload it), to test it yourself you should rename it with the `.lp` extension.

Checking [and_elim.txt](https://github.com/Deducteam/lambdapi/files/6109630/and_elim.txt) takes about 0.5s on my machine.
Uncommenting the commented lines in this examples effectively introduces 20 fresh, unused variables. Checking time then goes up to approximately 12 seconds.

**Comment by QGarchery** [comment]
Awesome ! It has never been that fast on all of my use cases !

**Comment by fblanqui** [comment]
Cool :+1:
