### ISSUE TITLE
Installation fails with opam 2

### ISSUE THREAD

**Issue by dwarfmaster** [Deducteam/lambdapi#609]
When trying to install lambdapi using a recent version of opam, it fails when trying to install the vim syntax files, because since version 2 opam sandboxes the installation process to make sure the installer cannot install things outside of the `.opam` directory.

To fix this, I would remove both the `make install_vim` and `make install_emacs` from the opam target, or at least mention that it is expected to fail when installing with opam 2.

**Comment by fblanqui** [comment]
Thanks Luc for your report. Which version of LP did you try to install with opam?

**Comment by fblanqui** [comment]
@gabrielhdt related to #495 ?

**Comment by dwarfmaster** [comment]
> Thanks Luc for your report. Which version of LP did you try to install with opam?
```shell
$ lambdapi --version
bcbe1929
```
From my understanding it is the hash of the git commit. To be able to install it, I had to clone this repo and edit the opam file, so the corresponding commit here would be `121e5238`.

**Comment by dwarfmaster** [comment]
I just looked at #495, and it should fix the issues since it installs the vim files in the `.opam` directory and not directly in the home user. I checked and `opam pin add lambdapi https://github.com/gabrielhdt/lambdapi.git#auto-opam` succeeds indeed.

**Comment by dwarfmaster** [comment]
Fixed with the merging of #495.
