### ISSUE TITLE
lambdapi init creates a project that doesn't work

### ISSUE THREAD

**Issue by dwarfmaster** [Deducteam/lambdapi#610]
When creating a project using `lambdapi init my_module`, the generated file `lambdapi.pkg` is empty, while it expects to contain at least the `package_name` and `root_path` attributes. Furthermore, the example lambdapi files are out of date (I guess), since their syntax is not valid, and I had to update them to get `make` to work.

Testing that the project generated by `lambdapi init` works with the current version of lambdapi should probably be part of some test suit.

**Comment by fblanqui** [comment]
Again, which version of LP are you using here? Thanks to always indicate this in your bug reports.

**Comment by fblanqui** [comment]
Anyway, I am not surprised because we changed the syntax but didn't update the init command code accordingly. I am going to fix this.

**Comment by fblanqui** [comment]
Fix in #611 .
