### ISSUE TITLE
Problem with id : {|00|} becomes {|0|}

### ISSUE THREAD

**Issue by yannl35133** [Deducteam/lambdapi#621]
As far as I'm concerned, surrounding characters around `{|` and `|}` treats it as a well-escaped immutable string.

However, this checks badly:
```dedukti
symbol Typ : TYPE;
symbol eta : Typ → TYPE;

symbol id {|00|} (Hb: eta {|0|}) ≔ Hb;

symbol id2 {|00|} (Hb: eta {|00|}) ≔ Hb;
```

`{|00|}` becomes `{|0|}`.
This also happens when the number is prefixed by something (in my case, `{|:000|}` becomes `{|:0|}`)

**Comment by fblanqui** [comment]
Hi. I suspect that it is a problem with Bindlib. I am afraid that the only solution for the moment is to forbid escaped identifiers for bound variables.

**Comment by gabrielhdt** [comment]
It must happen when an integer is used as suffix of a variable name. We may perform a sanity check while scoping.
