### ISSUE TITLE
The parser always expects type annotations for the first argument in lambdas

### ISSUE THREAD

**Issue by dwarfmaster** [Deducteam/lambdapi#631]
When writing a lambda, the parser fails with `Unexpected token [,]` when the first argument of the lambda has no type annotation. This behaviour only concerns the first variable :
```lambdapi
constant symbol T : TYPE;

symbol const1 : T → TYPE ≔ λ(x : T), T; // Succeeds
symbol const2 : T → TYPE ≔ λ(_ : T), T; // Succeeds
symbol const3 : T → TYPE ≔ λ(_ : _), T; // Succeeds
symbol const4 : T → TYPE ≔ λ_, T;       // Fails

symbol const1' : T → T → TYPE ≔ λ(x : T) _, T; // Succeeds
symbol const2' : T → T → TYPE ≔ λ(_ : T) _, T; // Succeeds
symbol const3' : T → T → TYPE ≔ λ(_ : _) _, T; // Succeeds
symbol const4' : T → T → TYPE ≔ λ_ _, T;       // Fails
```

In the manual, the only example for a lambda indeed has a type annotation, but the formulation is such that it doesn't seem mandatory, so if it isn't a bug I would advise updating the manual.

```shell
$ lambdapi --version
e4509ffd
```

**Comment by dwarfmaster** [comment]
My mistake, the error is actually that the parser expects a space after the `λ` (probably because it is parsed as only one token), but the parenthesis split the token.

**Comment by gabrielhdt** [comment]
For now, `λ` is allowed in identifiers, so `λ_` is a valid identifier, and not a binder opener. What we can do is forbid `λ` in identifiers, which would parse `λ_, t` as a correct binder. The same goes for products.

**Comment by dwarfmaster** [comment]
Yeah it totally makes sense. I guess I'm not used yet to utf8 in identifiers.
