### ISSUE TITLE
Conditions to add rewriting rule on an ac symbol

### ISSUE THREAD

**Issue by Thiagofelis** [Deducteam/lambdapi#642]
I'm trying to understand what I'm allowed and not allowed to do with this new functionality. If I have
```
constant symbol nat : TYPE;
symbol zero : nat;
symbol succ : nat → nat;
associative commutative symbol + : nat → nat → nat;
rule + (succ $x) zero ↪ succ $x;
rule + zero zero ↪ zero;
```
then everything goes well. However, if I try to typecheck 
```
constant symbol nat : TYPE;
symbol zero : nat;
symbol succ : nat → nat;
associative commutative symbol +: nat → nat → nat;
rule + $x zero ↪ $x;
```
I get the error Uncaught exception: (Invalid_argument "Core__Term.cmp_term: File \"src/core/term.ml\", line 463, characters 41-48"). What are the conditions for adding a rewriting rule on an ac symbol? My version of lambdapi is 9dc51052

**Comment by fblanqui** [comment]
Thanks Thiago for the report! This is a bug in the total comparison function Term.cmp_term on terms which is incomplete. I am going to try to fix it. Otherwise there is no restriction currently for using those symbols in rules.
