### ISSUE TITLE
Error appears when .lpo is generated

### ISSUE THREAD

**Issue by Thiagofelis** [Deducteam/lambdapi#646]
I'm having the following error. If I do `lambdapi check test.lp` inside the root directory of the package attached, it typechecks normally. However, if I generate the .lpo of ac.lp by doing `lambdapi check -c ac.lp` and then do `lambdapi check test.lp` then now the assertion fails. Note that the error disappears when removing the associative commutative prefix of the symbol Union. My version is 058c1c58

[acerror2.zip](https://github.com/Deducteam/lambdapi/files/6312670/acerror2.zip)

**Comment by fblanqui** [comment]
Thanks for reporting this issue Thiago. #647 should fix it.
