### ISSUE TITLE
[FEATURE REQUEST] A syntax to distinguish a notation and its underlying value

### ISSUE THREAD

**Issue by yannl35133** [Deducteam/lambdapi#657]
Having
```lambdapi
constant symbol Int: TYPE;
constant symbol + : Int → Int → Int;
notation + infix left 6;
constant notation - : Int → Int;
notation - prefix 7;
```
I'd like to have access to `(+)` and `(-)` without a λ-abstraction.
Another solution could be to define `plus` and then assign `notation + [...] infix left 6 ≔ plus;`

**Comment by QGarchery** [comment]
If you are not worried about implicit arguments, you can use the `@` notation:

```
constant symbol Int: TYPE;
constant symbol + : Int → Int → Int;
notation + infix left 6;

symbol zero : Int;
symbol fortytwo : Int;
symbol iter (_n : Int) (_f : Int → Int) (_acc : Int) : Int;

symbol some_unknown_int ≔ @+ zero fortytwo;

symbol mul (m n : Int) ≔ iter n (@+ m) zero;
```

**Comment by yannl35133** [comment]
I'd take it for now, but there are some irregularities which makes it unusable for me now: [see this example](https://github.com/Deducteam/lambdapi/issues/655#issuecomment-830160727)

**Comment by fblanqui** [comment]
This was a duplicate of #359.
