### ISSUE TITLE
Problem with rewrite left

### ISSUE THREAD

**Issue by QGarchery** [Deducteam/lambdapi#669]
Contrary to the rewriting from left to right, the rewriting from right to left does not try to instantiate the given term to find a proper equality : 

```
require open Stdlib.Set Stdlib.Prop Stdlib.Eq Stdlib.Nat;

symbol test_assoc a b c : π (a + (b + c) = c + (a + b))
≔ begin
  assume a b c;
  rewrite left add_assoc a b c;
  // rewriting from right to left forces us to give a, b and c
  rewrite add_com;
  // rewriting from left to right does not require this
  reflexivity;
end;
```

Feature wish: automatically find how to instantiate the given term when rewriting from right to left, as for rewriting from left to right.

**Comment by fblanqui** [comment]
This is a bug.
