### ISSUE TITLE
Wrong comment or wrong function

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#685]
If I'm not mistaken, the function `add_unif_rule_constr` does not do what the comment says, the constraint `(c, t, u)` is not added to the problem.
https://github.com/Deducteam/lambdapi/blob/4d12e7dd4c26bc5dd7594fc519bdbcf36b02e2ed/src/core/unif.ml#L32

**Comment by fblanqui** [comment]
Right. This seems to explain the issue #683 .

**Comment by fblanqui** [comment]
Fixed in #688 .
