### ISSUE TITLE
Anonymous functions cannot take in implicit arguments

### ISSUE THREAD

**Issue by yannl35133** [Deducteam/lambdapi#698]
Currently, anonymous functions cannot take in implicit arguments : wrapping an argument in curly braces will have no effect and giving an explicit argument will raise an error

**Comment by fblanqui** [comment]
The goal is to handle the following example:
```
constant symbol Set:TYPE;
constant symbol nat:Set;

injective symbol τ:Set → TYPE;
constant symbol z:τ nat;

symbol f a:τ a → τ a;

type (λ {a}, λ x, f a x) z;
type (λ {a}, λ x, f a x) {nat} z;
```
