### ISSUE TITLE
Require/Open and long name

### ISSUE THREAD

**Issue by amelieled** [Deducteam/lambdapi#705]
C.lp:
```
symbol c : TYPE;
```
B.lp:
```
require open tests.C;
symbol b1 : c;
symbol b2 : tests.C.c;
```

A.lp:
```
require open tests.B;
open tests.C;

symbol a1 : c;
symbol a2 : tests.C.c; // doesn't work because the module tests.C isn't required
```

**Comment by gabrielhdt** [comment]
IINM, this is normal behaviour, `require` is not transitive. On the other hand, it should fail on `open tests.C` shouldn't it?

**Comment by amelieled** [comment]
> On the other hand, it should fail on ``open tests.C`` shouldn't it?
I don't know, but if I delete it, the two last lines don't work.

**Comment by amelieled** [comment]
> On the other hand, it should fail on ``open tests.C`` shouldn't it?

I don't know, but if I delete it, the two last lines don't work.

**Comment by amelieled** [comment]
More precisely:

C.lp:
```
symbol c : TYPE;
```
B.lp:
```
require open tests.C;
symbol b1 : c;
symbol b2 : tests.C.c;
```

A.lp:
```
require open tests.B;

symbol a1 : c; // doesn't work
symbol a2 : tests.C.c; // doesn't work
```

**Comment by fblanqui** [comment]
That's normal. As mentioned by Gabriel, the problem is that the open should fail.

**Comment by amelieled** [comment]
OK, thanks for the clarification.
Could you detail the semantics of these commands in the documentation, please?

**Comment by amelieled** [comment]
Moreover, I can open another issue as "feature request" about the possibility to export symbols.
Indeed, with the command `open`, you can import symbols, but not export them.

**Comment by fblanqui** [comment]
No, there is already an issue about this.

**Comment by amelieled** [comment]
Right, this feature is linked with #257 .
Do you plan to add this feature soon?

**Comment by gabrielhdt** [comment]
I don't think we want to, IMO it's a lot clearer to not export automatically what's opened.

**Comment by amelieled** [comment]
Yes, but we can add a new command, for example `export` to do this if it's necessary.

**Comment by gabrielhdt** [comment]
Right, perhaps we could think of something like the `include` of ocaml.

**Comment by amelieled** [comment]
And just to be clear about my first request: is it normal that a symbol in `C.lp` can only be called in `A.lp` by its short name (so not with its long name)?

**Comment by gabrielhdt** [comment]
Well, it's a bit strange, I would have expected the  code to fail on the `open tests.C`, and then you shouldn't be allowed to write `c` anyway in `A.lp` because `C.lp` isn'd required nor opened. So you shouldn't be able to call `c` in `A.lp`, it may be flawed. Or I don't understand `open`.

**Comment by amelieled** [comment]
In my first example, I opened `C.lp`, but this file isn't required.

**Comment by gabrielhdt** [comment]
It shouldn't be allowed.

**Comment by amelieled** [comment]
So, your goal is to hide the symbols in `C.lp` when you are in `A.lp`?
Indeed, in this case, there is no way to use in `A.lp` the symbols defined in `C.lp`.

**Comment by gabrielhdt** [comment]
Well, there is a way: you have to `require tests.C`

**Comment by amelieled** [comment]
OK right, I see.
It's a bit strange, because if I understand correctly, you can write:

C.lp:
```
symbol c : TYPE;
```
B.lp:
```
require open tests.C;
symbol b1 : c;
symbol b2 : tests.C.c;
```

A.lp:
```
require open tests.B;
```
Then, you can use `b1` or `b2` on `A.lp`, but how can the type-checker check their type?
It seems very logical that the `require` command is recursive.

**Comment by fblanqui** [comment]
The type-checker knows their type but the user cannot write it without adding a require. This may look strange indeed but it is not considered as a mistake for the moment. This issue is therefore closed as what you require is a duplicate of https://github.com/Deducteam/lambdapi/issues/257.
