### ISSUE TITLE
What is the semantics of `left/right associative`?

### ISSUE THREAD

**Issue by amelieled** [Deducteam/lambdapi#708]
I'm trying to understand the semantics of `left/right associative`, but:
* the answer isn't in the documentation (btw, this syntax is only defined in `syntax.bnf`)
* when I inspected the code, it seems that these keywords (`left` and `right`) are related to dead code.
* the only testing file about this is `ac.lp`, but LP checks the file even if I delete the option `left`.

**Comment by gabrielhdt** [comment]
It's supposed to be documented in <https://lambdapi.readthedocs.io/en/latest/commands.html#notation>, and the documentation is being revised in pull request #664. Its used internally by the pratt parser, particularly here
https://github.com/Deducteam/lambdapi/blob/63796ccadcc9147c5badd9a87f626611f63e3c4c/src/parsing/pratt.ml#L42
which is the code that allows the pratt parser to retrieve the associativity of a symbol. It's tested a lot in the test suite of the pratt parser (<https://forge.tedomum.net/koizel/pratter/-/raw/master/t/main.ml>).

**Comment by fblanqui** [comment]
Gabriel, I guess Amélie is talking about the symbol modifiers (https://lambdapi.readthedocs.io/en/latest/commands.html#symbol), not the notations. Indeed, this is not explained in details in the user manual, but a reference is given: http://dx.doi.org/10.1007/978-3-540-71316-6_8. Roughly, x+y+z is internally represented as (x+y)+z if + is left associative, and x+(y+z) if + is right associative. Moreover, t+u is internally represented as u+t if + is commutative and t>u in some unspecified total order on terms.

**Comment by fblanqui** [comment]
So this is not actually an issue. You should have put this in discussions instead.

**Comment by amelieled** [comment]
In fact, I don't understand: when someone defines a symbol associative, it means both left associative and right associative.
I understand that you need to have a unique representation internally, but from a user perspective, what does that change?
In the `ac.lp` testing file, it doesn't change anything, but can you give an example that changes something?

Also, in the documentation there is no mention that we can write `left associative` and by default `associative` = `right associative`.

Finally, if a user declares a symbol with `left associative`, but also with `left associative`, does that make sense?

**Comment by fblanqui** [comment]
It's clear that, if the terms are internally represented in some specific way, then some user rules might not be necessary or, on the contrary, some user definitions can rely on this.
I agree that the documentation needs to be developed and some examples provided but why are you interested in this feature that you do not understand?
I don't understand the last question.

**Comment by amelieled** [comment]
There is a mistake on the last question: 
Finally, if a user declares a symbol with `left associative`, but also with `notation left`, does that make sense?

**Comment by fblanqui** [comment]
These are two different things. The notation is about parsing: to use + as infix and says whether x+y+z should be parsed as (x+y)+z or x+(y+z). The modifier is about internal term representation: it says whether (x+y)+z should be transformed into x+(y+z) or vice versa (whether + is infix or not). Of course, it would be less efficient to add on a left associative symbol a right associative notation, as x+y+z would be parsed as x+(y+z) and then transformed into (x+y)+z.
