### ISSUE TITLE
Identifiers not correctly qualified for printing

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#729]
Let the following file `reqbool.lp` be in `tests/OK` (for convenience),
```
require tests.OK.bool as B;
symbol bool_neg: B.B → B.B;
symbol negate b ≔ B.bool_neg b;
```
then we have the following interaction
```
$ lambdapi check -v3 reqbool.lp
[...]
Checked "/home/hondet/workspace/deducteam/lambdapi/tests/OK/bool.lp"
(symb) add bool_neg : B.B → B.B
(symb) add negate : B.B → B.B ≔ λ b, bool_neg b
Checked "/home/hondet/workspace/deducteam/lambdapi/tests/OK/bool_req.lp"
```
and we see that `bool_neg` is not correctly qualified, it reads `bool_neg` instead of `B.bool_neg`.

This can be particularly confusing when developing generic libraries where, for instance, one defines the `cons` on lengthed lists, another one on lists, such that `LList.cons` and `List.cons` end up being printed as `cons`.

**Comment by fblanqui** [comment]
Right, those verbose messages could be improved by indicating the file name for instance.
But this does not mean that printing is incorrect. When an error occurs, the faulty terms are printed in the context where they appear, so are not qualified. This is what users usually expects, don't they? If really needed, a printing option could be added to force printing qualified identifiers (but it quickly gets more lengthy and more difficult to read).

**Comment by gabrielhdt** [comment]
It seems to me that the printing is incorrect because the term `negate : B.B → B.B ≔ λ b, bool_neg b` is not defined anywhere in this file. If it was printed in the context where it appears, it should be `B.bool_neg` shouldn't it? I'd intuitively think that copy-pasting what's printed at the same place should typecheck; so I'd expect to have `negate : B.B → B.B ≔ λ b, B.bool_neg b`. 

If I attribute a computational content to `bool_neg` that is different from the one of `B.bool_neg`, the result is really confusing, not to say wrong since `B.bool_neg` is not convertible with `bool_neg`.

**Comment by fblanqui** [comment]
Ah, I see the problem you were talking about now. But I cannot reproduce it. On master, no definition is printed.

**Comment by gabrielhdt** [comment]
My mistake, I was on a branch of mine, but the bug still exist on master. The following file is quite explicit
```
require tests.OK.bool as B;
symbol T : (B.B → B.B) → TYPE;
symbol bool_neg: B.B → B.B;
symbol foo : T B.bool_neg;
symbol bar : T bool_neg;
assertnot ⊢ T B.bool_neg ≡ T bool_neg;
```
which produces
```shell
Checked "[...]/lambdapi/tests/OK/bool.lp"
(symb) add T : (B.B → B.B) → TYPE
(symb) add bool_neg : B.B → B.B
(symb) add foo : T bool_neg
(symb) add bar : T bool_neg
(asrt) it is false that T bool_neg ≡ T bool_neg
Checked "[...]/lambdapi/tests/OK/boolreq.lp"
```
with the last assertion being quite confusing.

**Comment by fblanqui** [comment]
@gabrielhdt Your comments on #731 are welcome!
