### ISSUE TITLE
Logging depth of scoping

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#744]
I see that an argument has been added to the scope functions to log the depth 
https://github.com/Deducteam/lambdapi/blob/fa885c1e4b8b41c7e698787c969c3e59bbf71af6/src/parsing/scope.ml#L285

but wouldn't be enough to indent the output accordingly to the depth (with boxed and formats), and drop that extra argument? I feel that adding arguments clutters the code, which is already complicated enough.

**Comment by fblanqui** [comment]
If you can get the same output by using boxes, why not.

**Comment by fblanqui** [comment]
@gabrielhdt I propose to close this issue-question. It can of course be reopened later if needed.
