### ISSUE TITLE
ocamlformat is out of date

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#748]
running `dune build @fmt` prints
```
ocamlformat: Error while parsing .ocamlformat:
             For option "version": expecting "0.19.0" but got "0.15.0"
```

**Comment by fblanqui** [comment]
ocamlformat moved to 0.20.0

**Comment by gabrielhdt** [comment]
We must change the line
https://github.com/Deducteam/lambdapi/blob/0f815a939b4b56520f77a214eb3ad1a47c9b8dd3/.ocamlformat#L1

**Comment by fblanqui** [comment]
Right. But ocamlformat is not used yet. In fact, there should be no such file. Perhaps we could use it after your PR.

**Comment by fblanqui** [comment]
@gabrielhdt What is the effect of having an .ocamlformat file?
