### ISSUE TITLE
Cannot generate documentation

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#762]
```sh
$ make doc

Running Sphinx v3.4.3

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/config.py", line 326, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/lib/python3/dist-packages/sphinx/util/pycompat.py", line 88, in execfile_
    exec(code, _globals)
  File "/home/hondet/workspace/deducteam/lambdapi/docs/conf.py", line 81, in <module>
    import sphinx_rtd_theme
ModuleNotFoundError: No module named 'sphinx_rtd_theme'
```
It should be said in `docs/README.md` that the python package `sphinx_rtd_theme` is needed.

**Comment by fblanqui** [comment]
I have no problem on my machine with sphinx v3.3.1, and the generated doc on https://lambdapi.readthedocs.io/en/latest/tactics.html seems fine. Perhaps I already have this package installed. How to get this package installed?

**Comment by gabrielhdt** [comment]
You can see if it's installed with `pip list | grep sphinx-rtd-theme`. It can be installed with `pip install sphinx_rtd_theme`.
