### ISSUE TITLE
Wrong meta type generation in scoping

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#767]
example due to @amelieled
```
constant symbol Set : TYPE;
injective symbol τ : Set → TYPE;
constant symbol B : Set;
type λ (f : _ → _ → τ B) (g : τ B → τ B) b1 b2, f (g b1) (g b2);
```

**Comment by fblanqui** [comment]
The problem is in Scope.scope_domain:
https://github.com/Deducteam/lambdapi/blob/b4ce95c10abe91ee9abc6993b41d7f5ab95d49f9/src/parsing/scope.ml#L269-L275
In case a type is given (last case), scope is called on it:
https://github.com/Deducteam/lambdapi/blob/b4ce95c10abe91ee9abc6993b41d7f5ab95d49f9/src/parsing/scope.ml#L467-L468
And in case of _ we have:
https://github.com/Deducteam/lambdapi/blob/b4ce95c10abe91ee9abc6993b41d7f5ab95d49f9/src/parsing/scope.ml#L345
At this point we forgot that _ stands for a type and not for an object.
scope should have an additional parameter to know whether we are scoping an object or a type.
In case of a type, we need to call fresh_meta_type.

**Comment by fblanqui** [comment]
@gabrielhdt https://github.com/Deducteam/lambdapi/pull/696 has the same problem.

**Comment by gabrielhdt** [comment]
I see. Do you intend to fix the master branch, or would it be ok if I fix my branch, and we merge it after?
