### ISSUE TITLE
The subject-reduction algorithm does not take into account quantified constraints

### ISSUE THREAD

**Issue by thiagofelicissimo** [Deducteam/lambdapi#813]
The following example shows that the rewriting rules generated by Guillaume's encoding of eta-expansion are sometimes rejected by Lambdapi's subject reduction check, even though they preserve typing. This encoding is used in Agda2Dedukti, and thus the files containing such rules are rejected. In Dedukti this was solved by using bracket arguments, which is a hack that avoids checking subject reduction, and thus is unsatisfying.
```
constant symbol Set : TYPE;
symbol El : Set → TYPE;
symbol η (A : Set) : El A → El A;
rule η _ (η $A $x) ↪ η $A $x;

constant symbol Σ (A : Set) (B : El A → Set) : Set;
constant symbol TypeΣ (A : Set) (B : El A → Set) : TYPE;
rule El (Σ $A $B) ↪ TypeΣ $A (λ x, $B (η $A x));

constant symbol intro-Σ (A : Set) (B : El A → Set) (a : El A) (b : El (B (η A a))) : El (Σ A B);
symbol fst (A : Set) (B : El A → Set) (p : El (Σ A B)) : El A;
symbol snd (A : Set) (B : El A → Set) (p : El (Σ A B)) : El (B (η A (fst A B p)));

rule η (Σ $A $B) $p ↪ intro-Σ $A (λ x, $B (η $A x)) (η $A (fst $A (λ x, $B (η $A x)) $p)) (η ($B (η $A (fst $A (λ x, $B (η $A x)) $p))) (snd $A (λ x, $B (η $A x)) $p));

rule fst _ _ (intro-Σ $A _ $a _) ↪ η $A $a;
rule snd $A' $B' (intro-Σ $A $B $a $b) ↪ η ($B (η $A $a)) $b; // fails here
```
When checking the typing constraints of the lhs we get `El (Σ A B) = El (Σ A' B')` and thus `TypeΣ A (λ x, B (η A x)) = TypeΣ A' (λ x, B' (η A' x))`, but as TypeΣ is a constant symbol, we get `A = A'` and `(λ x, B (η A x)) = (λ x, B' (η A' x))`. The rhs has the same type as the lhs when `B (η A a) = B' (η A' a)`, and by `B (η A a) = (λ x, B (η A x)) a = (λ x, B' (η A' x)) a = B' (η A' a)` this is indeed the case. However, Lambdapi is not currently capable of checking this.

**Comment by thiagofelicissimo** [comment]
El is not injective : `El (Σ A B) = El (Σ A (λ x, B (η A x)))` but `Σ A B /= Σ A (λ x, B (η A x))`
Anyway, here is an example which shows the same problem even when El is marked as injective
```
constant symbol Set : TYPE;
injective symbol El : Set → TYPE;
symbol η (A : Set) : El A → El A;
rule η _ (η $A $x) ↪ η $A $x;

constant symbol Σ (A : Set) (B : El A → Set) : Set;
constant symbol TypeΣ (A : Set) (B : El A → Set) : TYPE;
rule El (Σ $A $B) ↪ TypeΣ $A (λ x, $B (η $A x));

constant symbol intro-Σ (A : Set) (B : El A → Set) (a : El A) (b : El (B (η A a))) : El (Σ A (λ x, B (η A x)));
symbol fst (A : Set) (B : El A → Set) (p : El (Σ A (λ x, B (η A x)))) : El A;
symbol snd (A : Set) (B : El A → Set) (p : El (Σ A (λ x, B (η A x)))) : El (B (η A (fst A (λ x, B (η A x)) p)));

rule η (Σ $A $B) $p ↪ intro-Σ $A (λ x, $B (η $A x)) (η $A (fst $A (λ x, $B (η $A x)) $p)) (η ($B (η $A (fst $A (λ x, $B (η $A x)) $p))) (snd $A (λ x, $B (η $A x)) $p));

rule fst _ _ (intro-Σ $A _ $a _) ↪ η $A $a;
rule snd $A' $B' (intro-Σ $A $B $a $b) ↪ η ($B (η $A $a)) $b; // fails here
```

**Comment by fblanqui** [comment]
We could perhaps solve this problem by declaring η as sequential (see Matching strategy modifier in https://lambdapi.readthedocs.io/en/latest/commands.html#symbol) and add the rule η _ $x --> $x.
Then, El becomes injective modulo η.
To avoid this modulo, we need to use the rule
rule El (Σ $A (λ x,$B.[x])) ↪ TypeΣ $A (λ x, $B (η $A x));
instead of rule El (Σ $A $B) ↪ TypeΣ $A (λ x, $B (η $A x));
This is however not sufficient because the SR algorithm ends with a constraint of the form:
B (η A' a) = B' (η A' (fst A' (\x, B' (η A' x)) (intro A' B a b)))
where both sides are in whnf. If we reduces both sides without using η _ $x --> $x, we get:
B (η A' a) = B' (η A' a)
And, from the typability of the LHS, we have A = A' and
forall x, B (η A x) = B' (η A' x)
However, currently, the SR algorithm does not use quantified constraints.

**Comment by thiagofelicissimo** [comment]
In this case, I have the impression that we don't need injectivity of El for your SR algorithm to work, right? Why the workaround with this sequential modifier then?

So I guess this shows once more the benefits of implementing your algorithm for SR, as it seems to me it would solve this problem. It would also allows us to typecheck definitions like the following without having to declare El as injective, which is a hack, since it is not injective.
```
injective symbol El : Π {s : Sort}, U s → TYPE;

constant symbol u s : U (𝓐 s);
rule El (u $s) ↪ U $s;

constant symbol Prod {s1 s2} (_ : ∃𝓡 s1 s2) : Π (A : U s1) (B : El A → U s2), U (𝓡 s1 s2);
constant symbol abs {s1 s2} (i : ∃𝓡 s1 s2) : Π {A : U s1} {B : El A → U s2}, (Π x : El A, El (B x)) → El (Prod i A B);
symbol app {s1 s2} (i : ∃𝓡 s1 s2) : Π {A : U s1} {B : El A → U s2}, El (Prod i A B) → Π x : El A, END → El (B x);
rule app _ (abs _ $M) $N _ ↪ $M $N;
```
