### ISSUE TITLE
Identifiers and forbidden letters

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#814]
https://github.com/Deducteam/lambdapi/blob/089f239ad951c8848e6b1394fa38dfe2eacd3a1c/src/parsing/lpLexer.ml#L156

Why are the characters `/`, `?`, `*`, `|` and `$` forbidden? As far as I understand, allowing them wouldn't clash with the language.

**Comment by gabrielhdt** [comment]
Furthermore this modification hasn't been documented in the changelog.

**Comment by fblanqui** [comment]
| is VBAR; it is used in inductive type definitions.
$ is used for pattern variables.
? was used at some point but I think we can remove it now.
/ and * are used for multi-lines comments but, indeed, there is perhaps no problem in adding them.
I don't want the user to be able to define "*/" as identifier, or anything containing "*/" like "*/*".
And I believe that sedlex parses the longest possible string.

**Comment by fblanqui** [comment]
If we allow * and /, how to avoid the identifier `a*/`?

**Comment by fblanqui** [comment]
Allow * and / in regular identifiers make tests/OK/comment_in_qid.lp fail:
```
assert ⊢ tests./*comment*/OK.bool.true : tests.OK.bool.B;
```

**Comment by fblanqui** [comment]
Current solution in #815: allow * but forbid / (except as a single character).
