### ISSUE TITLE
Lambdapi does not allow postfix operators

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#827]
like ⁻¹ or !

**Comment by fblanqui** [comment]
@gabrielhdt Could this be added in Pratter?

**Comment by gabrielhdt** [comment]
Probably, but I don't think I'll take the time to look at it.

**Comment by gabrielhdt** [comment]
One may look at https://matklad.github.io/2020/04/13/simple-but-powerful-pratt-parsing.html

**Comment by fblanqui** [comment]
Fixed in https://github.com/Deducteam/lambdapi/pull/879.
