### ISSUE TITLE
Bad checking with `notation` command

### ISSUE THREAD

**Issue by amelieled** [Deducteam/lambdapi#845]
The following file is accepted by LP:
```
symbol O : TYPE;
symbol T : O;
symbol p : O → TYPE;
symbol ¬  : p T → p T → p T;
symbol ⊥ : p T;
symbol ⊤ : p T;
notation ⊤ infix left 5;
rule $x ⊤ $y ↪ ¬ ⊥;
```

By the way, the documentation doesn't specify the default precedence.

**Comment by fblanqui** [comment]
What do you mean? There is no default precedence: a priority level must always be given.

**Comment by fblanqui** [comment]
Concerning arity checking, is #848 ok?

**Comment by amelieled** [comment]
> What do you mean? There is no default precedence: a priority level must always be given.

It should be the case for ->.

> Concerning arity checking, is https://github.com/Deducteam/lambdapi/pull/848 ok?

It seems to be nice. Thanks.

**Comment by fblanqui** [comment]
Could you please clarify what you would like and give an example?

**Comment by amelieled** [comment]
```
constant symbol typ : TYPE;
constant symbol bool : typ;
symbol eta : typ → TYPE;

constant symbol arr : typ → typ → TYPE;
notation arr infix left 5;
```
How do you parse `eta bool → bool arr bool`?

**Comment by fblanqui** [comment]
→ has priority higher than any symbol application (see https://raw.githubusercontent.com/Deducteam/lambdapi/master/doc/lambdapi.bnf):
`eta bool → bool arr bool` is parsed as `(eta bool) → (bool arr bool)`:
```
assert ⊢ eta bool → bool arr bool ≡ (eta bool) → (bool arr bool);
```

**Comment by amelieled** [comment]
> → has priority higher than any symbol application (see https://raw.githubusercontent.com/Deducteam/lambdapi/master/doc/lambdapi.bnf): `eta bool → bool arr bool` is parsed as `(eta bool) → (bool arr bool)``

Where?

What is a symbol application?

So the precedence is 0? 1? 0.1?

**Comment by fblanqui** [comment]
→ is not a function symbol and a → b is not a function symbol application: it is syntactic sugar for Π _:a, b. Priorities are only used for ordering function symbol applications. The parsing of a → b is governed by rules different from the ones of function symbol applications. For details, see the BNF grammar of terms.

**Comment by amelieled** [comment]
Do you mean: → IS a function symbol and a → b IS a function symbol application?

**Comment by amelieled** [comment]
Again, what is a symbol application?
What is the meaning of `saterm`?

**Comment by amelieled** [comment]
No answer here.
It's possible to add explanations about the non-terminals?
