### ISSUE TITLE
Breaking changes with new release of bindlib

### ISSUE THREAD

**Issue by rlepigre** [Deducteam/lambdapi#852]
To avoid breakage, you will need to constrain the bindlib version used by Lambdapi to be exactly 5.0.1 due to the release of 6.0.0, which contains some changes of API and semantics. I can help porting the code to version 6.0.0 once the package is published.

There is already a PR for publishing Bindlib 6.0.0 (see https://github.com/ocaml/opam-repository/pull/20808), and I took care of constraining the existing Lambdapi versions to bindlib 5.0.1 there.

**Comment by fblanqui** [comment]
Fixed in #854 .

**Comment by rlepigre** [comment]
I had a quick look to the diff, and this does not look like this is enough to support Bindlib 6.0.0. This new release of Bindlib introduces a change of semantics around variable renaming. The code of all functions that print variables (i.e., the result of `Bindlib.name_of`) need to be updated to use Bindlib contexts. See https://github.com/rlepigre/ocaml-bindlib/blob/master/CHANGELOG.md.

**Comment by fblanqui** [comment]
Hi Rodolphe. Tests and libraries are passing. So I do not plan to make any further changes at the moment.

**Comment by rlepigre** [comment]
OK. I would at least fix the Bindlib version to 5.0.1 to avoid printing code being broken (i.e., variables being printed with the wrong name). The breakage will be silent, quite rare, and probably not captured by tests with Bindlib 6.0.0. Of course, feel free to disregard my warning if you are fine with this.
