### ISSUE TITLE
The terminal UID

### ISSUE THREAD

**Issue by amelieled** [Deducteam/lambdapi#853]
Input:
```
symbol _toto : TYPE;
```
Output:
```
Unexpected token: "_".
```
But I'm not sure that is an error, because I don't find the definition of the terminal `UID`.
I know that it was possible that an identifier begins with "_" in the past.

**Comment by fblanqui** [comment]
Which version of Lambdapi do you use?

**Comment by amelieled** [comment]
The last one.
But I made an error: the correct identifier is `_/toto`, and the problem comes from `/`.

**Comment by fblanqui** [comment]
This is explained in https://lambdapi.readthedocs.io/en/latest/terms.html: / cannot appear inside an identifier except if it is alone.

**Comment by fblanqui** [comment]
See also https://github.com/Deducteam/lambdapi/issues/814.

**Comment by amelieled** [comment]
OK, but it's not explained in lambdapi.bnf.

**Comment by fblanqui** [comment]
lambdapi.bnf describes the grammar not the lexer and it is automatically generated from the grammar
