### ISSUE TITLE
Version cmdliner & why3

### ISSUE THREAD

**Issue by CoghettoR** [Deducteam/lambdapi#866]
Hi,
For beginners like me, the compilation works if you use the line:

opam install dune bindlib timed sedlex menhir pratter yojson cmdliner.1.1.1 why3.1.4.1 alcotest alt-ergo odoc

rather than the line:

opam install dune bindlib timed sedlex menhir pratter yojson cmdliner why3 alcotest alt-ergo odoc

it is obvious when reading the file dune-project, but not obvious when you don't know dune ;-)

**Comment by fblanqui** [comment]
Thank you for your remark! We will fix the doc.

**Comment by CoghettoR** [comment]
it may not be necessary.

it's probably related to my "opam switch" installation. 
I'll take a closer look and get back to you.

**Comment by CoghettoR** [comment]
Everything is back to normal.
This issue obsolete now: see https://github.com/Deducteam/lambdapi/commit/a7717902b83d9b4ef8a1bf7d4b0ae43aa30585aa 
thanks
