### ISSUE TITLE
alt-ergo did not find a proof

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#882]
Running `dune exec -- lambdapi check tests/OK/why3.lp` returns
```
[.../lambdapi/tests/OK/why3.lp:7:14-23] "Alt-Ergo" did not find a proof
```
with alt-ergo-lib 2.4.1 installed

**Comment by fblanqui** [comment]
Which version of lambdapi do you use? What is the output of `why3 config detect`?
