### ISSUE TITLE
compilation problem linked to why3

### ISSUE THREAD

**Issue by FilaliM** [Deducteam/lambdapi#899]
I have clone the git repository.
I have upgraded through opam my packages.
I get the following error:
```
filali@tourfan lambdapi % make             
File "src/handle/why3_tactic.ml", line 257, characters 22-33:
257 |     try Why3.Whyconf.(load_driver why3_main why3_env prover)
                            ^^^^^^^^^^^
Error: Unbound value load_driver
make: *** [bin] Error 1
filali@tourfan lambdapi % 
```
By the way:
```
filali@tourfan lambdapi % which why3
/Users/filali/.opam/4.11.1+default-unsafe-string/bin/why3
filali@tourfan lambdapi % why3 --version
Why3 platform, version 1.5.0+git
```

why3 config detect has been done successfully.

**Comment by fblanqui** [comment]
This is strange... Did you do `eval $(opam env)`? Could you please try with another switch (e.g. 4.14.0)?

**Comment by fblanqui** [comment]
@FilaliM You seem to have fixed your problem. Should I close this issue? For the record, could you please explain what went wrong and how you fixed it?

**Comment by FilaliM** [comment]
Actually it works after installing opam switch 4.14.0 (and recompiling some packages). 
Previously, I was on opam switch 4.11.1+default-unsafe-string.
Thanks.
