### ISSUE TITLE
Postfix notation become infix in proof mode

### ISSUE THREAD

**Issue by qbuzet** [Deducteam/lambdapi#903]
```
symbol ! : ℕ → ℕ; 

notation ! postfix 40;

rule 0 ! ↪ 1
with (s $n) ! ↪ (s $n) × $n !;

opaque symbol fact0 : π (0 ! = 1) ≔
begin
  reflexivity;
end;
```
![postfix](https://user-images.githubusercontent.com/90800237/183035147-71e5bd5d-5035-4885-baf4-02bf7c68f6bc.png)

**Comment by fblanqui** [comment]
Printing of postfix symbol application has not been implemented in the PR #879 adding postfix symbols.
