### ISSUE TITLE
problem with postfix symbol parsing

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#922]
See https://github.com/fblanqui/lib/pull/1#issuecomment-1280790268.
```
git add remote garchery git@github.com:QGarchery/lib.git
git fetch garchery
git checkout -b binint garchery/master
```
Then replace "s" by "+1" and add after the definition of +1:
```
notation +1 postfix 100;
```
You get:
```
inductive ℕ : TYPE ≔
| 0 : ℕ
| +1 : ℕ → ℕ;
notation +1 postfix 100;
...
```
First thing strange:
```
rule is0 0 ↪ true
with is0 (+1 _) ↪ false;
```
does not fail while we should write
```
with is0 (_ +1) ↪ false;
```
But the main problem comes with the first lemma:
```
opaque symbol s≠0 [n] : π (n +1 ≠ 0) ≔
begin
  assume n h; refine ind_eq h (λ n, istrue(is0 n)) top
end;
```
I get:
```
[/home/blanqui/src/lib/Nat.lp:122:2-12] Not a typing goal.
```
Indeed, the first goal is:
```
n: Π y: (ℕ → ℕ), ?35.[y]
------------------------------
?35.[+1] ≡ ℕ
```
Note that ≠ is defined in Eq as follows:
```
symbol ≠ [a] (x y : τ a) ≔ ¬ (x = y); notation ≠ infix 10; // \neq
```

**Comment by gabrielhdt** [comment]
@fblanqui can you post the lambdapi commit and the pratter version you use?

**Comment by gabrielhdt** [comment]
It seems there's a conflict with the builtins: in `Nat.lp`, it works when `builtin "+1" := +1` is commented out.

**Comment by fblanqui** [comment]
I understand the problem now. Builtin "+1" s sets the notation for s to Succ.

**Comment by fblanqui** [comment]
Hi @gabrielhdt . I think that I fixed the problem in #926. But there is still a problem. See tests/OK/List.lp. (size $l) +1 is not parsed as expected:
```
[scop] 0. (size $l) +1
[scop]  1. size $l
[scop] find_qid size
[scop]   2. $l
[scop]   2. got $3
[scop]  1. got size $3
[scop]  1. +1
[scop] find_qid +1
[scop]  1. got +1
[scop] 0. got size $3 +1
[/home/blanqui/src/lambdapi/tests/OK/List.lp:19:5-33] [ℕ] and [Π x: (ℕ → ℕ), ?14.[x]] are not unifiable.
The rewriting rule does not preserve typing.
17:33 ~/lambdapi (succ) 
```

**Comment by gabrielhdt** [comment]
Wouldn't that come from the scoping process, since it's where parentheses are handled?

**Comment by fblanqui** [comment]
Perhaps it is related to the fact that size has an implicit argument?

**Comment by fblanqui** [comment]
Hi @gabrielhdt. Any progress of this issue? Will you have time in the coming weeks to look at this problem?
