### ISSUE TITLE
make install segfault when lp-lsp is running

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#95]
Error: exception Sys_error("/local/blanqui/.opam/4.07.0/bin/lp-lsp: Text file busy")
Backtrace:
Raised by primitive operation at file "stdlib.ml", line 316, characters 29-55
Called from file "src/stdune/io.ml", line 148, characters 19-178
Called from file "src/stdune/exn.ml", line 21, characters 8-11
Re-raised at file "src/stdune/exn.ml", line 23, characters 30-37
Called from file "bin/main.ml", line 553, characters 17-264
Called from file "list.ml", line 106, characters 12-15
Called from file "list.ml", line 106, characters 12-15
Called from file "src/fiber/fiber.ml", line 111, characters 22-27
Called from file "src/fiber/fiber.ml", line 299, characters 6-13
                   
I must not segfault.  Uncertainty is the mind-killer.  Exceptions are
the little-death that brings total obliteration.  I will fully express
my cases.  Execution will pass over me and through me.  And when it
has gone past, I will unwind the stack along its path.  Where the
cases are handled there will be nothing.  Only I will remain.
GNUmakefile:158 : la recette pour la cible « install » a échouée
make: *** [install] Erreur 1

**Comment by ejgallego** [comment]
Indeed report upstream. What version of dune are you using? Note that indeed Unix doesn't allow modifications of files that are currently being executed.

**Comment by fblanqui** [comment]
1.4.0

Le 18/10/2018 à 12:21, Emilio Jesús Gallego Arias a écrit :

**Comment by ejgallego** [comment]
Did you report this upstream @fblanqui ?

**Comment by fblanqui** [comment]
No. I am too busy at the moment to do this. :-(

Le 08/11/2018 à 20:20, Emilio Jesús Gallego Arias a écrit :

**Comment by rlepigre** [comment]
I'm running `dune.1.4.0` and I can't reproduce. This must have been fixed upstream.
