### ISSUE TITLE
Adding a clear tactic to keep a clean the context ?

### ISSUE THREAD

**Issue by NotBad4U** [Deducteam/lambdapi#963]
Hi everyone!

I am working on proofs where I can have many hypotheses. For example, one of my proofs reaches 50 hypotheses in the context but most of them can be discarded before the end of the proof. Having a tactic `clear h;` (or `remove`, `clean`) that deletes hypothesis `h` from the context could be interesting for me to keep a readable local context of a main goal.

 I imagine that I could use this tactic like this:
 
```
opaque symbol my_lem: T ≔
begin
    ...
    have myHyp: U { ... };
    apply myHyp;
    clear myHyp;
    ...
end;
```

Besides, I created an issue but if you prefer I can just add a new comment in #907 and close this issue.

I can help to develop this feature if you think that it is interesting to add this 😃.

**Comment by fblanqui** [comment]
Hi Alessio. Thank you for your issue. This would indeed be interesting to add a remove tactic taking a list of identifiers as argument. And it should not be too difficult to implement as it consists in reducing the context of a metavariable. If your goal is x1:A1,..,xn:An|-?M[x1,..,xn]:B, then removing say xn consists in generating the new goal x1:A1,..,xn-1:An-1|-?N[x1,..,xn-1]:B and instantiating ?M by \x1:A1,..,\xn:An,?N[x1,..,xn-1]. I will be happy to review a PR if you want to submit one.

**Comment by NotBad4U** [comment]
Sure I can start to think about it @fblanqui! Could you point me to some points in the code where I should have a look before to see how the others tactics are implemented?

**Comment by fblanqui** [comment]
You can have a look at the way the assume tactic is implemented in https://github.com/Deducteam/lambdapi/blob/master/src/handle/tactic.ml. Here are some more pointers:
- the type meta is defined in core/term.ml
- core/libMeta.ml contains a few functions for generating/instantiating metas 
- the type goal is defined in handle/proof.ml
- the abstract syntax of tactics is defined in parsing/syntax.ml
- the concrete syntax is defined in parsing/lpParser.mly
