### ISSUE TITLE
explicit type required for ensuring subject reduction

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#986]
```
symbol Set:TYPE;
symbol ι:Set;
injective symbol τ:Set → TYPE;
symbol U:TYPE;
rule τ ι ↪ U;
symbol = [a] : τ a → τ a → U;
notation = infix 1;
symbol true:U;
rule @= ι $x $x ↪ $x;
rule $x = $x ↪ $x; // fails

[/home/blanqui/src/lambdapi/tmp/zo.lp:9:5-17] Cannot solve ι ≡ $1
Unable to prove type preservation.
```

**Comment by GuillaumeGen** [comment]
It seems legit to me. If there is a set `s`different of `ι`, then you can take a variable `x` in `τ s` and the left-hand side of the last rule you wrote is of type `U` (ie `τ ι`) whereas the right-hand side is of type `τ s`.

**Comment by fblanqui** [comment]
Right. @NotBad4U The problem is that the typing of the LHS does not generate enough constraints for fixing the type of x. Assume that an instance (t=t) of the LHS is typable. Its type is U. And the type of x is (\tau a) for some a. Now, the RHS t is of type (\tau a) which may not be equivalent to U as noticed by Guillaume. Hence the need to enforce a to be \iota.
