### ISSUE TITLE
Error when my inductive type have more than one parameter

### ISSUE THREAD

**Issue by NotBad4U** [Deducteam/lambdapi#989]
Hi!
When I try to add a second parameter to the inductive type 𝕃, I get the error:

`Cannot solve $130 □ ≡ $130 □`

Here is a snippet of code to reproduce the problem:

```
symbol Prop : TYPE;
injective symbol Prf : Prop → TYPE;
builtin "Prop" ≔ Prop;
builtin "P" ≔ Prf;

symbol Set : TYPE; 
injective symbol τ : Set → TYPE;

(a:Set) (b:Set) inductive 𝕃:TYPE ≔
| □  : 𝕃 a b
| ⸬   : τ a → τ b → 𝕃 a b → 𝕃 a b;
```

Thank you in advance!

**Comment by amelieled** [comment]
`τ b` is not typable because `b` has type `Prop` and `τ` has type `Set → TYPE`.

**Comment by NotBad4U** [comment]
Sorry @amelieled  I forgot to update the code in the issue, there is still a problem if `b` is a `Set`.
 @fblanqui  is investigating the error.

**Comment by fblanqui** [comment]
Sorry no. I am currently in Japan until June 11. I will try to look at that next week or when I am back.
